### ISSUE TITLE
Request: add support for Namecheap DNS?

### ISSUE THREAD

**Issue by WereCatf** [NginxProxyManager/nginx-proxy-manager#1151]
Currently nginx-proxy-manager doesn't have support for Namecheap's DNS, so I would like to request support be added.

The Go-acme Lego ( https://github.com/go-acme/lego ) seems like a pretty competent way of adding support for some of the missing DNS-services, including the aforementioned Namecheap. There is also the project at https://github.com/heralight/certbot_dns_namecheap but it's not being actively maintained and I don't know if it even works currently.

**Comment by chaptergy** [comment]
For this to be included in NPM, it would have to be available on the [Python Package Index](pypi.org). As it is licensed under the Apache 2 license, it shouldn't be a problem if anyone goes ahead and publishes it to PyPI.   
It would also be great if we knew it was working before it is implemented.

**Comment by DeviantEng** [comment]
Has there been any updates on namecheap support?  I've been doing LE manually outside of docker for a couple of years now via `dns-lexicon[namecheap]`.  Could support to NPM be added using that PyPi package?

**Comment by chaptergy** [comment]
As I said, a [certbot plugin](https://eff-certbot.readthedocs.io/en/stable/contributing.html#writing-your-own-plugin) has to be available via [PyPi](https://pypi.org/). As long as one of the conditions is not met, we can not add it.

**Comment by WereCatf** [comment]
Ugh. I guess I'll look into forking that one plugin there, testing it out and pushing to PyPi one of these days.

**Comment by knoxell** [comment]
Hey,

the https://github.com/heralight/certbot_dns_namecheap has a few deprecation warnings about using the old certbot plugin naming scheme, using deprecated [dns-lexicon](https://github.com/AnalogJ/lexicon) (2.x) Config and maybe the many Problem the service it uses to get the server IP (client ip) for the namecheap api is not active anymore. But you don't need the real IP, as a [comment](https://github.com/AnalogJ/lexicon/blob/66006e36440116bd98a10e7f5bec16d740a59d08/lexicon/providers/namecheap.py#L30) in the dns-lexicon namecheap plugin says, you can send any.

I forked it, cleaned the repo up and have a fully running plugin now, that is compatible with dns-lexicon 2.x and 3.x.

https://github.com/knoxell/certbot-dns-namecheap

I'll publish it as an pypi package and create a pull request for npm soon.

I would appreciate it, if anyone would look over the the code and leave me an issue or pull request if there is anything to be fixed.

I might change folder structure and create a better README some day, but other that that there is nothing I see that can be fixed.

Cheers!

**Comment by knoxell** [comment]
For anyone who is interested in this and doesn't wanna wait for the merge, `jc21/nginx-proxy-manager:github-pr-2312` now offers the latest `develop`(default) branch d2688cf (23.08.2022) with namecheap support.

**Comment by Vaevictus** [comment]
I just tested this via jc21/nginx-proxy-manager:github-pr-2312 and it worked great, thanks

**Comment by DerfOh** [comment]
Appears to be working for me 👍

**Comment by xppx99** [comment]
It's working great! Thanks for this
