### ISSUE TITLE
Add UID and GID variable

### ISSUE THREAD

**Issue by mgutt** [NginxProxyManager/nginx-proxy-manager#1226]
In Unraid its important of being able to set UID and GID to 99:100. I tried it through the following docker flag:
```
--user=99:100
```

But the NPM docker container isn't happy with it:
```
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
```

Some containers solve this by using additional variables:
https://hub.docker.com/r/linuxserver/mariadb#:~:text=boot%20and%20setup.-,Usage,-Here%20are%20some
```
    environment:
      - PUID=1000
      - PGID=1000
```

**Comment by mgutt** [comment]
Nope.

**Comment by rogierlommers** [comment]
Please also see this: https://github.com/jlesage/docker-nginx-proxy-manager/issues/271
I don't know what repo that is, but it does support docker --user params.
Personally I prefer to use this (original) one, but I do need to save data files as my own user.

**Comment by renzo-s** [comment]
There is a `s6-applyuidgid` directive to do this after init. The `jslesage` repo seems to be quite a behind, also would not recommend using another source for your reverse proxy.

Writing everything as root on the host can interfere with common backup strategies, RAID setups and remote monitoring. Would love to see this get picked up soon.

**Comment by rogierlommers** [comment]
Yes me too; I don't want to use the jslesage repo either. So for me it's a must-have. Unfortunately I don't have the time nor skills to apply it in this repo. :(

**Comment by agorgl** [comment]
Waiting for this too!

**Comment by vdrover** [comment]
This is working for me: https://hub.docker.com/r/jc21/nginx-proxy-manager

```
    environment:
      PUID: $PUID
      PGID: $PGID
```
![192 168 86 59 2023-04-20 at 11 01 45 PM](https://user-images.githubusercontent.com/3143313/233538302-1846fd12-f6b1-4906-a8e0-90c3d3ba76e4.jpg)

**Comment by Moooartin** [comment]
Sorry to re-open this thread but the issue has changed a bit...
Since the environment have been added, The `PUID` and `PGID` work fine for the `2.10.2` and `2.10.3` but it is not working with the latest `2.10.4`.

Has it been removed?

**Comment by archive-r** [comment]
> Sorry to re-open this thread but the issue has changed a bit... Since the environment have been added, The `PUID` and `PGID` work fine for the `2.10.2` and `2.10.3` but it is not working with the latest `2.10.4`.
> 
> Has it been removed?

Same issue

**Comment by NeoMod** [comment]
thank you @vdrover. I can confirm this is working fine on _latest_ and solved the bunch of errors about file permission at startup under unraid.

**Comment by malavolti** [comment]
Dear All,

this is my docker-compose.yml:

```bash
services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:2.12.1'
    container_name: nginx-proxy-manager
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Rome
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```

and I get:

```bash
-------------------------------------
 _   _ ____  __  __
| \ | |  _ \|  \/  |
|  \| | |_) | |\/| |
| |\  |  __/| |  | |
|_| \_|_|   |_|  |_|
-------------------------------------
User:  npm PUID:1000 ID:1000 GROUP:1000
Group: npm PGID:1000 ID:1000
-------------------------------------

❯ Starting nginx ...
❯ Starting backend ...
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:4
[12/14/2024] [11:24:06 PM] [Global   ] › ℹ  info      Using Sqlite: /data/database.sqlite
[12/14/2024] [11:24:06 PM] [Global   ] › ℹ  info      Creating a new JWT key pair...
...
```


But folders get different UID and GID:

```bash
drwxr-xr-x 7 100999 100999 4096 14 dic 23.24 data
drwxr-xr-x 2 100999 100999 4096 14 dic 23.21 letsencrypt
```

can you tell me why, please?

Thank you so much!
Marco

**Comment by vdrover** [comment]
Just a bit of a stab in the dark, but have you added your user to the docker group? 

https://docs.docker.com/engine/install/linux-postinstall/

**Comment by malavolti** [comment]
> Just a bit of a stab in the dark, but have you added your user to the docker group?
> 
> https://docs.docker.com/engine/install/linux-postinstall/

Yes, I've added.

**Comment by malavolti** [comment]
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3252

I report also this issue that is rely on my problem.

Any help about this @vdrover @jc21 ? Thank you so much!

**Comment by ashipaek0** [comment]
Seems this issue where it does not respect the PGUID set and changes the folder ownership on boot is causing SSL acquisition to fail
