### ISSUE TITLE
forword remot real IP

### ISSUE THREAD

**Issue by elyashivhazan** [NginxProxyManager/nginx-proxy-manager#1324]
Hi, I saw some ways to fix it but none of this solution works. Is there any way I could get some help with that?

I`m trying to forword the real conction IP to my servers contaners (on the same host) but its pusing the npm IP in side the docker network

**Comment by baudneo** [comment]
Have you made any progress diagnosing your issues? Are you behind cloudflare or is it just a DDNS pointed to your Home IP and NPM?

I am behind cloudflare and no matter what I do I cannot get the remote IP to come through to be logged. Kills my fail2ban setup.

**Comment by elyashiv-hazan** [comment]
I just switch for nginx with configs files its more minimal and it works

**Comment by baudneo** [comment]
I figured it out via the advanced tab for ngonx proxy manager I will reply with some of my confogs and how they are setup

**Comment by Martydog** [comment]
This worked for me: 

I'm behind cloudflare and this is what i put in the advanced box: 

`real_ip_header CF-Connecting-IP;`

![image](https://user-images.githubusercontent.com/22003058/132127047-3985fcd6-a1f6-4ee4-ae0f-900f8f0921db.png)

**Comment by elyashiv-hazan** [comment]
i have try that before, no luck for me my servers inside my home are not getting the real ip no idea why. but with nginx its self its working

**Comment by NoskaOff** [comment]
Did someone found a solution ?

**Comment by Reemabnyslma** [comment]
الغاء

في السبت، ٥ نوفمبر ٢٠٢٢ ٦:٤٨ م N O S K A ***@***.***> كتب:

**Comment by baudneo** [comment]
> Did someone found a solution ? 

What is your issue and what headers are included in the request?

I have found success behind cloudflare using the CF-Connecting-IP. Are there any proxies or services your NPM is behind? Possibly could be using PROXY protocol?
