### ISSUE TITLE
limit_conn perip Throws Error

### ISSUE THREAD

**Issue by adoboligh1** [NginxProxyManager/nginx-proxy-manager#1432]
limit_conn perip 10; turns off the proxy host

**Comment by Nuke142** [comment]
Why it was closed?
I insert `limit_conn perip 10;` to Custom Nginx Configuration and host disabled, error.

**Comment by Nuke142** [comment]
@joeyboli 
Why it was closed?
I insert limit_conn perip 10; to Custom Nginx Configuration and host disabled, error.
