### ISSUE TITLE
Force SSL not working with non-standard port

### ISSUE THREAD

**Issue by ysslang** [NginxProxyManager/nginx-proxy-manager#1466]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

Similar to (this question)[https://serverfault.com/questions/338700/redirect-http-example-com12345-to-https-example-com12345-in-nginx]

**Nginx Proxy Manager Version**

2.9.9

**To Reproduce**
1. While create docker container, bind container's 443 port to any port other than 443 on host, like 60443
2. Create SSL certificates, create a proxy server and enable SSL and force-SSL
3. Request http://server_name:60443. You'll get an 400 Error 'The plain HTTP request was sent to HTTPS port';

**Expected behavior**

Get a 302 redirect to  https://server_name:60443

**Screenshots**

**Operating System**

**Additional context**

Solution is in the link too. Maybe 'error_page 497' is better than 'if() redirect'

**Comment by Danielv123** [comment]
This sounds like it is best solved by hosting nginx in the cloud and routing traffic back to your home network using an overlay network service like tailscale or zerotier. This way you won't have to deal with your ISP gatekeeping ports.

Normal http -> https redirection works by you entering http://my.domain:80 and being redirected to https://my.domain:443, which wouldn't work if you enter the wrong port.

**Comment by zierbeek** [comment]
does force ssl even work with the standard ports? At my instance, with subdomains, that isn't working

**Comment by yqchilde** [comment]
@ysslang Have you solved it? I have encountered the same situation.

**Comment by yqchilde** [comment]
> @ysslang Have you solved it? I have encountered the same situation.

我最后是这么解决的！
error_page 497 301 =301 https://your_domain:your_port$request_uri;

**Comment by RobertusIT** [comment]
> > @ysslang Have you solved it? I have encountered the same situation.
> 
> This is how I finally solved it! error_page 497 301 =301 https://your_domain:your_port$request_uri;

please can you explain better?

My isp block a port range, so i open 443 to 32763
80 to 32764

How can I setup in proxy manager?
