### ISSUE TITLE
Handling redirects in Express

### ISSUE THREAD

**Issue by MinHyeong-Lee** [NginxProxyManager/nginx-proxy-manager#1576]
**Is your feature request related to a problem? Please describe.**

I have an express application that is working perfectly on my local environment on port 5001. I need to deploy it on a production server running nginx listening on port 80. Below are some of the express routes

```javascript
router.get('/', (req, res) => {
    //home page, show login page
});


router.post('/login', (req, res) => {
    if(errors){
        //invalid credentials
        return res.redirect('..');
    }

    //successful login, redirect to admin area
    return res.redirect('../main');
})
```

and similar routes for authenticated admin users. The routes are not working properly when deployed on nginx using reverse proxy. The nginx reverse proxy settings are as follows:
```javascript
location / {
    proxy_pass http://192.168.219.240:5000/;
}

location /test2/ {
    proxy_pass http://192.168.219.240:5001/;
}
```

**Describe the solution you'd like**

I want the application to be accessible on the route v2manager on my production domain like example.com/v2manager. So all the routes become as:
```
example.com/test2/ for the home page
example.com/tset2/login for login POST route, and
example.com/tset2/main for after successful login
```

However, the redirects are not working properly, on login failure the ```return res.redirect('..')``` redirects me to example.com which has a different page whereas it should redirect to ```example.com/test2```

I can obviously change my application routes to add ```/test2/``` everywhere but the route ```test2``` can change frequently depending upon our environments and versioning. Also, a solution that would not hamper the local environment so that ```localhost:5001/login``` would work always

This is my NPM config
![image](https://user-images.githubusercontent.com/48749902/140859973-05f22b9f-01f2-4f82-ae09-16f78be281ba.png)

![image](https://user-images.githubusercontent.com/48749902/140859832-b6483fae-8878-4765-9da6-744dcf1eb2e1.png)

**Comment by MMIINNHH** [comment]
Sorry for registering the wrong label.
But I'm not good at using github..
I don't know how to edit label

**Comment by ma-karai** [comment]
have you tried the custom location tab?

**Comment by MMIINNHH** [comment]
> have you tried the custom location tab?

![image](https://user-images.githubusercontent.com/48749902/141709875-ad5bb2bf-0d39-4f99-9bda-dbc6a50935da.png)

I don't know if I did it right, but I tried this. 
Access to example.com/test2 works. 
But redirection still doesn't work.

not to example.com/test2/login
example.com/login

:(
