### ISSUE TITLE
Can I proxy just a subfolder?

### ISSUE THREAD

**Issue by GordonCopestake** [NginxProxyManager/nginx-proxy-manager#1577]
I have an internal web server with lots of folders: host1/sub1, host1/sub2, host1/sub3 etc

Am I able to proxy just a **single subfolder** so a user can go to proxy/sub3 to get to host1/sub3 but **can't** go to proxy/sub1 or proxy/sub2 to get to those folders?

Reason is I would like to expose just one folder on my internal host to the internet, but not any others.

I've tried adding sub3 as a _custom location_ but I just get 404's when I try. What's the right way to do this (assuming I can)

Thanks

**Comment by IceflowRE** [comment]
Same as #40
