### ISSUE TITLE
Fail to Authenticate with Basic Auth

### ISSUE THREAD

**Issue by Horuyuki** [NginxProxyManager/nginx-proxy-manager#1579]
Is it possible to limit the number of basic authentication?

To prevent brute forcing and the such.

**Comment by GilbN** [comment]
Yes, with fail2ban

**Comment by angrycuban13** [comment]
Yes, with fail2ban

**Comment by tronyx** [comment]
NPM is just a pretty UI for Nginx. This is not possible to do with just Nginx. The correct answer is Fail2Ban.

**Comment by Horuyuki** [comment]
I have not figured how to install fail to ban, closing.
