### ISSUE TITLE
How to install additonal NICs (and its routing rules due to "default gateway" AFTER installing proxy manager with docker?

### ISSUE THREAD

**Issue by jayjupdhig** [NginxProxyManager/nginx-proxy-manager#1736]
1.) When i add them  in /etc/network/interfaces BEFORE installing docker, it works

2.) When i add them  in /etc/network/interfaces AFTER installing docker , it does not work: https://github.com/jc21/nginx-proxy-manager/issues/1734

Now i have that proof for that fact - before set up a complete new proxy vm it was just a theory... 

SO: What to to when i want to add a 4rd or 5th NIC AFTER isntalling proxy manager...?

Because of proxy manager (i think because its "special" virtual NICs, bridge and so on) it makes issues: https://github.com/jc21/nginx-proxy-manager/issues/1734

**Comment by jayjupdhig** [comment]
Maybe it's better to use an own VM for each [new] IP address / network connection to bypasss / avoid problems like that!?

**Comment by jayjupdhig** [comment]
No anwser? The problem seems proxy manager-related to me (because of it's virtual adapters: bridge and so on!!), so NOT debian re-related. When i set up a fresh Debian [11] installation, or adding the additional adapters (eth1, eth2, ethX) BEFORE installing the proxy manager docker container, then IT WORKS!!

Otherwise, when i install them (eth1, eth2, ethX) AFTER INSTALLING proxy manager docker container, it does not work.

So: Why? Thank you very much for your feedback... 


With kind regards, Jan

**Comment by chaptergy** [comment]
As I have told you before, please stop spamming this issue tracker, this is not your personal tech support, and such behavior will not be tolerated here. No one owes you support, everyone is doing this in their spare time, and you are not paying for a product or a service. Furthermore most of your comments don't even sound friendly in tone, but rather angry and entitled. Commenting very frequently makes it seem even worse if you do not have anything useful to provide, like just cross-linking your issues.

You are obviously describing something you are experiencing with docker. This issue tracker is for Nginx Proxy Manager only. It does run in a docker container, however docker is a totally separate thing from npm. We do not provide support on how you can set up your docker environment for your super specific use-cases. You would have to research that yourself or find a community which is meant to help each other with docker issues. This is not the place.
