### ISSUE TITLE
NginxProxyManager Adds Port 80 to the URL

### ISSUE THREAD

**Issue by b3nd1k** [NginxProxyManager/nginx-proxy-manager#1740]
Hey. I've Portrainer, NginxProxyManager and LinkAce installed on a Ubuntu VPS server. The LinkAce container has the local IP 172.17.0.14:80. When I add the information to NPM and choose go to linkace.mydomain.com NPM automatically adds "80" to the URL, so that the URL looks like https://linkace.mydomain.com:80/login. This breaks the container. 

With other containers such as Monica who runs at 172.17.0.5:80, it does not add the "80" to the URL. The settings for the two reverse proxies in NPM looks identical, so I am not sure what is wrong here. Any ideas?

**Comment by serotonie** [comment]
Have a look at #1717
I personally just revert to 2.9.13 and it works again.

**Comment by chaptergy** [comment]
Closing as duplicate of https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1717
