### ISSUE TITLE
Enable/Disable by Timeframes

### ISSUE THREAD

**Issue by cybrdyne** [NginxProxyManager/nginx-proxy-manager#1745]
I have my entire docker shutdown during certain times which works ok, but it would be great if you could have sets of timeframes that could be assigned to subdomains to enable/disable. This would allow some to be on indefinitely and others to be scheduled.

**Comment by chaptergy** [comment]
Duplicate od https://github.com/NginxProxyManager/nginx-proxy-manager/issues/755
