### ISSUE TITLE
How to forward Mail server through NPM? Using Streams?

### ISSUE THREAD

**Issue by b3nd1k** [NginxProxyManager/nginx-proxy-manager#1746]
Hey! I've the ProtonMail Bridge Docker installed on my Unraid server that I want to expose to the internet. Currently IMAP is running locally from 10.0.0.20:1143 and SMTP from 10.0.0.20:1025. How do I do this in Nginx Proxy Manager? I am thinking maybe I Could use 'Streams'. What I essential want is to connect my email apps through mydomain.com:1025 rather than through public-ip:1025.

**Comment by chaptergy** [comment]
If you don't need NPM to handle SSL certificates, streams could work. Otherwise there is no build in way currently, you would have to mount a custom config file into your docker container. See https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1110.
