### ISSUE TITLE
Ports 80, 81 (Admin console) and 443 are only present on one (1) NICs of totally 3...

### ISSUE THREAD

**Issue by kosuodhmwa** [NginxProxyManager/nginx-proxy-manager#1776]
While Debian 11 installation, i used eth0 with a static IP configuration ("leased line"), after installation i set up other 2 NICs... with correct "post up ip route ... " commands in /etc/network/interfaces. (All IPs are pingable, but only one one (1) telnet [or web browser] gives me an anwser on ports 80, 81 and 443.

Does somebody known what this is?

Thank you very much for your feedbacks...

**Comment by kosuodhmwa** [comment]
???

**Comment by jayjupdhig** [comment]
Better use Windows 10 Pro x64 with IIS as a reverse proxy, much more simple and much more stable... :-)

**Comment by kosuodhmwa** [comment]
ok thx!! :-)
