### ISSUE TITLE
sub_filter

### ISSUE THREAD

**Issue by panaris** [NginxProxyManager/nginx-proxy-manager#1783]
**Is your feature request related to a problem? Please describe.**
I want to be able to replace footer copyrights.

**Describe the solution you'd like**
Just enable the ngx_http_sub_module http://nginx.org/en/docs/http/ngx_http_sub_module.html

**Describe alternatives you've considered**
Not always easy to modify the copyright otherwise especially when working with docker.

**Comment by BananaAcid** [comment]
The module seems to be enabled, and is useable if wrapped in Advanced-tab code field with `location /whatever { }` but does not seem to be working for the main route (not being wrapped in location but directly entered 
<img width="511" alt="sub_filter" src="https://user-images.githubusercontent.com/1894723/167083863-beb3d26d-e86d-45c5-8d78-ef6c4b3eba31.png">

Any ideas on this?
