### ISSUE TITLE
Unable to renew / create SSL certificates

### ISSUE THREAD

**Issue by elax46** [NginxProxyManager/nginx-proxy-manager#1792]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes  #1771

**Describe the bug**

impossible to renew the SSL certificates I also tried to delete the expired ones from the SSL section and recreate them but an error always occurs

![Immagine 2022-01-22 211339](https://user-images.githubusercontent.com/55278049/150654525-0a02197f-7e98-4f80-98f4-8c760f944a7a.png)
![Immagine 2022-01-22 212703](https://user-images.githubusercontent.com/55278049/150654526-d9fa0e63-e3e9-40de-9bbb-0a2ab9fa145a.png)

**Comment by mouazdk** [comment]
i have the same issue and tried the same like @elax46 done but nothing helped. Still not able to renew the SSL certificates
My NginxProxyManager working on Docker 
**PLEASE HELP!**

**Comment by JaydenE55** [comment]
Are you using Cloudflare or any other DNS provider that supports proxying?

**Comment by JaydenE55** [comment]
> i have the same issue and tried the same like @elax46 done but nothing helped. Still not able to renew the SSL certificates My NginxProxyManager working on Docker **PLEASE HELP!**

Are you using Cloudflare or any other DNS provider that supports proxying?

**Comment by elax46** [comment]
> > i have the same issue and tried the same like @elax46 done but nothing helped. Still not able to renew the SSL certificates My NginxProxyManager working on Docker **PLEASE HELP!**
> 
> Are you using Cloudflare or any other DNS provider that supports proxying?

No I am not using any proxying

**Comment by KILLERMANTV** [comment]
If you use cloudflare the workaround would be to generate a origin server certificate on cloudflare that's valid for 10 years and manually import it and change the ssl policy to full (strict) and it will work and also increase the security.

**Comment by hanneslpd** [comment]
I could solve the problem by resetting npm. I deleted the mounted directories /data and /letsencrypt. After that I logged into the GUI with the default credentials and was able to create new certificates for my domains - without the error message above.
Then quickly created the hosts again and assigned certificates - done :)

**Comment by elax46** [comment]
I close this problem as I did not notice that my modem has reset the port mapping by rearranging it I was able to renew the certificates
