### ISSUE TITLE
after reboot: cannot login anymore / reinstall doesn't let me create new SSL certificates

### ISSUE THREAD

**Issue by konstics** [NginxProxyManager/nginx-proxy-manager#1817]
Hi guys,
I'm pretty new in regard to self-hosting but nevertheless always learning and trying.

After rebooting my little RP4, I'm no longer able to login anymore. I always face the error "bad gateway" (with login via IP // no error shown while login in via domain); I had this one in the past as well; workaround with recreating the docker-container does not work.
Even resetting the password does not show any result.

Honestly, I tried to have a look into the logs but they do not show any error as far as I can see. (looked at the logs via Portainer).

Then, when I reinstall NPM and start completely fresh, I want to register a LE-certficate with a wildcard-subdomain, but this actually does not work. The last wildcard-certificate with this domain was registered on Jan 04th with the now broken instance (see above). Am I allowed to have only one LE-wildcard-certificate, even though it's done via the dns-challenge?

I tried almost everything the whole day, now I don't know what else to do. Any help is much appreciated :)
My system:
- docker-CE 20.10.12
- linux/arm (v7 on RP4)
- used official docker-compose.yml found in the documentation

**Comment by konstics** [comment]
Short update:
I reinstalled NPM since I was not able to manage my domains anymore (even though resolving worked fine).

Still facing the issue with re-generating the wildcard-cert, getting following error:

> Error: Command failed: pip install certbot-dns-cloudflare==$(certbot --version | grep -Eo '[0-9](\.[0-9]+)+') cloudflare
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-cloudflare/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-cloudflare/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-cloudflare/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-cloudflare/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-cloudflare/
ERROR: Could not find a version that satisfies the requirement certbot-dns-cloudflare==1.22.0 (from versions: none)
ERROR: No matching distribution found for certbot-dns-cloudflare==1.22.0
>    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

using the current build on 2.9.15 and the alpine-mariaDB by yobasystems.

**Comment by kylelliott** [comment]
i have same problem eveytime i reboot my NPM on docker all my setting get clear out
