### ISSUE TITLE
How can i get an alpine docker image to reduce the size

### ISSUE THREAD

**Issue by Yggdrasil80** [NginxProxyManager/nginx-proxy-manager#1915]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

An alpine alternative tag for the docker image, to reduce the image size, which is actually around 800Mb

**Describe alternatives you've considered**

Fork NPM and create my own alpine image

**Additional context**

**Comment by sciencebug** [comment]
see #1141
