### ISSUE TITLE
Ssh in docker.

### ISSUE THREAD

**Issue by bgman111111** [NginxProxyManager/nginx-proxy-manager#1943]
Hi i like to see how it is working. is there way connect to docker with admin rights and how is going... It will be good ideA. im newbiew and like computer science i want to learn. Man this project is super. PLease help make more features that nginx max. support. Include if you can incorporate main server, so peoples who have apache dont have to use it. Example: 

I have apache2 and i have firefly iii on /var/www/html/fireflyiii so for that to work i need have apache2. But i dont know how apache2 work. So insalling nginx proxy manager can do all work. Be like fully web server and dont use apache2 server. Now when it run. have explanation. Im sure that when every day peoples use it. They will have more ideas and with that help you. And donate. with sshin docker i mean. I want enter in docker like root in ubuntu. MUACKS

**Comment by jc21** [comment]
One should never, ever ever run a ssh server inside docker.

You can enter a shell inside a docker container easily. I highly recommend taking an introduction to docker course online, there are plenty of free ones out there.

This project does not support hosting files within itself, only proxying to other services, so you will be able to run your apache stuff separately (even in another docker container) and proxy to it with NPM.

However, support for that is outside of this project.

**Comment by bgman111111** [comment]
> One should never, ever ever run a ssh server inside docker.
> 
> You can enter a shell inside a docker container easily. I highly recommend taking an introduction to docker course online, there are plenty of free ones out there.
> 
> This project does not support hosting files within itself, only proxying to other services, so you will be able to run your apache stuff separately (even in another docker container) and proxy to it with NPM.
> 
> However, support for that is outside of this project.

i dont wajt ssh server inside docker. i want enter in docker with root access. like you use your computer i try with this command: 

 docker-compose run -u 0  bash name of containder and it didn't work.

**Comment by jc21** [comment]
```
docker exec -ti name_of_container bash
```
