### ISSUE TITLE
just updated to v2.9.18 ??

### ISSUE THREAD

**Issue by hs6666** [NginxProxyManager/nginx-proxy-manager#1968]
Hi

Just pulled latest docker image (using portainer)

npm is running on a debian vm

all working ok but on opening webpage the version showing at bottom left hand side is v2.9.18

any ideas why please?

PS pulling .... 'jc21/nginx-proxy-manager:latest'

Thanks

Harry

**Comment by l4rm4nd** [comment]
Introduced by the latest release: https://github.com/NginxProxyManager/nginx-proxy-manager/commit/4db34f5894a2eb86e99683d52e9b7a859dd206a8
