### ISSUE TITLE
400 error for admin panel over SSH tunnel

### ISSUE THREAD

**Issue by itsKV** [NginxProxyManager/nginx-proxy-manager#2020]
I have not forwarded port 81 on VPS for internal security reasons.
I have logged in via SSH with tunnel setting as L81-->127.0.0.1:81 
But the browser is giving _Bad Request - Invalid Hostname_ error when I open http://127.0.0.1:81 in browser. 
How to access Admin web panel using ssh tunnel?

**Comment by itsKV** [comment]
It seems I have to enable SYN packets on port 81 from iptables to access it from browser.
It worked after that.

**Comment by stk21** [comment]
@itsKV What is your connection string to the VPS?

I just did this on mine it worked find.

I would recommend port forwarding a higher port than 81.  your host operating system might have an issue with :81


ssh -L8181:<ip address of where NPM is running>:81 user@<ip address of machine you are connecting to>

this assumes that :81 is the management port that docker is listening to for management of the NPM container.

**Comment by itsKV** [comment]
Sorry, my bad.  
The port I was trying to use on local machine was hogged by local application which was giving 400 error. Changed the port no 'free' one. That solved the issue.
