### ISSUE TITLE
Proxy Buffer Size edit/update

### ISSUE THREAD

**Issue by kaushikray1** [NginxProxyManager/nginx-proxy-manager#2022]
Hello, 

First of all thank you for all your hardwork and support. 

I use Mailcow email server behind NPM for about last 2 years with no issue. After the last update of Mailcow this April they require bigger cash size for the proxy host. 

https://github.com/mailcow/mailcow-dockerized/issues/4537#issuecomment-1090126628

https://mailcow.github.io/mailcow-dockerized-docs/post_installation/firststeps-rp/#nginx

please help me how can I change this either in GUI or by updating config files.

Thank you.

**Comment by SuperGaleb** [comment]
I also have same problem.
"I use Mailcow email server behind NPM for about last 2 years with no issue. After the last update of Mailcow this April they require bigger cash size for the proxy host."

**Comment by kaushikray1** [comment]
Thank you, this is perfect.
