### ISSUE TITLE
SSL don't works

### ISSUE THREAD

**Issue by Timtaran** [NginxProxyManager/nginx-proxy-manager#2039]

**Comment by progamer562** [comment]
Well how can we help you if you don't give out some info to debug this issue

**Comment by Timtaran** [comment]
Ok, so 
![изображение](https://user-images.githubusercontent.com/60805088/167054831-73f3119b-0105-4e64-934d-4d976996f19d.png)
when I try to go to `https://map.minescale.ru/` it redirects me to `http://map.minescale.ru/`
if I use Force SSL site don't works

**Comment by the1ts** [comment]
When I curl https://minescale.ru I get a 301 redirect from cloudflare redirecting me to http://minescale.ru so I suspect your cloudflare config is doing this force to http.

**Comment by Timtaran** [comment]
thanks
