### ISSUE TITLE
DomainOffensive (do.de) - please add existing certbot plugin to NPM

### ISSUE THREAD

**Issue by DFS-90** [NginxProxyManager/nginx-proxy-manager#2055]
**What provider would you like to see added to NPM?**
DomainOffensive (do.de)

**Have you checked if a certbot plugin exists?**
https://pypi.org/project/certbot-dns-do/0.31.0/

Thanks in advance,
David

-------------------------------------------------
-------------------------------------------------
**old version (before edit):**

**What provider would you like to see added to NPM?**
DomainOffensive (do.de)

**Have you checked if a certbot plugin exists?**
Not sure if that helps, but DomainOffensive offers a LetsEncrypt API:

**first method: acme.sh:**
export DO_LETOKEN="02pAPacMv1yNnUzSDR75"
acme.sh --issue --dns dns_doapi -d meineDomain.de -d *.meineDomain.de

**second method: GET-Request:**

example

https://my.do.de/api/letsencrypt?token=1md6xRcUCTrB58kbpwAH&domain=_acme-challenge.testdomain.de&value=OVxwaDm7MgN1IRG0eSivJMlepO9CL4X8vKo6Tcns

parameters:

token=  - auth token
domain= - full domain name, including _acme-challenge as well as subdomains
value=  - value for TXT record

answer:

{
    "kdn": "1234",
    "domain": "testdomain.de",
    "success": true
}

**Please also see:**
https://blog.ichalsroot.de/letsencrypt-wildcard-ssl-zertifikate-mit-domain-offensive/

Thanks in advance,
David

**Comment by Cyneric** [comment]
+

**Comment by Cyneric** [comment]
+

**Comment by DFS-90** [comment]
I think I probably found a certbot plugin for DomainOffensive (do) - please see here:
[https://github.com/georgeto/certbot-dns-do](url)

Is it possible to integrate this one into NPM?

Thanks,
David

**Comment by DFS-90** [comment]
The GitHub package from
https://github.com/georgeto/certbot-dns-do](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/url

can also be found on PyPI:
https://pypi.org/project/certbot-dns-do/0.31.0/

I edited the original post.
Maybe @jc21 can include the certbot plugin for Domain-Offensive now? :-)

**All credits go to the original author georgeto!**


Thanks in advance,
David

**Comment by deluxestyle** [comment]
oh yes please. this would be great

**Comment by Cyneric** [comment]
+

**Comment by Cyneric** [comment]
push

**Comment by Cyneric** [comment]
would apreciate this to be added

**Comment by Cyneric** [comment]
would appreciate this to be added

**Comment by trasrikgaldifei** [comment]
Would also appreciate this registrar to be added. Thanks in advance.

**Comment by DFS-90** [comment]
I was able to successfully create a build that includes the DomainOffensive plugin from georgeto.
**(Thanks to Knoxell for showing me how to do this!)**

I created a pull request (#2327 ) and hope that @jc21 will include the changes into the development branch.

I also created a **testing version** on Docker Hub.
You can modify your docker-compose.yml like this in order to check it out:

```
version: "3"
services:
  app:
    image: 'dfs90/nginx-proxy-manager-do-de'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```

**Please be aware that this version is based on v2.9.18 and will not be updated!**

**Comment by DFS-90** [comment]
Pull request has been approved - see [here](https://github.com/NginxProxyManager/nginx-proxy-manager/pull/2327).
