### ISSUE TITLE
Sub-domain redirection for Streams

### ISSUE THREAD

**Issue by official-Cromatin** [NginxProxyManager/nginx-proxy-manager#2064]
**Is your feature request related to a problem? Please describe:**

Yes, I would like to be able to reach different game servers within my network from different sub-domains

**Describe the solution you'd like:**

If I specify a proxy host, I have the option to specify an input subdomain and an internal IP address as the destination, so far so good.

The other day I found out while browsing in the Web Interface that I can also specify a UDP port in the streams in addition to the TCP port, unfortunately I cannot specify an input subdomain as with the streams in order to be able to specify which traffic is forwarded from which address to which internal address.

As an example, it is not possible for me to access the server with the internal IP 192.168.178.2 (port 25665) via the domain vanilla.domain.de, and the internal IP 192.168.178.4 (port 25565) via the address dev.domain.de

**Describe alternatives you've considered:**

So far I haven't found any alternatives yet

**Additional context:**

![grafik](https://user-images.githubusercontent.com/92319467/169813264-f0bd6dfc-b7db-44f1-b864-dcd213f878ec.png)
This is what it could look like, if it can be implemented

**Comment by the1ts** [comment]
Aren't streams just a TCP or UDP connection that nginx proxies onwards? so are just IP to IP, there is no way to distinguish between multiple subdomains that all use the same IP, the actual traffic which doesn't have to be http may not even contain the subdomain it was destined for only source and destination IPs. Or am I misunderstanding a tech I've not used.
I think the only way you can do this is have one use vanilla.domain.de:25565 -> 192.168.178.2:25565 and the other to use dev.domain.de:25566 -> 192.168.178.4:25565 (note the different port). Since these are just minecraft servers, the client does take a different port in the connection string.

**Comment by official-Cromatin** [comment]
I had thought that this information could be taken up when establishing a connection to make the forwarding. 
After the days I had dealt with it again intensively, I think the only solution to this problem (without the users having to change the port) is an SRV record in the domain. 
I don't know if that's possible because this information is not transmitted. 

I wanted to avoid having to change the ports as much as possible because it leads to complications at some points

However, if there is no other option, and only http transmits this information when establishing the connection, I probably have to go the way with the ports.
However, now that I am writing this message I remember that the load balancer of Kemp supports this feature at least as far as I have noticed.

**Comment by the1ts** [comment]
I think for minecraft the easiest solution for this is the addition of an SRV record with the non-standard port and its subdomain then a non-standard port will not be seen by the player, only the admin and the minecraft client (after the DNS lookup) will know its a non-standard port.
I've worked with load balancing/proxying that makes decisions on things other than the HTTP Host header, Apache and mod_security for example, but those are very complex tools which don't really live in a tool to simplify SSL certs and HTTP Proxying, there is always a battle to keep simple tools simple.
