### ISSUE TITLE
The DNS response does not contain an answer to the question (DuckDNS)

### ISSUE THREAD

**Issue by jake404** [NginxProxyManager/nginx-proxy-manager#2092]
I have been using Nginx Proxy Manager with DuckDNS DNS challenge for a few months and suddenly it can't renew the certs. Nginx Proxy Manager says 'Internal error' and the log says 'The DNS response does not contain an answer to the question: mydomain.duckdns.org. IN TXT'. Nothing has changed in my LAN. Has something changed with the DuckDNS implementation in Nginx Proxy Manager?

**Comment by Rihan9** [comment]
Hi @jake404,
I have the same error. how did you solve it?

**Comment by totalizator** [comment]
Same here. Suddenly I can't renew or request new certificate: "The DNS response does not contain an answer to the question: mydomain.duckdns.org. IN TXT".

Any ideas?

**Comment by Rihan9** [comment]
We are all stuck with this bug. I'm going to open a new issue.

**Comment by devedse** [comment]
I've added explanations/workarounds to the post from Rihan9, please check that out here:
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3138
