### ISSUE TITLE
How to forward a location to another location?

### ISSUE THREAD

**Issue by Horuyuki** [NginxProxyManager/nginx-proxy-manager#2093]
iOS uses a different link for webDAV then what the Nextcloud system uses, therefore requiring this bit of code if one is to configure nginx manually:
```
    location ^~ /.well-known {
        # The rules in this block are an adaptation of the rules
        # in `.htaccess` that concern `/.well-known`.

        location = /.well-known/carddav { return 301 /remote.php/dav/; }
        location = /.well-known/caldav  { return 301 /remote.php/dav/; }

        location /.well-known/acme-challenge    { try_files $uri $uri/ =404; }
        location /.well-known/pki-validation    { try_files $uri $uri/ =404; }
```

Therefore I want to know hot should I set these rules manually in the npm UI. Thank you!

**Comment by Horuyuki** [comment]
[![example.png](https://i.postimg.cc/d02XrDfX/example.png)](https://postimg.cc/CZKmVMSH)

This is what you need to put down, just redirect to the same Forward destination as the details page.

**Comment by billvanleeuwen424** [comment]
Just wanted to say thanks for posting this here! Saved me a big headache on my personal server.
got here from the nextcloud forms where a helpful user posted his journey.
https://help.nextcloud.com/t/cannot-connect-ios-carddav-caldav-to-nextcloud/140046/3

**Comment by Chyllie** [comment]
Hey I made a mistake an used the line "return 301 $scheme://$host/remote.php/dav;" in Advanced tab in Nginx docker. Now the site forwards directly to the remote.php/dav. Can I set this back to the original config, what do I need to write in Advanced tab? Deleting and making a new Forwarding does not help.
