### ISSUE TITLE
Brightcloud IP Reputation Violations

### ISSUE THREAD

**Issue by mrjlturner** [NginxProxyManager/nginx-proxy-manager#2128]
### Discussed in https://github.com/NginxProxyManager/nginx-proxy-manager/discussions/2127

<div type='discussions-op-text'>

<sup>Originally posted by **mrjlturner** June 22, 2022</sup>
Gang,

Can anyone else confirm the hidden interface for npm on /aaa9? My installation had this, and was constantly being found by Brightcloud as a risk. Here's the verbiage:
"Our scanners detected proxy activities from this IP address. These threats have been detected by our own sensors. Because of this, we are not able to provide the destination IP addresses or additional details about the detection. However, I can provide a sample of some URLs hosted the IP address which may have contributed to the listing: <DNS Hostname Removed>/aaa9"

This was happening every few weeks. So, I ran a test today, and sure enough when I put that directory in, I was redirected to the administrative console interface. No bueno! So, I've added a "dead link" location for that URI and now it's closed. How disturbing though!

If anyone else can confirm, I'd appreciate it! I've confirmed this on two of my installs.

Thanks,
mrjlturner</div>

**Comment by jc21** [comment]
Please refer to the discussion and avoid duplicating issues.
