### ISSUE TITLE
stream port

### ISSUE THREAD

**Issue by dragacss** [NginxProxyManager/nginx-proxy-manager#2159]
Good afternoon!
Is it possible to forward one port to different subdomains?
For example RDP port: 
server1.mysite.com:3389    =>  192.168.0.15:3389
server2.mysite.com:3389    =>  192.168.0.16:3389

Only one active rule is created in the stream tab

**Comment by the1ts** [comment]
Don't believe so, streams on nginx are simple forwards, they don't look inside packets to see what hostname was being used only the IP and port that nginx is being hit on. Simply put, you are actually setting up something like 5.5.5.5:3389 => 192.168.0.15:3389 so having server1.mysite.com and server2.mysite.com both pointing at 5.5.5.5 doesn't help us get 2 different streams.
Use multiple unique ports on the npm side.
