### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by axldroid** [NginxProxyManager/nginx-proxy-manager#2163]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
I cant start it with docker

**Operating System**
Ubuntu 20.04

**Error**
root@ns5009505:/# docker-compose up -d
Creating default_app_1 ... 
Creating default_app_1 ... error

ERROR: for default_app_1  Cannot start service app: driver failed programming external connectivity on endpoint default_app_1 (9e61ae547efaa671fce34be29bdbdac2a056f3fe26a10c4f579c0b195ea27cc5): Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use

ERROR: for app  Cannot start service app: driver failed programming external connectivity on endpoint default_app_1 (9e61ae547efaa671fce34be29bdbdac2a056f3fe26a10c4f579c0b195ea27cc5): Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by the1ts** [comment]
it appears you already have something listening on port 443, have nginx or apache already running?

**Comment by axldroid** [comment]
> it appears you already have something listening on port 443, have nginx or apache already running?

Yes, I have NGINX running already on my machine.

**Comment by the1ts** [comment]
one will have to use another port or another IP on the same machine. Only one process can bind to an IP:port at time.

**Comment by axldroid** [comment]
> one will have to use another port or another IP on the same machine. Only one process can bind to an IP:port at time.

If I change the ports that NGINX Proxy Manager uses (443 and 80) will it still work?

**Comment by the1ts** [comment]
That is a big question, most people in this situation will change the ports to something that doesn't clash, but forward 80 -> new port 80 and 443 -> new port 443 from their router. That works fine for NPM hosted sites such as https://www.domain.com and https://app.domain.com since they are hit on port 80 and 443 on the router outside
