### ISSUE TITLE
Unraid App image

### ISSUE THREAD

**Issue by myxxmikeyxx** [NginxProxyManager/nginx-proxy-manager#2165]
Do you have an official unraid image?
I found one - mgutt's Repository: from jc21: Maintainer mgutt
I found one - Djoss's Repository: from jlesage: Maintainer Djoss
Are either of these "offical" unraid app?

I currently have a docker compose version installed but I would like to use a native unraid app.
The unraid app allows for more options unlike the docker compose that I did from terminal.

**Comment by MrSmits** [comment]
I saw your post as I was browsing earlier today. JC21 is the only member of the Github org that is hosting this repository, so the JC21 would be the official docket image. 
Mgutt is the one that made the template available for use on Unraid, but the docker image being pulled with that template is the one published by JC21. It's been running just fine for the last 2 months on my machine.

![image](https://user-images.githubusercontent.com/29866289/187525533-ad71d943-8e12-4a74-b4b4-fd3898f66307.png)

**Comment by myxxmikeyxx** [comment]
Okay. I saw that the repo was jc21 but I didn't know how unraid works for apps and if the "owner" can put any repo but maybe customize the scripts or something.
