### ISSUE TITLE
Unable to redirect for localhost port

### ISSUE THREAD

**Issue by DiogoMarques2003** [NginxProxyManager/nginx-proxy-manager#2175]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
I tried to redirect a part of localhost to the domain and memso didn't work

**Nginx Proxy Manager Version**
jc21/nginx-proxy-manager:latest@sha256:7c775dbb91f2e5feebddd764dbfd76fd013235a1fd9b1215f44082cddc26ccad

**Screenshots**
![image](https://user-images.githubusercontent.com/52538977/181484299-a76e0a74-eb1b-44a9-bc38-b1808dcb9207.png)
![image](https://user-images.githubusercontent.com/52538977/181484328-2458ad2b-f16a-4388-ba15-34e4519af721.png)

**Operating System**
ubuntu server 20

**Comment by the1ts** [comment]
I'm seeing this hostname is working, I take it this is fixed and can be closed?

**Comment by DiogoMarques2003** [comment]
@the1ts no, isn't working, i'm using directly the IP do host and bot de localhost

**Comment by the1ts** [comment]
@DiogoMarques2003 don't you have to use docker with containers on network=host for containers and host to share localhost between containers and host?

**Comment by DiogoMarques2003** [comment]
> @DiogoMarques2003 don't you have to use docker with containers on network=host for containers and host to share localhost between containers and host?

I don't know, but i can trie affter

**Comment by DiogoMarques2003** [comment]
@the1ts this work thanks
