### ISSUE TITLE
Plesk API (Plesk Remote XML API)

### ISSUE THREAD

**Issue by rezzorix** [NginxProxyManager/nginx-proxy-manager#2200]
**What provider would you like to see added to NPM?**
Plesk API (Plesk Remote XML Api)
see here: https://docs.plesk.com/en-US/obsidian/api-rpc/about-xml-api/reference/managing-dns.34756/

**Have you checked if a certbot plugin exists?**
Yes checked, doesnt exist.

**Comment by gomble** [comment]
This would be great

**Comment by motom001** [comment]
Maybe this could help:
https://pypi.org/project/certbot-dns-plesk/
