### ISSUE TITLE
[enhancement|feature request] Add redirect option for access lists.

### ISSUE THREAD

**Issue by TheRealVira** [NginxProxyManager/nginx-proxy-manager#2261]
Currently, whenever someone wants to access a host and doesn't meet its' dedicated access list requirements they receive a 403 forbidden error message. This may be fine for many, but I'd like to redirect the user to my default page instead. I'd imagine it to be similar to the "Default Site" setting.

**Comment by the1ts** [comment]
@TheRealVira I would say use the optional custom http_top.conf as described [here](https://nginxproxymanager.com/advanced-config/#custom-nginx-configurations)
perhaps the below will work:
`error_page  403   http://google.com;`

**Comment by TheRealVira** [comment]
Yup this works for me. Thanks for the quick reply @the1ts ! I guess if you really want different redirects depending on which access list you use you'd need to use a different configs. But I am okay with just my one default page.
