### ISSUE TITLE
Custom Certificate Import not working Cant enter local path?

### ISSUE THREAD

**Issue by 1liminal1** [NginxProxyManager/nginx-proxy-manager#2321]
- Have you searched for similar issues (both open and closed)?
  - Yes, seems to be a workaround

**Describe the bug**
When trying to specify the path local NPM docker instance path to certificates I just get a dialog box keep popping up with access to the local computer.

**Nginx Proxy Manager Version**
v2.9.18

**To Reproduce**
1. Add SSL certs
2. Custom
3. Try to enter Certificate & Key location 

**Expected behavior**
Am able to enter the local NPM docker instance path to my the certificates already on the NPM server 

**Screenshots**
![image](https://user-images.githubusercontent.com/10505942/195556560-26e4e99c-a72b-4940-b6ae-0fc66e9dc90b.png)

**Operating System**
Debian 

**Additional context**
People have certs that they want to use and not being able to automate that is a PIA

**Comment by the1ts** [comment]
@1liminal1 When you say local path, do you mean local to the npm server or local to the browser? I'm not sure because you use local twice in the report.
If you mean local to the npm server, then the correct method would be to use docker volumes to put the cert into the correct location within the npm docker container.

**Comment by 1liminal1** [comment]
Hi there, 

Thanks for that. Yes, local server path. I have the certs already on the docker instance ready to go. But I cant specify a path. 

If there is a path where the certs will be automatically loaded, can you advise what that is. Is there doco for it?

**Comment by the1ts** [comment]
custom ssl certs are held in the data volume under custom_ssl/npm-number, I suggest you create a cert with the correct names in the UI. Then the npm-number directory will be made, then link in your cert and key.

**Comment by 1liminal1** [comment]
Ok... So what your saying is; 

Add the cert though the UI the first time and make a note of what the directory name was created under the "custom_ssl" directory. For me using Portainer its; 

/portainer/Files/AppData/Config/Nginx-Proxy/data/custom_ssl/npm-1/

Then set up an export, or whatever sync method you want, to export the certs to that folder after renewal and NPM with pick up the new certs automatically. 

Is that right?

**Comment by the1ts** [comment]
yes, as long as your certs end up in the custome_ssl and are readable by nginx it will work. You will have to restart NPM when they change, but that is true of apache/nginx or any SSL protected service.

**Comment by the1ts** [comment]
Hoping we can close this off since docker images cannot get access to host files not presented as volumes so it doesn't make sense as a development request. So the only sensible thing is to present the cert and key as docker volumes as suggested.

**Comment by 1liminal1** [comment]
Yes thanks, I wanted to convert this to a feature request, but seems its easier to just open one. 

Thanks for your help, I do appreciate it :)
