### ISSUE TITLE
Support ws and wss scheme

### ISSUE THREAD

**Issue by ilsnk** [NginxProxyManager/nginx-proxy-manager#2326]
what about ws and wss support?
![image](https://user-images.githubusercontent.com/44324620/195962380-5d19e089-5764-4460-8c66-e756198d73ad.png)

**Comment by the1ts** [comment]
isn't ws:// and wss:// simply presented over http and https? NPM already has the websockets tick box. Javascript web apps that use wss:// style schema work fine through it for me.

**Comment by ilsnk** [comment]
yes, work fine, sorry :)

**Comment by damms005** [comment]
@the1ts @ilsnk  Please how do you specify the port for the web socket connection?

I setup [Laravel Websockets](https://beyondco.de/docs/laravel-websockets/basic-usage/pusher#pusher-configuration) and I need to specify the `host` and `port`. NginxProxyManager, like in the screenshot above, only provides option to set port for http/s
