### ISSUE TITLE
Reset password now hosts list empty (but working)

### ISSUE THREAD

**Issue by jimmyeao** [NginxProxyManager/nginx-proxy-manager#2340]
So I forgot my password, and reset it through the DB ( UPDATE user SET is_deleted=1; , restart, log in with [admin@example.com](mailto:admin@example.com) and set new password, then ran UPDATE user SET is_deleted=0; restarted)
I can now no longer see any of the config, although it is all working, and the entries exist in the DB.

What did I mess up?

**Comment by PDXUser** [comment]
I had the exact same problem! 

I am using the jc21/nginx-proxy-manager:latest container and I did not have the sqlite3 command available inside the container, so I used "DB Browser for SQL Lite" from Flatpak to run the commands. In the "user" table, I deleted the second user, and under the "auth" table, I changed the "secret" for the 1st user (record 1) to:

$2b$13$C9mJYK7Gf7sVgCCYw84HhOvOIpnyhkdGqwIp0PPj/s9.q0bxkoMZe             - this is the _changeme_ password.

Wrote my changes then uploaded them back to the server and restarted the container, I was able to login with the _changeme_ password and update my password.  After this, i had my hosts and everything like it was before.
