### ISSUE TITLE
Setting proxy_set_header Host <VALUE>;

### ISSUE THREAD

**Issue by prashantsomashekar** [NginxProxyManager/nginx-proxy-manager#2351]
Hi.

I need to set proxy_set_header Host _value_; as the application I am proxying to will not allow $host.  I cannot seem to override this in a custom location block (which is ultimately being taken from proxy.conf / template).  I cannot seeem to override this in server (because of the aforementioned include).

Can someone please advise on how I may do this, without hacking this thing and overriding files and removing things?

Thank you.

**Comment by prashantsomashekar** [comment]
Closing this as there is a similar issue: https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2076

**Comment by bilogic** [comment]
Solution here https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2076#issuecomment-2068581644
