### ISSUE TITLE
FW Default DROP + ACCEPT 80,443 not enough for NPM while global IP+port works?

### ISSUE THREAD

**Issue by j2l** [NginxProxyManager/nginx-proxy-manager#2399]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
FW default action drops all packets except 80 and 443
(but NAT rules supersede filters and I can still access my container using <globalIP>:<port> which is weird)
NPM is configured to route to HTTP <globalIP> and <port>, SSL is valid for 5 years and working fine.
but domain name doesn't resolve and I get Error 504.
It looks like something need to access another port for NPM to resolve or forward to the container, which is still accessible using <globalIP>:<port>.

Of course, if FW default action is Accept, everything works fine, NPM runs and domain name get resolved.

**Nginx Proxy Manager Version**
2.9.16

**To Reproduce**
1. FW ACCEPT 80,443, default action = DROP
2. check access to your globalIP:port
3. try to access your domain name

**Expected behavior**
NPM to resolve/forward

**Operating System**
Ubuntu 20.04

**Comment by the1ts** [comment]
The 504 seems to suggest NPM cannot get to the backend you setup. I would `docker exec -it "npm container name" /bin/bash`. Check DNS is functional if you are using hostnames not IPs. Check that NPM container and nginx are using the same DNS servers. 
Using curl from the command line curl -v "http://backend:port" will show if its access that failing.

**Comment by j2l** [comment]
Thank you @the1ts !
Very good idea.
