### ISSUE TITLE
Federation setup for Matrix

### ISSUE THREAD

**Issue by gouthamravee** [NginxProxyManager/nginx-proxy-manager#2406]
### Discussed in https://github.com/NginxProxyManager/nginx-proxy-manager/discussions/2404

<div type='discussions-op-text'>

<sup>Originally posted by **gouthamravee** November 15, 2022</sup>
I'm trying to get federation working for my matrix server. I'm using the ansible install method. 
Matrix and nginx-proxy are on different vms with their own unique address on the LAN. 

I have the ansible nginx-proxy on but using different ports, and NPM is managing proxying from `matrix.my.domain` and `my.domain`. 
NPM is also managing certs for both domains. 
https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-own-webserver.md#method-2-fronting-the-integrated-nginx-reverse-proxy-webserver-with-another-reverse-proxy

I can access matrix from matrix.my.domain. 
I have port `8448` forwarded to NPM and I have the dockerfile setup to pass port `8448` to `8048` on the matrix server. 

The problem is I need `my.domain:8448` to show the SSL cert for my.domain

In NPM I have hosts with SSL created for 
```
matrix.my.domain -> matrix.my.lan:8008 
my.domain -> matrix.my.lan:8084
```

I also have a stream host as 
`8448 -> matrix.my.lan:8084`

But I'm getting a connection refused when doing the matrix federation test. </div>

**Comment by mxwmnn** [comment]
I have a very similiar problem. 

I think the best thing is to add an option to define another port listeners for the configuration file in the npm cause npm needs to listen on 8448 and forward it to the federation port with SSL.

I tried it with manual config, but no luck yet

**Comment by mjmccans** [comment]
My setup is not quite the same as yours in that I do not have a separate VM running my Synapse instance, but I think I have dealt with a similar issue so the below may be helpful. I have port 8448 forwarded to my NPM container, and then I have the following as a Custom Nginx Configuration on the Advanced tab of the base url entry in NPM. Note that "synapse:8008" is a reference to my Synapse docker container, so you would have to adjust the below accordingly to point to your Synapse instance.

```
listen 8448 ssl http2 default_server;

location ~* ^(\/_matrix|\/_synapse|\/_synapse\/client) {
        # note: do not add a path (even a single /) after the port in `proxy_pass`,
        # otherwise nginx will canonicalise the URI and cause signature verification
        # errors.
        proxy_pass http://synapse:8008;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;

        # Nginx by default only allows file uploads up to 1M in size
        # Increase client_max_body_size to match max_upload_size
        # defined in homeserver.yaml
        client_max_body_size 50M;
    }
```

**Comment by gouthamravee** [comment]
Thanks for the responses everyone! I managed to get some help from the matrix-ansible support chat. I wrote the post below to document the config that worked. 

https://www.gravee.dev/en/matrix-ansible-with-nginx-proxy-manager/

Marking this as solved!
