### ISSUE TITLE
Missing Entrys of proxy hosts and SSL Certificates

### ISSUE THREAD

**Issue by Pudding26** [NginxProxyManager/nginx-proxy-manager#2432]
Checklist

    Have you pulled and found the error with jc21/nginx-proxy-manager:latest docker image?
        Yes
    Are you sure you're not using someone else's docker image?
        Yes
    Have you searched for similar issues (both open and closed)?
        Yes

Describe the Bug

i have just set up an nginx docker instance on ubuntu. Due to a miss sync with my password manager I lost my pw, after creating a proxyhost for portainer and nginx (both with a Subdomain). In order to fix the issue i first tried to just delete the stack and deploy it again, that didnt work as I kept my mariadb with my still lost pw. At least i guess that is what happend. I then entered the db and ran `UPDATE user SET is_deleted=1;` as discribed in Issue#230. Following these steps i was then able to reset the password.

My problem is now, that the 2 reverse proxys i set up before are not listed, Furthermore is my portainer as well as my nginx acces still possible via the subdomains and encrypted. If i want to set a new proxy host I can see both SSL certificates in the SSL tab, but I am not able to reasing them, not even to the "old" subdomains. If i open the log I can still see, that I have set up said proxy hosts.

By my understanding I have corrupted the db in a way, that the settings are still in place but I am just not able to access them via the GUI. Is that correct and if so is there a way to fix this. Re deploying the whole Server is still an Option as it has no Data yet. I am just not sure if that will even solve the issue.

**Comment by the1ts** [comment]
Data for NPM is in 2 places, you perhaps need to clear both.

1. the docker data volume which holds the certs and nginx config built by the app
2. the database, either sqlite held in the above or MySQL/MariaDB, this Db also needs clearing or it may think it has certs that don't exist in the volume in point 1

**Comment by Pudding26** [comment]
the docker data volume which holds the certs and nginx config built by the app

can i just access the data in order to delete these files (stoping both containers beforehand)

**Comment by the1ts** [comment]
Not sure as you are using portainer, but the data volume needs removing. In short delete containers, DBs, data volumes and start from scratch. If that is too confusing to do, start with newly named containers and volumes.

**Comment by Pudding26** [comment]
Thank you. All solved now.
