### ISSUE TITLE
[Urgent] Certbot command fails when creating new SSL certificate using DNS challenge

### ISSUE THREAD

**Issue by MelvynEzi** [NginxProxyManager/nginx-proxy-manager#2448]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

When creating an SSL certificate using DNS challenge, this error appears:
```
Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --cert-name "npm-1" --agree-tos --email "EMAIL REDACTED" --domains "DOMAINS REDACTED" --authenticator dns-porkbun --dns-porkbun-credentials "/etc/letsencrypt/credentials/credentials-1"
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 5, in 
    from certbot.main import main
  File "/usr/local/lib/python3.7/dist-packages/certbot/main.py", line 6, in 
    from certbot._internal import main as internal_main
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 28, in 
    from certbot import crypto_util
  File "/usr/local/lib/python3.7/dist-packages/certbot/crypto_util.py", line 42, in 
    from certbot import interfaces
  File "/usr/local/lib/python3.7/dist-packages/certbot/interfaces.py", line 21, in 
    from acme.client import ClientBase
ImportError: cannot import name 'ClientBase' from 'acme.client' (/usr/local/lib/python3.7/dist-packages/acme/client.py)

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket. (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe. (node:net:301:12)
```

**Nginx Proxy Manager Version**

2.9.19

**To Reproduce**
1. Go to 'SSL Certificates'
2. Click on 'Add SSL Certificates'
3. Check 'Use a DNS Challenge'
4. Click on 'Save'
5. See error

**Expected behavior**

SSL certificate created and shown under 'SSL Certificates'

**Screenshots**

N/A

**Operating System**

RaspberryPi OS Lite Bullseye

**Additional context**

- https://github.com/certbot/certbot/pull/9356/commits/21dbe0cc7d06ed5c8b01153820f7f3cb28631cb2
This commit have removed some deprecated code from Certbot, and the removal of 'ClientBase' causes NPM to break.

**Comment by eosti** [comment]
A workaround can be found [here](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2430#issuecomment-1331687301) in #2448

**Comment by DJCrapsody** [comment]
> A workaround can be found [here](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2430#issuecomment-1331687301) in #2430

Can confirm workaround works. Hoping for a fix on NPM end.
