### ISSUE TITLE
SSL settings disappear after creation of host

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [NginxProxyManager/nginx-proxy-manager#2476]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
  - Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

When ever I create a host and generate an SSL certificate and select SSL settings, once it is created it has none of the SSL settings I have checked (e.g: Force SSL) and then I have to select them again for it to work.

**Nginx Proxy Manager Version**

v2.9.19

**To Reproduce**

Go to either proxy, redirect, or 404 hosts. Click the create button. Go to the SSL tab and select generate an certificate and select any SSL options and then click save. Then click the edit button and check the SSL tab and you will see that the options you selected are not selected.

**Expected behavior**

The SSL options to save

**Screenshots**

N/A

**Operating System**

Server is running Ubuntu 20.04. My computer is running Windows 11 Pro v22H2

**Additional context**

N/A

**Comment by Nedevski** [comment]
+1
I came here to open an issue for this exact bug. Not a big deal but still annoying.

**Comment by WilliamDavidHarrison** [comment]
This issue doesn't seem to be happening for me anymore.
