### ISSUE TITLE
Crowdsec Support

### ISSUE THREAD

**Issue by marcocajon** [NginxProxyManager/nginx-proxy-manager#2480]
Hi Folks,

Is Crowdsec being officially supported by the latest image? Asking because I see it mentioned in v2.9.17 released this Mar 30 but there are no other mentions besides the ones at the fork by lepresidente @ https://github.com/LePresidente/docker-nginx-proxy-manager. 

Thanks!

**Comment by cloudybyte** [comment]
I don't see why you wouldn't be able to proxy crowdsec.
There isn't really such a thing as "official software support", as npm is really just a fancy configuration interface for nginx.

**Comment by garsiv1932** [comment]
@cloudybyte you need to make some changes on the nginx configuration and install a bouncer that is not easy. There is another developer that is making the configuration, his nick is lepresidente, but he is making a fork from another fork, not the official image, and some things are changed, like the mount point for the data folder, and some features are not working, like generating certificates from cloudflare.

It could be nice to have the crowdsec bouncer included on the official image.
