### ISSUE TITLE
Timezone incorrect; how to change?

### ISSUE THREAD

**Issue by Panja0** [NginxProxyManager/nginx-proxy-manager#2481]
I've setup NPM and the creation time (for SSL certs, hosts etc) is not the correct time.
How can I change this?

**Comment by alexkararo** [comment]
Hi! I am facing a similar issue, tried to mount /etc/timezone and locale into volumes, but I still have wrong date inside the container or logs. 

Did you find a solution?

Thank you!

**Comment by lastsamurai26** [comment]
i tried this
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
      
      but didn't changed =(
