### ISSUE TITLE
Yellow text for warnings (instead of red)

### ISSUE THREAD

**Issue by ugosan** [NginxProxyManager/nginx-proxy-manager#2520]
Just a minor feature, the red color should be really for errors, not warnings:
<img src="https://user-images.githubusercontent.com/17125/210577519-7c386cbf-a029-4c35-97fb-5206e2e40a78.jpg" width="400" />

I think it would look better this way:
<img src="https://user-images.githubusercontent.com/17125/210577551-123a1d52-899b-43d7-8458-03b1f7436498.jpg" width="400" />

**Comment by mrfullset** [comment]
I've created a PR for this https://github.com/NginxProxyManager/nginx-proxy-manager/pull/2599
