### ISSUE TITLE
After modifying Access List(s), NPM does not automatically update the configuration of the relevant Host(s)

### ISSUE THREAD

**Issue by MSDNicrosoft** [NginxProxyManager/nginx-proxy-manager#2524]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

> Notice: English is not my native language.

**Describe the bug**

After modifying or deleting Access List(s), NPM does not automatically update the configuration of the relevant Host(s).

**Nginx Proxy Manager Version**

`2.9.19`

**To Reproduce**

1. Add an Access List called `acc_1` (Assume that the settings are correct.)
2. Modify a host called `host_1`, and change its `Access List` option to `acc_1`
3. Modify the setting options for `acc_1` (e.g. username and password)
4. Visit `host_1`，Log in with the modified username and password.
5. You cannot log in with the modified username and password, but you can log in with the previous username and password.

Also, if you delete the Access List that has been used, although the web interface shows accessibility as `PUBLIC`, the actual accessing browser prompts "Untrusted Certificate" (The certificate is actually valid).

The current way to solve this problem manually is to **edit the problematic host(s), do not change anything, and click `Save`**

**Expected behavior**

After I modify or delete Access List(s), NPM should automatically update the configuration of the relevant host(s).

**Operating System**

Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-56-generic x86_64)

**Comment by Watn3y** [comment]
There's already an open issue for this. Check out #2254. It also includes a temporary fix

**Comment by sebastienvercammen** [comment]
+1 to this. Editing (and saving) an Access List does not update the hosts that use it. This poses a security risk, as a system admin might falsely believe that updating the Access List applies the changes to all necessary hosts.

#2254 was an unrelated bug and has since been closed. The "workaround" is a PowerShell script that uses the API to update all hosts without making any changes. This is not a solution.
