### ISSUE TITLE
Docker is running but no status with "docker ps"  

### ISSUE THREAD

**Issue by Ganzhans** [NginxProxyManager/nginx-proxy-manager#2525]
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
   Yes 
- Are you sure you're not using someone else's docker image?
   No
- Have you searched for similar issues (both open and closed)?
   Yes

**Describe the bug**
Works perfect ...... but  with  "docker ps"  it's up for more than 20 minutes and working, but no status like other containers  "health".  

**Nginx Proxy Manager Version**

V.2.9.19

**To Reproduce**

docker ps
no status 

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/100431846/211068967-a8607345-b982-448b-aafa-207b7c87917b.png)

**Operating System**

PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"

**Additional context**

**Comment by Watn3y** [comment]
What you want is a docker healthcheck. 

https://nginxproxymanager.com/advanced-config/#docker-healthcheck

**Comment by Ganzhans** [comment]
thnx !!

**Comment by Watn3y** [comment]
you're welcome :D don't forget to close the issue when your problem is solved
