### ISSUE TITLE
Nginx Proxy Manager doesn't pass the Real IP of the client

### ISSUE THREAD

**Issue by KaspianDev** [NginxProxyManager/nginx-proxy-manager#2560]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

I have a reverse proxy set up for my cockpit.
I'm using following configuration:
![image](https://user-images.githubusercontent.com/34658474/214516179-58997962-8d9c-455c-a9b8-8b896a5a2a26.png)
![image](https://user-images.githubusercontent.com/34658474/214516226-eeef4107-b798-4606-ab8c-a16acc7f0df4.png)
![image](https://user-images.githubusercontent.com/34658474/214516584-b1728fb7-95fa-4e3e-abfe-729343f8c719.png)

**Nginx Proxy Manager Version**

v2.9.19

**To Reproduce**
1. Install cockpit (but any application should work)
2. Set up a reverse proxy with my configuration
3. Login to cockpit and notice that it shows container's IP.

**Expected behavior**

I should see my own IP address in logs.

**Screenshots**

See Describe the bug

**Operating System**

Rocky linux

**Additional Information**
The address that shows in cockpit logs is the address from nginxproxymanager docker network 172.25.0.X

**Comment by unknown-qp** [comment]
hi @KaspianDev, are you fix this problem? if you solved this problem, can you help me and explain the way for me? thanks.

**Comment by KaspianDev** [comment]
> hi @KaspianDev, are you fix this problem? if you solved this problem, can you help me and explain the way for me? thanks.

I was using pterodactyl, first I had to add IP to trusted proxies.

Next I had to follow cloudflare nginx config.
