### ISSUE TITLE
Make a docker script.

### ISSUE THREAD

**Issue by MA-TTP** [NginxProxyManager/nginx-proxy-manager#2572]
So I want a `docker run` script for it rather than `docker compose` since it is easier to map one thing to one IP.

**Comment by No0Vad** [comment]
A starting point would be the [docker documentation](https://docs.docker.com/engine/reference/commandline/run/) and look at the [compose sample](https://nginxproxymanager.com/guide/#quick-setup) to see what arguments you need to run it through `docker run`.

**Comment by MA-TTP** [comment]
closed!
