### ISSUE TITLE
Max domain_names

### ISSUE THREAD

**Issue by Tokukarin** [NginxProxyManager/nginx-proxy-manager#2574]
![max domain ](https://user-images.githubusercontent.com/50606374/215930781-f5b924ab-c9a7-444b-a3af-6bd3272798d8.png)

I need more than 15 domain names for my mail server.

**Comment by notzenox** [comment]
I had the same issue, fixed by removing the `"maxItems": 15` line.

https://github.com/NginxProxyManager/nginx-proxy-manager/blob/cce73beb2da108a6de93cccdd82855805102ddb5/backend/schema/definitions.json#L171-L180

**Comment by Tokukarin** [comment]
@notzenox Thank you kind stranger <3

**Comment by Tokukarin** [comment]
For anyone who doesn't know how to fix this, I made a small script to change the max value to 50 inside the container:
https://github.com/Tokukarin/scriptCollection/blob/master/unlockMaxDomainnames.sh
