### ISSUE TITLE
Synology Apps not working via nginx proxy manager

### ISSUE THREAD

**Issue by tombauer** [NginxProxyManager/nginx-proxy-manager#2615]
I would like to make my Synology Photo app publicly available via the nginx proxy manager. Unfortunately, the Synology Photo app is not connecting. When I create the configuration on http I get a redirect to https, when I create the call on https I get an error message 502 Bad Gateway.

If I access the Photo-App via IP & port from the internal network everything works fine. I can also get a proper connection to other Apps on a Synology Docker trough the nginx Proxy Manager, so the connection is working. What am I doing wrong?

Does anyone have a solution for this? Thanks a lot for any help and hints.

<img width="811" alt="setup" src="https://user-images.githubusercontent.com/3863752/218657481-c8f8cde3-a9c2-4fa0-9ebe-e9de4d37e305.png">
<img width="499" alt="https-config" src="https://user-images.githubusercontent.com/3863752/218657486-b7e96980-964f-4f4f-a7da-ae7787e9b437.png">
<img width="616" alt="error" src="https://user-images.githubusercontent.com/3863752/218657720-3a7e3842-5f2f-4676-9a27-334237307b9a.png">

**Comment by ashimov** [comment]
Hi Tom!I think you have issue in your network. Because i host own synology drive with 10000 port & all work very well

**Comment by tombauer** [comment]
@ashimov thanks for the reply - i will check that out, but it's strange, that i can reach docker Containers on my Synology (ex. running UpTime Kuma) without problems... 
Are you running the nginx Proxy Manager direct on the Synology in a Docker Container or on a separate host? Do you have maybe additional config settings in the Advanced Tab on the nginx Proxy Manager for the Synlogy apps? Thanks again for your reply.

**Comment by ashimov** [comment]
@tombauer My nginx proxy manager working on separate vm in proxmox
No i don't have any advanced config settings

**Comment by tombauer** [comment]
@ashimov Thanks for your help and the explanation - in this case I'll have a look in the network settings of Synology. Hope to find and fix the error...

**Comment by tombauer** [comment]
I found the reason... Had to disable the automatic forwarding from http to https on synology... now it works like a charm :-).
