### ISSUE TITLE
Login screen bad gateway error

### ISSUE THREAD

**Issue by geverin** [NginxProxyManager/nginx-proxy-manager#2637]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

I changed my npm container from docker network to work with authentik but when i try to login the login screen shows "Bad Gateway".
The logs of the db container in portainer are normal but the logs of app container show this
"[2/27/2023] [2:31:59 AM] [Global   ] › ✖  error     getaddrinfo ENOTFOUND db"
and it keep repeating.
Is there a solution to this or is there any way to specify to use the already existing docker network in the docker-compose.yml ?
 

**Nginx Proxy Manager Version**

v2.9.19

**To Reproduce**
1. Go to 'Login Page'
2. Fill in email and password
3. Click 'Sign in'
4. See 'Bad Gateway'

**Expected behavior**

Go to dashboard

**Screenshots**

<img width="584" alt="Schermafbeelding 2023-02-27 033733" src="https://user-images.githubusercontent.com/91187291/221460682-94cf2b5e-d5f6-4ecf-bc0b-1651add5ea14.png">

**Operating System**
Docker on Debian Bullseye Lxc container on Proxmox

**Additional context**

**Comment by drajvver** [comment]
Since you closed it, how did you resolve that? @geverin

**Comment by baiyz0825** [comment]
i have the same question , login pages bad gateway

**Comment by baiyz0825** [comment]
you can try this ,t find the solution worked form me ,you can try this https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2598#issuecomment-1442443251
