### ISSUE TITLE
Custom port mapping ignored

### ISSUE THREAD

**Issue by mindonwarp** [NginxProxyManager/nginx-proxy-manager#2643]
Hi guys, I'm sorry if I'm posting a duplicate but I couldn't find what I was looking for.

I just installed the proxy manger as a docker container and created custom port mappings like so:
![image](https://user-images.githubusercontent.com/1856574/222537570-95ec5690-192b-4bc9-830b-e7dacf7311cb.png)

However, I can't reach the admin page on 8181 like I entered but I can reach the page at 81. I suspect the other ports have the same issue. Is this a known issue or am I doing something wrong?

I can't use the default ports since those are used by the host machine and I can't change them.

Thanks!

**Comment by sebasdt** [comment]
Have you tried to restart the stack/containers? That did the job for me.

**Comment by mindonwarp** [comment]
> Have you tried to restart the stack/containers? That did the job for me.

I have, several times. I have a feeling that these ports are fixed internally and can't be changed.
Perhaps that's the expected behavior?

**Comment by sebasdt** [comment]
Any updates? Otherwise please close the issue and mark ik as resolved.

**Comment by mindonwarp** [comment]
Nginx does use the ports 80 and 443 internally and those can't be changed, but it should be possible to map those internal ports to any other host port. I wasn't able to achieve that.

I did however change the setup so that I can use the default ports on host as well, i.e. 80:80 and 443:443.

I'll close the issue with a comment: "can't reproduce".

**Comment by mindonwarp** [comment]
Others can't reproduce the issue.
