### ISSUE TITLE
[Express  ] › ⚠  warning   invalid signature

### ISSUE THREAD

**Issue by schumi2004** [NginxProxyManager/nginx-proxy-manager#2688]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - No Reason: unable to renew certificate, running version v2.19.9
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
In the logs i see several messages like:
[Express  ] › ⚠  warning   invalid signature

**Nginx Proxy Manager Version**
2.19.9

**To Reproduce**
Just run NPM as normal and check logs

**Expected behavior**
No warning messages

**Screenshots**
n/a

**Operating System**
Docker

**Additional context**
[3/16/2023] [1:23:37 PM] [Express  ] › ⚠  warning   invalid signature
[3/16/2023] [1:23:38 PM] [Express  ] › ⚠  warning   invalid signature

I have no idea what above messages means so no clue if it can be ignored or not.
It says warning so i guess something is wrong.

**Comment by SeanChengN** [comment]
same problem

**Comment by jc21** [comment]
That error isn't part of the codebase and it's been seen before in #775 but the reporter said it fixed itself. I would think it's something related to the JWT given in the API request. Some things to try:

- use the new `2.9.21` docker image tag
- add the following environment variable to your docker-compose configuration:
```yml
  environment:
    DEBUG: 1
```

and you should see more info in the logs.

**Comment by swoop124** [comment]
Hello,

i have the same errors and did also a `DEBUG: 1 `and got same messagesa as `Marcbacca`.

any News?

**Comment by SeanChengN** [comment]
2.9.22
`[3/24/2023] [9:26:49 AM] [Express  ] › ⬤  debug     JsonWebTokenError: invalid signature
    at /app/node_modules/jsonwebtoken/verify.js:171:19
    at getSecret (/app/node_modules/jsonwebtoken/verify.js:97:14)
    at Object.module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:101:10)
    at /app/models/token.js:71:11
    at new Promise (<anonymous>)
    at Object.load (/app/models/token.js:65:11)
    at /app/lib/access.js:228:20
    at new Promise (<anonymous>)
    at Object.load (/app/lib/access.js:226:11)
    at /app/lib/express/jwt-decode.js:7:10`

**Comment by henkiewie** [comment]
I had the same error (2.9.22). Restarted the docker container that was/is using the API (in my case homepage gave an API error) and both errors were gone.  Maybe it helps someone.

**Comment by Marcbacca** [comment]
Can confirm, the patch 3-4 days ago appears to have fixed the issue. Yesterday's/today's updates haven't broken it.. seems to be fixed.

**Comment by scorpio2k2** [comment]
I still have the same issue:
Image used: jc21/nginx-proxy-manager           latest    5b3ff21ccf9

[3/27/2023] [2:52:03 PM] [Express  ] › ⬤  debug     JsonWebTokenError: invalid signature
    at /app/node_modules/jsonwebtoken/verify.js:171:19
    at getSecret (/app/node_modules/jsonwebtoken/verify.js:97:14)
    at Object.module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:101:10)
    at /app/models/token.js:65:11
    at new Promise (<anonymous>)
    at Object.load (/app/models/token.js:60:11)
    at /app/lib/access.js:228:20
    at new Promise (<anonymous>)
    at Object.load (/app/lib/access.js:226:11)
    at /app/lib/express/jwt-decode.js:7:10

**Comment by jc21** [comment]
I looked into this further, the warning is just a warning. It will happen when the JWT you use to access the API was encrypted with a different set of keys than is currently on file.

Prior to 2.10, this would be common, especially for those not using a mounted config file, as the keys would be generated after every docker container restart and wiped out.

With 2.10.0, these keys are now saved in the data folder and read from there.

I'll close this for now. If anyone experiences this with 2.10.0 or above AND think it's related to other behaviour, such as not being able to login, then please reopen.

**Comment by eriksneff** [comment]
@jc21 thx for looking into this. Not sure what the impact is here, but I'm on npm v2.10.1 and I'm seeing this `⚠️ warning invalid signature` message about once a minute as I navigate through my system. Here's a screenshot that I'm not sure will help: 
![image](https://user-images.githubusercontent.com/6926543/228701279-e89550d0-0e06-4caf-be93-4668149f12a9.png)

**Comment by GVA-Guillaume** [comment]
Last version and I have also this warning

<img width="670" alt="Capture d’écran 2023-07-12 à 16 36 42" src="https://github.com/NginxProxyManager/nginx-proxy-manager/assets/128600399/3fb45437-82c8-4a3a-9a4d-c15885b5059a">

But this is not only a warning,
because, the UI freeze it's then it's impossible to manage anything


[7/12/2023] [4:19:04 PM] [Express  ] › ⬤  debug     JsonWebTokenError: invalid signature
    at /app/node_modules/jsonwebtoken/verify.js:171:19
    at getSecret (/app/node_modules/jsonwebtoken/verify.js:97:14)
    at Object.module.exports [as verify] (/app/node_modules/jsonwebtoken/verify.js:101:10)
    at /app/models/token.js:65:11
    at new Promise (<anonymous>)
    at Object.load (/app/models/token.js:60:11)
    at /app/lib/access.js:228:20
    at new Promise (<anonymous>)
    at Object.load (/app/lib/access.js:226:11)
    at /app/lib/express/jwt-decode.js:7:10

**Comment by GVA-Guillaume** [comment]
After some investigations two points : 

strangely the problem comes from the database name, it seems that we are not able to harden the database" "npm" of the  most EXPOSED service in the network, a very clear security issue, most of the Dockerfile and/or Entrepont scripts needs to be fixed 

- to be rootless
- not hardcoded about all the env variables, everything must be changed
