### ISSUE TITLE
Acces Lists broken in 2.9.20

### ISSUE THREAD

**Issue by ranton1990** [NginxProxyManager/nginx-proxy-manager#2692]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - No
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
Since today, I cannot successfully add Access Lists. In the GUI i get an Internal Server Error, in the logs I get:
<pre>at ChildProcess.exithandler (node:child_process:402:12)

    at ChildProcess.emit (node:events:513:28)

    at maybeClose (node:internal/child_process:1100:16)

    at Socket.<anonymous> (node:internal/child_process:458:11)

    at Socket.emit (node:events:513:28)

    at Pipe.<anonymous> (node:net:301:12)

[3/16/2023] [5:32:16 PM] [Access   ] › ✔  success   Built Access file #7 for: Ich

[3/16/2023] [5:32:16 PM] [Express  ] › ⚠  warning   Command failed: /usr/bin/htpasswd
</pre>

**Nginx Proxy Manager Version**
v2.9.20, image pulled today at 3 a.m.

**To Reproduce**
1. Go to Access Lists
2. Click on Add Access List
3. Fill out the form, click on Save
4. See error: Internal Server Error
5. Refresh the page, list exists, editing gives the same error
6. Add list to proxy host, host switches to offline, gives 403 error.

**Expected behavior**
Working as in version 2.9.19

**Additional context**
Going back to 2.9.19 fixes the error.

**Comment by Microbolt** [comment]
I'm having issues with ACL's too.  I get an internal server error and when it writes out the nginx.conf it will only show the ; where the rules are normally at.  For example

I'm running with docker using the image jc21/nginx-proxy-manager:2

I get an error saying ; wasn't expected during start in my conf files and if I look inside of 10.conf for example I get:

```
location / {
    # Access Rules
    ;
    ;
    ;
    ;
    ;
    ;
    ;
    ;
    ;
    deny all;
    # Access checks must...
    satisfy all;
```

**Workaround for those affected.**  
- Open each of the conf files inside of /data/nginx/proxy_host/
- Delete all of those lines with just the semicolon 
- Roll back to 2.9.19 (I'm using jc21/nginx-proxy-manager:2.9.19 to get back up and running)
- Log back into webui
- Open the ACL and click save

That will rebuild the ACL and get you back up and running.

**Comment by SpecialAro** [comment]
I confirm that I'm having the same issue and that rolling back to 2.9.19 solves it.

**Comment by jc21** [comment]
@Microbolt your issue is due to a problem with ObjectionJS not returning prototyped objects anymore, something has changed somewhere in the dependencies, but I'm looking into it.

**Comment by jc21** [comment]
Please try the `github-develop` docker image tag for these fixes

**Comment by renzo-s** [comment]
Can confirm the fix for ACL works in the `github-develop` branch (and the cert configs are not nuked :) ).
Related: #2691
