### ISSUE TITLE
image does not exist

### ISSUE THREAD

**Issue by walter787a** [NginxProxyManager/nginx-proxy-manager#2694]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**
image does not exist

**Nginx Proxy Manager Version**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating System**

**Additional context**

**Comment by jc21** [comment]
Literally zero information.
