### ISSUE TITLE
[BUG] 2.9.20 breaks access list editing

### ISSUE THREAD

**Issue by wzzrd** [NginxProxyManager/nginx-proxy-manager#2698]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**
After adding a new entry to an access list, the proxy host configuration is rendered with just semi colons where IP addresses and semi colons should have been:

```
    # Access Rules
    ;
    ;
    ;
    ;
    ;
    ;
    deny all;
```

**Nginx Proxy Manager Version**
2.9.20

**To Reproduce**
1. Take an instance with an existing, pre-2.9.20, working access list
2. Update to 2.9.20
3. Add an entry to the access list
4. Restart container
5. Encounter error :/

**Expected behavior**
Container starts, renders access list for proxy 4. 

** Actual behavior:**
Container does not start anymore:
```
❯ Enabling IPV6 in hosts: /data/nginx
  ❯ /data/nginx/default_host/site.conf
  ❯ /data/nginx/proxy_host/6.conf
  ❯ /data/nginx/proxy_host/1.conf
  ❯ /data/nginx/proxy_host/2.conf
  ❯ /data/nginx/proxy_host/3.conf
  ❯ /data/nginx/proxy_host/7.conf
  ❯ /data/nginx/proxy_host/5.conf
  ❯ /data/nginx/proxy_host/4.conf
  ❯ /data/nginx/redirection_host/1.conf
nginx: [emerg] unexpected ";" in /data/nginx/proxy_host/4.conf:63
```
Note: I edited the proxy host with id = 4 and added an additional IP address to it. I have both IPv4 and IPv6 addresses in access list.

**Operating System**
Podman container on RHEL9, with a volume for /data;

**Comment by xofox25** [comment]
I would like raise the same issue before seeing this topic.
The issue was already present in previous version of npm (2.9.19)

**Comment by wzzrd** [comment]
Really? I haven't seen it on 2.9.19, tbh, but maybe that's because my setup was fairly static until yesterday.

**Comment by g1uliano** [comment]
In my setup I have more than 60 domains, I had never had problems until this update, I came here to report this problem and saw that this issue already existed. To mitigate the problem, I used an image from a previous version, and it does not have this bug. Remembering that this is happening with all hosts, just edit and save and you will have the problem. The only solution other than downgrading is to not use the access lists

**Comment by wzzrd** [comment]
Well, another solution is to copy the 4.conf out of the container and edit it outside of it before pushing it back. Quirky but it works.

**Comment by xofox25** [comment]
my workaround is to remove the proxy host and create another one.
I also manage to stop the docker, edit the .conf by adding the Access Rules and start the docker.
But sometimes it breaks the npm conf and I need to revert a snapshot of the VM.

**Comment by kaisermtek** [comment]
I just killed 2 1/2 hours trying to figure out why my bloody Access List kept borking NPM.  Low and behold!  150min of life I'll never get back.

**Comment by jc21** [comment]
Fixed in `github-develop` branch, and new release coming very soon
