### ISSUE TITLE
cert-prune 'Path "/etc/letsencrypt" does not look like a Let's Encrypt folder'

### ISSUE THREAD

**Issue by jjpvdpoel** [NginxProxyManager/nginx-proxy-manager#2708]
Looking at the cert-prune source ('{"live", "archive", "csr", "keys"}') it seems that the folders 'csr' and 'keys' are missing in my letsencrypt folder in order to make it run. I'm running 2.9.21

**Comment by jjpvdpoel** [comment]
Looks like the folders are deprecated lately in certbot (https://github.com/certbot/certbot/pull/9537).
Guess cert-prune needs an update...

**Comment by blaine07** [comment]
> Looks like the folders are deprecated lately in certbot ([certbot/certbot#9537](https://github.com/certbot/certbot/pull/9537)). Guess cert-prune needs an update...

NPM Uses a implmentation found here; I would make sure there is a issue opened here as well: https://github.com/axllent/cert-prune

**Comment by jc21** [comment]
Yep I just include the binary. Feel free to link this issue to their github project's issue.

**Comment by Investigamer** [comment]
This issue was closed over a year ago but still persists to this day...?
