### ISSUE TITLE
nginx-proxy-manager Not support GRPC?

### ISSUE THREAD

**Issue by babutree** [NginxProxyManager/nginx-proxy-manager#2718]
When I add the following code, which includes grpc-related functionality, a "502 Bad Gateway" error occurs. 
Proxy Hosts - Custom Nginx Configuration

```
location / {
    proxy_pass http://172.17.0.1:8018;
    proxy_set_header Host $host;
    grpc_socket_keepalive on;
    grpc_pass grpcs://172.17.0.1:8015;
}
```

And I comment out the grpc-related code, the service can be reverse proxied, but it does not support grpc.

`location / {
    proxy_pass http://172.17.0.1:8018;
    proxy_set_header Host $host;
    #grpc_socket_keepalive on;
    #grpc_pass grpcs://172.17.0.1:8015;
}`

Thanks!

**Comment by Yang-z** [comment]
Hi, 
Here is how I config a proxy host to let it support http, ws and grpc at the same time. 
In the 'Details' tab, fill the Scheme, Forward Hostname/IP, Forward Port, and turn on 'websockets Support' just as normal.  In the 'Advanced' tab, paste the fellowing config and modify the grpc url.
It works for me, hope that could help.
`
underscores_in_headers on; 
location / {
    grpc_read_timeout 300s;
    grpc_send_timeout 300s;
    grpc_socket_keepalive on;
    if ($http_content_type = "application/grpc") {
        grpc_pass grpc://172.18.0.1:7891;
    }

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;
    
    # Proxy!
    include conf.d/include/proxy.conf;
}
`
`
ref: https://pydio.com/en/docs/kb/deployment/running-cells-behind-nginx-reverse-proxy
`

**Comment by Yang-z** [comment]
@babutree Is it possible for nginx-proxy-manager to support grpc config through GUI just as websockets? It would be fantastic if that could be done.

**Comment by popliviustefan** [comment]
By any chance... @Yang-z  do you know how to translate those directives in HAProxy plugin for pfSense?

**Comment by teoder** [comment]
> By any chance... @Yang-z  do you know how to translate those directives in HAProxy plugin for pfSense?

Have you looked at this?

https://www.haproxy.com/documentation/haproxy-configuration-tutorials/load-balancing/grpc/

**Comment by popliviustefan** [comment]
Hi! I've seen that! But in pfsense I can't directly edit haproxy files, I have to set it from the web UI and I couldn't figure it out...

**Comment by teoder** [comment]
> web

Best bet is to edit the configuration manually in CLI or you would probably need to add this configuration to the "Advanced pass thru" section. (Available for both frontend and backend)

**Comment by teoder** [comment]
You could try something like this with your IP/Port information 😃 
I **Think** you'll be able to achieve this using the "advanced" field for both _Frontends_ and for _Backends_

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/8885430/ce923653-7a98-44be-8fca-2ec03e88419c)

**Comment by popliviustefan** [comment]
Hi! 
In the frontend I don't know where to enter the directive proto h2, since both on port 80 and 443 I have shared frontends, and the advanced editbox is only on the main frontend. But the rest of my apps are not http/2, so I don't think it would be ok to set proto h2 on the main frontend. 
I was under the impression that setting alpn h2,http/1.1 in Advanced certificate specific ssl options would accomplish the same, but probably not, since it isn't working...

**Comment by oanhnn** [comment]
> Hi, Here is how I config a proxy host to let it support http, ws and grpc at the same time. In the 'Details' tab, fill the Scheme, Forward Hostname/IP, Forward Port, and turn on 'websockets Support' just as normal. In the 'Advanced' tab, paste the fellowing config and modify the grpc url. It works for me, hope that could help.
> 
> underscores_in_headers on; location / { grpc_read_timeout 300s; grpc_send_timeout 300s; grpc_socket_keepalive on; if ($http_content_type = "application/grpc") { grpc_pass grpc://172.18.0.1:7891; } proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection $http_connection; proxy_http_version 1.1; # Proxy! include conf.d/include/proxy.conf; }
> 
> ref: https://pydio.com/en/docs/kb/deployment/running-cells-behind-nginx-reverse-proxy

Thank @Yang-z .
It work for me.

**Comment by babutree** [comment]
OK, Thank you very much!
