### ISSUE TITLE
I proxy my code-server through nginx-proxy-manager and got an error

### ISSUE THREAD

**Issue by snicoe** [NginxProxyManager/nginx-proxy-manager#2736]
my English is not good, please don't mind -_-lol
I deployed the project on docker and successfully obtained the ssl certificate，the code-server is deployed on my homelab server. I proxy the code-server port through, when I access it with the domain, the code-server returns an error of "websocket 1006". By adding
proxy_set_header Upgrade $http_upgrade; 
proxy_set_header Connection "Upgrade"; 
proxy_set_header Host $host;
establish websocket connection normally, I want to know the reason.

**Comment by theraw** [comment]
code-server requires websocket support so you have to enable it
![image](https://user-images.githubusercontent.com/32969774/229418544-8fee5cd9-b470-4620-95eb-817cac8886f4.png)

**Comment by lauren12133** [comment]
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/77604108/4105c16d-4836-45a8-adda-34ed117b26d0)

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/77604108/7a2ca568-dd1e-4f82-8ced-1ff6a19d8e6f)

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/77604108/3a5d606d-52de-40e4-b0ce-f1e6eaee6f52)

useless！！！！

**Comment by snicoe** [comment]
@theraw websockets support is enabled，websocket 1006 is still reported, like @lauren12133

**Comment by snicoe** [comment]
websockets support is enabled，websocket 1006 is still reported, like @lauren12133

**Comment by snicoe** [comment]
> code-server requires websocket support so you have to enable it ![image](https://user-images.githubusercontent.com/32969774/229418544-8fee5cd9-b470-4620-95eb-817cac8886f4.png)

websockets support is enabled，websocket 1006 is still reported, like @lauren12133

**Comment by wbrione** [comment]
Same stuff here !!! "Websockets Support" option has no effect all :-(

**Comment by snicoe** [comment]
@wbrione bro i solved this problem :) maybe help.
Add “Custom Nginx Configuration", no other changes are needed.
```
location /
{
    proxy_pass http://[YOUR_SERVER_IP]:9901;
    proxy_set_header Host [YOUR_DOMAIN]:25052;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header   Upgrade          $http_upgrade;  
    proxy_set_header   Connection       "Upgrade";
    proxy_connect_timeout      60;   
    proxy_send_timeout         90;   
    proxy_read_timeout         90; 
    proxy_buffer_size          4k; 
    proxy_buffers              4 32k;
    proxy_busy_buffers_size    64k;  
    proxy_temp_file_write_size 64k;
    add_header X-Cache $upstream_cache_status;
}
```

**Comment by wbrione** [comment]
@snicoe 

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/66576320/ba808756-84da-4f74-aa49-c0630356dc99)

So, i created a "custom location", but... same error... in fact, some errors are still very specific, like...

```
Unable to open 'workspace'
Unable to resolve resource vscode-remote://<my domain>/config/workspace
```

or 

`ENOPRO: No file system provider found for resource 'vscode-remote:/config/data/User/settings.json'`

So... back in your tip... I believe that plus change the [SERVER_IP] and [DOMAIN], i need replace the ports of two first lines, right ?! 

Ports: 9901 and 25052... i don't recognize this :flushed:

**Comment by snicoe** [comment]
@wbrione yes ,you need replace the ports of two first lines

**Comment by WannaYoung** [comment]
> @wbrione bro i solved this problem :) maybe help. Add “Custom Nginx Configuration", no other changes are needed.
> 
> ```
> location /
> {
>     proxy_pass http://[YOUR_SERVER_IP]:9901;
>     proxy_set_header Host [YOUR_DOMAIN]:25052;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header REMOTE-HOST $remote_addr;
>     proxy_set_header   Upgrade          $http_upgrade;  
>     proxy_set_header   Connection       "Upgrade";
>     proxy_connect_timeout      60;   
>     proxy_send_timeout         90;   
>     proxy_read_timeout         90; 
>     proxy_buffer_size          4k; 
>     proxy_buffers              4 32k;
>     proxy_busy_buffers_size    64k;  
>     proxy_temp_file_write_size 64k;
>     add_header X-Cache $upstream_cache_status;
> }
> ```
> 
> change the [YOUR_SERVER_IP], [YOUR_DOMAIN] and server port to your own

You save my life!
