### ISSUE TITLE
Certificate not found. Nginx not starting after newest update

### ISSUE THREAD

**Issue by boehser-enkel** [NginxProxyManager/nginx-proxy-manager#2751]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**
[](ginx: [emerg] cannot load certificate "/etc/letsencrypt/live/npm-23/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/npm-23/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file))

**Nginx Proxy Manager Version**
Newest and also tried out some old ones now

**To Reproduce**
Start Nginx Proxy Manager after updating.
Check: the path is not there. Also not in my backups
The error comes right after loading of default_host\site.conf

**Expected behavior**
Clean start

**Screenshots**

**Operating System**
Ubuntu

**Additional context**

**Comment by romainlouvet** [comment]
I have same issue, how are you fix it @boehser-enkel ?
