### ISSUE TITLE
id: 'npmuser': no such user

### ISSUE THREAD

**Issue by JosonJiang** [NginxProxyManager/nginx-proxy-manager#2760]
emqx_nginx-proxy         | ❯ Configuring npmuser ...
emqx_nginx-proxy         | id: 'npmuser': no such user
emqx_nginx-proxy         | ❯ Checking paths ...
emqx_nginx-proxy         | ❯ Setting ownership ...
emqx_nginx-proxy         | s6-rc: fatal: timed out
emqx_nginx-proxy         | s6-sudoc: fatal: unable to get exit status from server: Operation timed out
emqx_nginx-proxy         | /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.

run in Docker 

`  nginx-proxy:
      image: 'jc21/nginx-proxy-manager:latest'
      container_name: emqx_nginx-proxy
      hostname: nginx-proxy.emqx.io
      restart: unless-stopped
      ports:
        - '6808:80'
        - '8818:81'
        - '7443:443'
      # volumes:
      #   - ./nginx/nginx-proxy-manager/data:/data
      #   - ./nginx/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
`

**Comment by jc21** [comment]
Please try the `github-develop` branch to resolve the fatal problem - there are other issues reporting this.

The title `id: 'npmuser': no such user` is not part of the problem and is informational in the logs only.

**Comment by AceTheSpaceCase** [comment]
> Please try the `github-develop` branch to resolve the fatal problem - there are other issues reporting this.
> 
> The title `id: 'npmuser': no such user` is not part of the problem and is informational in the logs only.

I tried github-develop but still had the same issue.

Using github-pr-2661 seemed to fix the issue for me.
