### ISSUE TITLE
"ssl_reject_handshake on" disables TLSv1.3

### ISSUE THREAD

**Issue by Fulachs** [NginxProxyManager/nginx-proxy-manager#2763]
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
If you use any version newer than [v2.9.19](https://github.com/NginxProxyManager/nginx-proxy-manager/releases/tag/v2.9.19) 
TLSv1.3 breaks and is no longer working. 
See the change [here](https://github.com/NginxProxyManager/nginx-proxy-manager/commit/a7f0c3b730678ae4352ade2829d891a3ce3cd3bc#diff-28012d6b25fda389a907f6c2484bc834e5cff720ae799b41777a592ef4e3a5b7R35)
See issue ticket https://trac.nginx.org/nginx/ticket/2071

**Nginx Proxy Manager Version**
v2.9.20+

**To Reproduce**
1. Install any version v2.9.20+
2. add a proxy and check the TLS version
3. maximum is TLSv1.2

**Expected behavior**
TLSv1.3 should work

Found by @piuswalter and myself.

**Comment by nietzscheanic** [comment]
+1

**Comment by BlackKerio** [comment]
+1
