### ISSUE TITLE
NPM SSL Advanced - Ghost CMS stuck in infinite HTTPS redirect loop

### ISSUE THREAD

**Issue by gillgitt** [NginxProxyManager/nginx-proxy-manager#2766]
I'm running NPM and Ghost CMS on two separate docker containers (Ubuntu) via Portainer UI. The Ghost URL is accessible via NPM using HTTP, but runs into infinite redirects when turning on SSL (Let's Encrypt). Below is Ghost documentation to help resolve this issue, however, I tried using this under the 'Advanced Setup' and it doesn't see to recognize this customization at all.

My setup is 

- VMware - Ubuntu
 - Docker
 - Portainer
   - npm
   - mysql
   - ghost
   - wordpress

**https://ghost.org/docs/faq/proxying-https-infinite-loops/** 

**_If you run into an infinite redirect loop when trying to configure your own proxy with nginx, apache, cloudfront or any other proxy and serving Ghost over HTTPS, this is due to the x-forwarded-proto header being set incorrectly. Your proxy will handle SSL termination and proxy to Ghost using http. To tell Ghost that the requests coming into the proxy are secure, set the x-forwarded-proto header to https. Without this, Ghost will think the requests are insecure, attempt to redirect to the https version of a URL and cause an infinite redirect loop._**

```
location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $http_host;
    proxy_pass http://127.0.0.1:2368;
}

client_max_body_size 50m;
```

<img width="504" alt="Screenshot 2023-03-28 at 5 54 51 PM" src="https://user-images.githubusercontent.com/129237886/228399003-76289827-97f7-4964-ab5e-e05c9346d48c.png">

Any suggestions?

**Comment by gillgitt** [comment]
It was resolved by reinstalling npm. The /letsencrypt directory didn't have appropriate storage permissions.

**Comment by ikonnow** [comment]
Ghost's docker configuration is actually quite straightforward. However, if you use nginxproxymanager like I do, you will find that ghost's interface is not linked correctly. So all assets point to the localhost path. 

Only this hint helped me to finally get ghost up and running, so THANK YOU VERY MUCH!
