### ISSUE TITLE
CPU Cores @ 100% for nginx worker past 2.9.19

### ISSUE THREAD

**Issue by gadgetusaf** [NginxProxyManager/nginx-proxy-manager#2794]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - No
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

**Nginx Proxy Manager Version**

**To Reproduce**
I upgraded the docker container, each release past 2.9.19 all cores peg to 100 with in a few min.

**Expected behavior**

**Screenshots**

**Operating System**

**Additional context**

**Comment by theraw** [comment]
do you see any type of error on your logs?

**Comment by gadgetusaf** [comment]
I see noting abnormail in the logs though the system becomes unstable quite quickly as the Nginx worker(s) onper core each consume the cpu.

I am thinking its a bug and I wa working on rebuilding the new container. But I can help test before I decom the server if it is useful.

**Comment by gadgetusaf** [comment]
I just rebuilt and am facing the same Issue. 
Are there any recomendations to get usefull information to troubleshoot.

**Comment by gadgetusaf** [comment]
`proxy_max_temp_file_size 0;
client_body_buffer_size 0;
client_max_body_size 0;
proxy_buffering                 off;
proxy_request_buffering off;`

This is the custom config on a number of sites I am running

**Comment by gadgetusaf** [comment]
I uncovered the issues as I thought it was with an advanced config. Once I cleaned up a few issues there I was able to upgrade without issue.

**Comment by javito1081** [comment]
did ya guys fi

> **Checklist**
> 
> * Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
>   
>   * Yes
> * Are you sure you're not using someone else's docker image?
>   
>   * No
> * Have you searched for similar issues (both open and closed)?
>   
>   * Yes
> 
> **Describe the bug**
> 
> **Nginx Proxy Manager Version**
> 
> **To Reproduce** Steps to reproduce the behavior: I upgraded the docker container, each release past 2.9.19 all cores peg to 100 with in a few min.
> 
> **Expected behavior**
> 
> **Screenshots**
> 
> **Operating System**
> 
> **Additional context**

did ya guys find a fix for this? cause im experiencing this issue for a few days now, and i havent found a fix yet

**Comment by Kieranwest** [comment]
Getting similar issues. At first thought I was getting spammed with bots but with no external rules forwarding I'm still seeing maxed CPU usage.
