### ISSUE TITLE
[feature request] Global custom nginx config

### ISSUE THREAD

**Issue by leoleoasd** [NginxProxyManager/nginx-proxy-manager#2798]
**Is your feature request related to a problem? Please describe.**

I want to enable redirect to https **on http request send to https port**(497 error) for all hosts.

**Describe the solution you'd like**

Allow me setting
```
error_page 497 https://$host$request_uri;
```
for all hosts.

**Describe alternatives you've considered**

manually setting it for every host.

**Additional context**

**Comment by the1ts** [comment]
Is this not covered by [advanced configuration](https://nginxproxymanager.com/advanced-config/#custom-nginx-configurations) documented on the website?

**Comment by leoleoasd** [comment]
Ohh it is. I thought where would be a GUI for this.
