### ISSUE TITLE
Internal Error: when creating a new ssl certificate UBUNTU v18/v20 & DEBIAN v11

### ISSUE THREAD

**Issue by KodekaTeamOfficial** [NginxProxyManager/nginx-proxy-manager#2800]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - No
- Are you sure you're not using someone else's docker image?
  - No
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

Internal Error: when creating a new ssl certificate
so, i will add my subdomain and when will create ssl in SSL TAB with modal. i can't create and add new ssl.

in addition, on the SSL Certificate TAB.
I also can't create a new Certificate.
when I try to test 'Test Server Reachability' it always shows the response 'Communication with the API failed, is NPM running correctly?'

and when I force to save, I get an error log like this:

Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name " npm-6" --agree-tos --authenticator webroot --email "email@gmail.com" --preferred-challenges "dns,http" --domains "sub.domain.my.id"
Saving debug log to /tmp/letsencrypt-log/letsencrypt.log
Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/letsencrypt-log/letsencrypt.log or re-run Certbot with -v for more details.

    at ChildProcess. exithandler (node:child_process:402:12)
    at ChildProcess. emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

**Nginx Proxy Manager Version**

V2.10.2 -> before

**Operating System**

I am using UBUNTU v18 and v20 operating system.
and DEBIAN v11

**Comment by andzejsp** [comment]
smells awfully like #2713

**Comment by KodekaTeamOfficial** [comment]
**updates!**
after I searched, it turns out this is not a bug.
Turns out I haven't pointed the public IP to Cloudflare DNS correctly.
And now, I've managed to do well.

Thank you, and I permission to close this thread
