### ISSUE TITLE
Expand default Docker subnet CIDR to be more inclusive

### ISSUE THREAD

**Issue by lyh16** [NginxProxyManager/nginx-proxy-manager#2829]
**Is your feature request related to a problem? Please describe.**

The current "set_real_ip_from" that targets the Docker subnet points to the CIDR "172.16.0.0/12" as referenced below.

https://github.com/NginxProxyManager/nginx-proxy-manager/blob/5f2576946de7955f7318218bfd19570b8c857b76/docker/rootfs/etc/nginx/nginx.conf#L63

However, due to the many possible ways of configuring Docker in the wild, many users often end up with a different subnet which is not covered by the above mentioned CIDR. This results in many users failing to acquire the real IP address of visitors using the default configurations. A quick Google search will reveal that quite a lot of users opt to modifying the CIDR for Docker.

**Describe the solution you'd like**

Change the CIDR for the Docker subnet from the current "172.16.0.0/12" to "172.0.0.0/8"

**Describe alternatives you've considered**

Manually modify the CIDR to match my needs via "docker exec -it".
However, even if I fix the CIDR to my likings by using "docker exec -it", pulling a newer version of the Docker image for the project will result in the resetting of the said customizations.

**Additional context**

**Comment by Zoey2936** [comment]
It is a very bad idea to trust public ips...

**Comment by lyh16** [comment]
> It is a very bad idea to trust public ips...

Ahh... my bad. Yes, you are right. I somehow mistakenly thought that the mentioned issue was related to some kind of limitation on NPM's part. But it actually was a misconfiguration issue on my part. Compliance with RFC 1918 should be enough. Calling down issue and pull request.
