### ISSUE TITLE
Login No relevant user found

### ISSUE THREAD

**Issue by poltrian** [NginxProxyManager/nginx-proxy-manager#2832]
I've been using the Nginx Proxy Manager as a docker for a couple of years. I haven't been able to log in for a while
No relevant user found

I have the login data in a password manager, so they must be correct

v2.10.2

**Comment by phillf** [comment]
@poltrian, this may sound a little daft but did you try logging in with the default credentials.

Default Admin User:
```
Email:    admin@example.com
Password: changeme
```

**Comment by poltrian** [comment]
Thanks,

**Comment by JVKeller** [comment]
Hello,

Fresh install on Portainer, same error.
