### ISSUE TITLE
Bad Gateway on login

### ISSUE THREAD

**Issue by EyyupA** [NginxProxyManager/nginx-proxy-manager#2841]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
On login I get a message "Bad Gateway".
I try everything. I search searched for same issues.

**Nginx Proxy Manager Version**
v2.10.2

**To Reproduce**
1. Use this docker compose
`version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
    environment:
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: npm
      DB_MYSQL_PASSWORD: npm
      DB_MYSQL_NAME: npm
    volumes:
      - nginx_proxy_manager-data:/data
      - nginx_proxy_manager-letsencrypt:/etc/letsencrypt
    networks:
      default:
    depends_on:
      - db
      
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - nginx_proxy_manager-mysql:/var/lib/mysql
    networks:
    default:
    
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.51.0.0/16
          gateway: 10.51.0.1
          
volumes:
  nginx_proxy_manager-data:
  nginx_proxy_manager-letsencrypt:
  nginx_proxy_manager-mysql:`

**Expected behavior**
Login Page

**Screenshots**
![image](https://user-images.githubusercontent.com/65238400/233322831-327fc0f5-5e8d-439c-9123-bde65736c7f7.png)

**Operating System**
Linux

**Additional context**
Docker version 23.0.4, build f480fb1

**Comment by abhishekbhakat** [comment]
Facing the same with provided docker-compose yaml on docs.

**Comment by KimVatnedal** [comment]
You could use "docker ps" to find your container id and then "docker logs [container ID]".

If you see a lot of create table errors with permission denied, it is likely permission issues on the mysql folder.

In that case you could try to do a "chmod 777 -R [mysql folder]".

**Comment by EyyupA** [comment]
I solved it by using another db 

like this compose file:
`version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      #- '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MARIADB_HOST: "db"
      DB_MARIADB_PORT: 3306
      DB_MARIADB_USER: "npm"
      DB_MARIADB_PASSWORD: "npm"
      DB_MARIADB_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      default:
    depends_on:
      - db

  db:
    image: 'webhippie/mariadb:latest'
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: 'npm'
      MARIADB_DATABASE: 'npm'
      MARIADB_USER: 'npm'
      MARIADB_PASSWORD: 'npm'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      default:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.51.0.0/16`

**Comment by abhishekbhakat** [comment]
Can we have the docs updated ?

**Comment by AndySM412** [comment]
I have the same issue but only when I play with the network. Using the standard documented compose file everything works. 

When I change the services to run on the default bridged network I get the error. If I then redeploy once again allowing docker compose to create a new bridge network just for these services everything works again.

**Comment by AndySM412** [comment]
Ignore my last message but I will leave it if it helps others. The default bridge network does not support DNS so the app can not find the DB server by name. I will move my other containers over to the the nginxproxy network.
