### ISSUE TITLE
You can help me, please!!!

### ISSUE THREAD

**Issue by wleelw** [NginxProxyManager/nginx-proxy-manager#2864]
Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --cert-name "npm-2" --agree-tos --email "@outlook.com" --domains "xn--i8s384bvyz8bd.xn--fiqs8s" --authenticator dns-dnspod --dns-dnspod-credentials "/etc/letsencrypt/credentials/credentials-2"
Saving debug log to /var/log/letsencrypt/letsencrypt.log
[DNSPOD] Record.Create error: Domain not exist
[DNSPOD] Record.List error: Domain not exist
Error communicating with the DNSPOD API: Domain not exist
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

**Comment by wleelw** [comment]
my domain is Chinese, it's unable to recognize now.

**Comment by DUCKCHI** [comment]
nginx-proxy-manager currently has an internal error. 
The DNS challenge does not appear to be possible at this time.

**Comment by lux032** [comment]
same error

**Comment by wleelw** [comment]
it's ok
