### ISSUE TITLE
NPM docker wont start.

### ISSUE THREAD

**Issue by blownco** [NginxProxyManager/nginx-proxy-manager#2885]
seems to be in some sort of restart loop? anyone else have this?

[supervisor  ] service 'nginx' exited (with status 1).
[supervisor  ] restarting service 'nginx'.
[supervisor  ] starting service 'nginx'...
[nginx       ] nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/npm-3/fullchain.pem": BIO_new_file() failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/etc/letsencrypt/live/npm-3/fullchain.pem','r') error:2006D002:BIO routines:BIO_new_file:system lib)

**Comment by blownco** [comment]
a full reinstall fixed the issue.

**Comment by BHeshka** [comment]
I ran into this issue after deleting an SSL certificate that was still being used by proxy hosts.

**Comment by jqtmviyu** [comment]
create files like `letsencrypt/live/npm-13/fullchain.pem`  `letsencrypt/live/npm-13/privkey.pem`,  resolve it.
