### ISSUE TITLE
Loopia DNS

### ISSUE THREAD

**Issue by addelovein** [NginxProxyManager/nginx-proxy-manager#2891]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes / No
- Are you sure you're not using someone else's docker image?
  - Yes / No
- Have you searched for similar issues (both open and closed)?
  - Yes / No

**Describe the bug**

Internal Error when using DNS challenge

**Nginx Proxy Manager Version**

**To Reproduce**

**Expected behavior**

**Screenshots**

I have setup API account entered user and password in the box...

**Operating System**

**Additional context**

**Comment by supersonical** [comment]
For anyone who has issue with Loopia DNS challange which i have personally been struggling with getting wildcard certs. The issue for me was that the example is missing space between the Username and password. See my examples. 

Here is the wrong formatting.
![Skärmavbild 2024-10-24 kl  23 57 36](https://github.com/user-attachments/assets/f7085ad2-4ff3-44ce-828b-d67e92d4b576)

Here is the correct formatting of the username and password.
![Skärmavbild 2024-10-24 kl  23 59 18](https://github.com/user-attachments/assets/eacc38f1-a6ad-4cdf-964b-2ab2c0d9cbed)

And also use 120 sec Propagation Seconds, the default is to short.
