### ISSUE TITLE
Getting domain_names.map is not a function error in HOSTS

### ISSUE THREAD

**Issue by pmorange** [NginxProxyManager/nginx-proxy-manager#2914]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
Almost everything is in the title ^^
When I enter the Hosts > Proxy Hosts menu, none of the 20 or so Hosts I have configured appear, and I see the following error :
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/8950440/11698c51-7be1-4b1d-a4df-37c966192c57)

domain_names.map is not a function

In Chrome's console, the following can be seen :
```
TypeError: domain_names.map is not a function
    at module.exports (7.bundle.7.js?v=2.10.3:1:6179)
    at i.render (main.bundle.js?v=2.10.3:310:15407)
    at i._renderHtml (main.bundle.js?v=2.10.3:303:68288)
    at i._renderTemplate (main.bundle.js?v=2.10.3:27:115832)
    at i.render (main.bundle.js?v=2.10.3:27:131271)
    at ae (main.bundle.js?v=2.10.3:27:122435)
    at main.bundle.js?v=2.10.3:27:140662
    at Function.Dt (main.bundle.js?v=2.10.3:3:28769)
    at i._getBuffer (main.bundle.js?v=2.10.3:27:140642)
    at i._renderChildren (main.bundle.js?v=2.10.3:27:140463)
```

**Nginx Proxy Manager Version**
2.10.3

**To Reproduce**
1. Go to Hosts > Proxy Hosts

**Expected behavior**
See the list of Proxy Hosts

**Screenshots**
Already provided screenshot with the description.

**Operating System**
Docker on Alpine Linux.

**Additional context**
I just updated to the latest version, it was working fine before.
But I don't know on which version I was before...

**Comment by pmorange** [comment]
Hi,
Now on 2.10.4 and still seeing the same error.
Any pointers ?

**Comment by milkpirate** [comment]
I try to provision my `nginxproxymanager` via writing to the sqlite DB. I get the same message when I insert the certificate entry. How did you (@pmorange) solve the problem?

**Comment by pmorange** [comment]
> I try to provision my `nginxproxymanager` via writing to the sqlite DB. I get the same message when I insert the certificate entry. How did you (@pmorange) solve the problem?

Hi, 
I was able to solve that by checking in debug mode the json I receive on the webpage. You can do that for instance in Brave and Chrome by opening the developer mode.
My problem was that in the name or description (can't remember which one exactly), I had badly closed " . You can check all the names you have and see if any one of them has a missing quote.

Hoe that helps.

**Comment by ThRPctmylSgltwH** [comment]
@milkpirate or @pmorange After following the database migration from mysql to sqlite #1529 I have the same error. I have looked for badly closed double quotes but have not found any. I did have an issue with the text **Let's Encrypt** on certificates since the sql escape **\'** remained after migration. I have now corrected that and changed it from **Let\'s Encrypt to Let's Encrypt** in the table **audit_log**. Can you be more specific on which table and which field has an issue with double quotes?

**Comment by milkpirate** [comment]
I guess table/field containing JSON related. JSON is very picky with its quotes and does not accept '. Further the " must be escaped in the field content/value. 

But anyway, I migrated to cloudflare tunnels. Its free, there are a lot of tutorials online (e.g. youtube) and it offers a lot (!) of functionality for free (e.g. SSL certs, Oauth for the endpoints aso.). You might need a domain thought but there are really cheap offers for as low as a few bucks / year (if you're not picky with your TLD - have a look here: https://tld-list.com/).

Sure one then is dependent on a cloud provider but still, for me the feature richness is worth it.

**Comment by ThRPctmylSgltwH** [comment]
I was able to solve it and the explanation is here.
#https://github.com/NginxProxyManager/nginx-proxy-manager/discussions/1529#discussioncomment-8959737
