### ISSUE TITLE
SSL DNS Challenge Issue

### ISSUE THREAD

**Issue by sglavach** [NginxProxyManager/nginx-proxy-manager#2921]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

Go to SSL Tab and try to create wildcard certificate.  Put in key and secret, select DNS Challenge and GoDaddy as provider.
Receive following error:

LOG:
[5/15/2023] [2:43:06 PM] [Express  ] › ⚠  warning   Command failed: . /opt/certbot/bin/activate && pip install --no-cache-dir --user certbot-dns-godaddy~=0.2.0  && deactivate
ERROR: Will not install to the user site because it will lack sys.path precedence to urllib3 in /opt/certbot/lib/python3.7/site-packages

DIALOG BOX:
Error: Command failed: . /opt/certbot/bin/activate && pip install --no-cache-dir --user certbot-dns-godaddy~=0.2.0  && deactivate
ERROR: Will not install to the user site because it will lack sys.path precedence to urllib3 in /opt/certbot/lib/python3.7/site-packages

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

Worked in previous version...

**Nginx Proxy Manager Version**

2.10.3

**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating System**

**Additional context**

**Comment by dcazman** [comment]
I get this same error

**Comment by matlantin** [comment]
Same issue with v2.10.3 and Online as DNS provider.

**Comment by Gianpaolopicariello** [comment]
I have the same bug with version 2 and 2.10.3.

**Comment by j93874** [comment]
I have the same when using godaddy dns and version 2.10.3

**Comment by varyform** [comment]
Works fine on 2.10.2

**Comment by viktak** [comment]
Sorry to ask a (somewhat related) question here, but I didn't find a better place to ask it...
Where do I save the `credentials.ini` file?

**Comment by andzejsp** [comment]
so its still borked?

**Comment by joemcc-90** [comment]
https://community.letsencrypt.org/t/nginx-proxy-manager-and-cert/198147 <--- posting this for info, hopefully it can help somebody, there is a fix posted here from a certbot engineer who advises to remove the --user flag from the command. I haven't tested this myself

**Comment by instantdreams** [comment]
Same issue here with 10.3.

**Comment by wolviex** [comment]
I've tested the proposed fix from the certbot engineer and works good for me.
I've submitted a PR, but if you want to deploy/test it:
Docker Image for build 1 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as:  jc21/nginx-proxy-manager:github-pr-2971

**Comment by unixorn** [comment]
I was having the same issue with Route 53 and the `github-pr-2971` image fixed it.

**Comment by czernobogBlog** [comment]
`github-pr-2971` did not work for me.
I am using DNS challenge with Cloudflare. :(

**Comment by czernobogBlog** [comment]
I tried using `github-pr-2971` image but I am still getting error. Here's the certbot log: https://pastebin.com/raw/kxE0gpMq
I think it might be because too many retries. But I am trying this after 2 weeks.
Would appreciate if someone could help

**Comment by wolviex** [comment]
> I tried using `github-pr-2971` image but I am still getting error. Here's the certbot log: https://pastebin.com/raw/kxE0gpMq I think it might be because too many retries. But I am trying this after 2 weeks. Would appreciate if someone could help

Moved to #3003. Seems unrelated

**Comment by chief-nerd** [comment]
Same error here on GoDaddy Domain.
Version: v2.10.3

**Comment by kbftech** [comment]
Same. GoDaddy
`Error: Command failed: . /opt/certbot/bin/activate && pip install --no-cache-dir --user certbot-dns-godaddy~=0.2.0  && deactivate
ERROR: Will not install to the user site because it will lack sys.path precedence to urllib3 in /opt/certbot/lib/python3.7/site-packages

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)`

Not sure how relevant that is but I'm running "latest" image, fresh install.
`TARGETPLATFORM=linux/amd64 BUILD_VERSION=2.10.3 BUILD_COMMIT=824c837 BUILD_DATE=2023-05-10`

**Comment by wolviex** [comment]
> Not sure how relevant that is but I'm running "latest" image, fresh install. `TARGETPLATFORM=linux/amd64 

PR #2971 should fix this for you, instead of pulling :latest, try the pr fix.
``` jc21/nginx-proxy-manager:github-pr-2971 ```

**Comment by wolviex** [comment]
> For cloudflare, should I switch back to "lastest" or stay on that pr for the tme being?

I'd go back to the latest if it is functional for cloudflare.
If you get  ``` ERROR: Will not install to the user site ``` again, you can go back to the PR.

**Comment by snorkrat** [comment]
Yip - I was having this issue and` jc21/nginx-proxy-manager:github-pr-2971` has fixed it.  Hopefully we can get this merged into latest.

**Comment by geekyouth** [comment]
image: jc21/nginx-proxy-manager:2.10.2 # 2.10.3 不兼容 aws routes3

**Comment by cryptolukas** [comment]
Issue still exist for me with AWS Route53

**Comment by unixorn** [comment]
@cryptolukas use the `github-pr-2971` build, it works for me with R53.

**Comment by 21st-centuryman** [comment]
I am still having this issue with my raspberry pi. Could this be a separate issue with ARM machines?

**Comment by HughSparks** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

Still experiencing the same issue with the following traceback:

```
Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-19" --agree-tos --email "hugh@sparkspack.com" --domains "*.sparksfamily.net" --authenticator dns-godaddy --dns-godaddy-credentials "/etc/letsencrypt/credentials/credentials-19"
Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in 
    from certbot.main import main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 6, in 
    from certbot._internal import main as internal_main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 28, in 
    from certbot import crypto_util
  File "/opt/certbot/lib/python3.7/site-packages/certbot/crypto_util.py", line 42, in 
    from certbot import interfaces
  File "/opt/certbot/lib/python3.7/site-packages/certbot/interfaces.py", line 21, in 
    from acme.client import ClientBase
ImportError: cannot import name 'ClientBase' from 'acme.client' (/opt/certbot/lib/python3.7/site-packages/acme/client.py)

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket. (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe. (node:net:301:12)
```

**Comment by unixorn** [comment]
@21st-centuryman I'm running `github-pr-2971` on an Orange Pi 5, which is ARM.

**Comment by wolviex** [comment]
> Still experiencing the same issue with the following traceback:
> 

> ImportError: cannot import name 'ClientBase' from 'acme.client' (/opt/certbot/lib/python3.7/site-packages/acme/client.py)
> 

This is a different issue and not NPM specific, see comments from Jun 15 on #2844 for a workaround.

**Comment by Braedach** [comment]
Changed container to jc21/nginx-proxy-manager:github-pr-2971
Stop the associated container
Prune the containers
Leave the data volumes all alone - so I dont have to set it up again.
Start the container with docker-compose

Get the following warning - sorry mate - still got issues.

Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-14" --agree-tos --email "redacted" --domains "redacted,*.redacted" --authenticator dns-godaddy --dns-godaddy-credentials "/etc/letsencrypt/credentials/credentials-14" --dns-godaddy-propagation-seconds 600
Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in 
    from certbot.main import main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 6, in 
    from certbot._internal import main as internal_main
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 28, in 
    from certbot import crypto_util
  File "/opt/certbot/lib/python3.7/site-packages/certbot/crypto_util.py", line 42, in 
    from certbot import interfaces
  File "/opt/certbot/lib/python3.7/site-packages/certbot/interfaces.py", line 21, in 
    from acme.client import ClientBase
ImportError: cannot import name 'ClientBase' from 'acme.client' (/opt/certbot/lib/python3.7/site-packages/acme/client.py)

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

Thanks

**Comment by wolviex** [comment]
This issue was regarding user site installation and sys.path precedence.
The import error regarding acme/certbot version mismatches is a separate issue and not NPM specific, see comments from Jun 15 on #2844 for a workaround: My advice was to downgrade acme, not upgrade certbot:
```/opt/certbot/bin/pip install acme==1.32.0```

Also note the certbot-dns-goddaddy comment is a recently released version pinned at 2.6.0.
nginx-proxy-manager has version_requirement: '~=0.2.0' for this plugin so it's not relevant.
I suspect the resolution to your issue is a version bump for that but haven't looked into it.

**Comment by Braedach** [comment]
Joe,

Will destroy the container.  Start again and let you know.  I have
bookmarked the correct issue.

Thanks

**Comment by Leuconoe** [comment]
same issue in cloudflare, OCI DNS
