### ISSUE TITLE
Log Rotate Issue

### ISSUE THREAD

**Issue by blaine07** [NginxProxyManager/nginx-proxy-manager#2938]
Running Nginx Proxy Manager 2.10.3 on Unraid 6.11.5. Noticed today, when I looked at logs for NPM that there was a error about LogRotate command failing: 
![Screen Shot 2023-05-21 at 12 39 47 PM](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/63940698/88ecffec-a592-4cfd-aa97-494609cb6d6f)
which prompted me to see how much/many logs were being stored. Appears about ~600mb and back to March of last year:
![Screen Shot 2023-05-21 at 12 41 21 PM](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/63940698/94891c22-651b-4b2c-bd29-b6369e840ad3)
![Screen Shot 2023-05-21 at 12 42 58 PM](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/63940698/33f79438-86f9-4ea9-a1e2-74dca04fd8af)

Is there a way I can safely purge these excessive logs myself? Also, I do have PUID/PGID defined; could issue be relative to that perhaps?
![Screen Shot 2023-05-21 at 12 49 54 PM](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/63940698/ef3983a0-29cb-42fc-bbf5-e1d9d0b76fe4)

Any help would be appreciated - just unsure if I can purge old logs myself or not and or if it's a permission issue of sorts or what?

**Comment by jeremysherriff** [comment]
Yes you can purge the log files yourself.

I'm not familiar with how unraid works - looks like the chown failed when it was trying to set the log location to root:root. I think logrotate requires the files to be owned by root?

**Comment by masterwishx** [comment]
Have same issue on latest version in ubuntu by root user :  

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/28630321/d3051bbb-8f97-4cdb-84cb-63bc1363c4a5)
