### ISSUE TITLE
Can't use both Google Domains DNS and DuckDNS for SSL Certificates

### ISSUE THREAD

**Issue by isaaccase** [NginxProxyManager/nginx-proxy-manager#2994]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
tl;dr You can't install both certbot-dns-google-domains 0.1.11 and certbot-dns-duckdns 0.9 at the same time.

You can't use both GoogleDomainsDNS and DuckDNS at the same time. I originally set up certificates using duckdns, but then wanted to set up a personal personal domain so I purchased a domain using Google domains. Unfortunately you can't use both at the same time. certbot-dns-duckdns depends on zope.interface 5.4 and certbot-dns-google-domains depends on zope.interface 6.0 and they're incompatible. The error from pip looks like this:

Error: pip's dependency resolver does not currently take into account all the packages that are installed. This behavior is the source of the following dependency conflicts.
certbot-dns-duckdns 0.9 requires zope.interface~=5.4.0, but you have zope-interface 6.0 which is incompatible.

**Nginx Proxy Manager Version**
2.10.3

**To Reproduce**
1. Go to SSL Certificates
2. Click on Add
3. Add a ssl certificate for DuckDNS
4. Afterward, try to add another certificate for GoogleDomainsDNS

**Expected behavior**
You should be able to add SSL certificates for both domain providers

**Screenshots**

**Operating System**
This was hosted on Debian, but should not be dependent on host OS

**Additional context**
N/A

**Comment by isaaccase** [comment]
FYI, upgrading certbot-dns-duckdns to 1.3 seems to fix the conflict, but I don't know if it still works with any other certbot providers.

**Comment by sleao** [comment]
I actually struggled with this for so long until I finally found this issue. I had to bash into the docker and upgrade both certbot-dns-duckdns and zope.interface. This worked for me!

**Comment by isaaccase** [comment]
I'm not sure that's a good solution because after restarting I am no longer able to log into nginx proxy manager. It shows "bad gateway" when trying to log in.
