### ISSUE TITLE
Admin-Panel not showing up after successful start

### ISSUE THREAD

**Issue by RemoCharles** [NginxProxyManager/nginx-proxy-manager#2996]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
I'm trying to get started with nginx-proxy-manager. I'm running several docker-images in one single docker-compose file.
On startup (docker-compose up -d) everything works fine. All my other docker-images work on their port. Even the default screen shows up on localhost:81:

_Congratulations!

You've successfully started the Nginx Proxy Manager.

If you're seeing this site then you're trying to access a host that isn't set up yet.

Log in to the Admin panel to get started._

The Problem is. No Admin panel is showing up...

**Nginx Proxy Manager Version**
No Login-Page for me =(

**To Reproduce**
See docker-compose file in "additional context

**Expected behavior**
The Login-Page should be there by the get-go.

**Screenshots**
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/61230079/7d500057-3308-4f24-b5ae-755b59887d9d)
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/61230079/7d2f874a-3c59-4e30-a12b-302288f69661)

**Operating System**
Docker Host: Ubuntu 18.04
Docker Version 24.0.2
Docker Compose Version 1.25.5 

**Additional context**
[fallback_error.log](https://github.com/NginxProxyManager/nginx-proxy-manager/files/11726773/fallback_error.log)
[docker-compose.txt](https://github.com/NginxProxyManager/nginx-proxy-manager/files/11726834/docker-compose.txt)

**Comment by jrd2017** [comment]
Are you using port 81?  Port 80 is the frontpage

**Comment by RemoCharles** [comment]
@jrd2017 jup you nailed it. I always checked the icoming ports 80 and 81 and not the ones I port forward to...
Thanks
