### ISSUE TITLE
internal application redirection requests

### ISSUE THREAD

**Issue by Suryah07** [NginxProxyManager/nginx-proxy-manager#3008]
My domain is example.com and accessing my app through example.com/app1 and whenever I click on a link through my app it goes to the link example.com/login.html instead of example.com/app1/login.html.
Config :

location /app1/ {
rewrite /app1/(.*) /$1 break;
proxy_pass [http://192.168.x.x:80](http://192.168.x.x/);
}

**Comment by SignFinder** [comment]
What about this one?

location ~ ^/app1/ {
proxy_pass http://192.168.x.x;
}
