### ISSUE TITLE
Error 502 when chaining multiple NPMs

### ISSUE THREAD

**Issue by Fufs** [NginxProxyManager/nginx-proxy-manager#3023]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes / No / __With tag 2.10.3 which is the latest__
- Are you sure you're not using someone else's docker image?
  - __Yes__ / No
- Have you searched for similar issues (both open and closed)?
  - __Yes__ / No

**Describe the bug**
I have my network setup like below:
Client ==service.domain.tld==> NPM 1 ==service.local.domain.tld==> NPM 2 ==Docker network==> Service Container

Now, I can access my service through NPM 2 with service.local.domain.tld, however, when I try to do it through NPM 1 with service.domain.tld I get a "premature disconnection when reading response headers" or something like that. I had added the following custom configuration to my proxy host on NPM 1
```
proxy_ssl_name $server;
proxy_ssl_server_name on;
```

Before the change, it would through a ```unrecognized name:SSL alert number 112``` error, which I can replicate when I try to access port 443 of NPM 2 with just the ip of the docker host. Reading the documentation, adding ```proxy_ssl_server_name on;``` should've fixed the issue, however I'm getting the premature disconnects now. NPM 2 does not log anything at all when causing the premature disconnection (with log level set to debug). I have also tried messing with extending the timeouts to see if that was an issue but still no success.

**Nginx Proxy Manager Version**
 2.10.3

**To Reproduce**
1. Setup 2 chained NPM istances
2. Try to access the the service with SSL from the first proxy in the chain

**Expected behavior**

Service gets proxied

**Screenshots**

****NPM 1:****
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/42976807/8e34c10a-cad1-4b45-9ebe-f183f5e6be3a)
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/42976807/b69d3355-f75b-4786-b7a4-5a5eba4e8bad)
(HTTP/2 support on or off doesn't make a difference)
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/42976807/9bf8f79c-2312-4cf9-a437-1ca56e777336)

****NPM 2:****
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/42976807/fce1d474-18a1-4742-ac98-60bad02cba8c)
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/42976807/ada1f574-442f-4fa5-b29c-f85934a986f3)
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/42976807/de42d0fd-30b7-4e02-ac93-74a1705473bd)

**Operating System**
x86_64 Virtual machine with ubuntu server 22.04 LTS

**Additional context**

No custom configuration:
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/42976807/5883de70-6d8d-4cb8-9f73-d055ecb94509)

With
```
proxy_ssl_name $server;
proxy_ssl_server_name on;
```
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/42976807/716421bd-5cb3-4073-b9d0-92e0a2e9071c)

**Comment by Fufs** [comment]
Found the issue!

All posts I found suggested changing the Host header to $server instead of $host, however, as I found out you can't do this through the advanced configuration section of the UI. After manually changing the nginx config file, it works as intended.

So the steps to fix it
1. Locate configuration file in /path/to/data/nginx/proxy_host
2. Change This line under ```location / {``` from
```conf
# Proxy!
include conf.d/include/proxy.conf;
```
With
```conf
# Proxy!
add_header       X-Served-By $host;
proxy_set_header Host $server;
proxy_set_header X-Forwarded-Scheme $scheme;
proxy_set_header X-Forwarded-Proto  $scheme;
proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
proxy_set_header X-Real-IP          $remote_addr;
proxy_pass       $forward_scheme://$server:$port$request_uri;
```
The only line changed from https://github.com/NginxProxyManager/nginx-proxy-manager/blob/develop/docker/rootfs/etc/nginx/conf.d/include/proxy.conf is ```proxy_set_header Host $server```
3. Bash into the container and run ```/usr/sbin/nginx -s reload```
4. Exit everything and your done!

Going forwards, would it be possible to have a toggle for this in the UI? Or perhaps a "Custom Hosts" tab where one could define custom nginx configurations using a built-in text editor? I'll probaby create a future request for that, as it seems like a nice feature to have.

P.S. Shout out to this user for a good explanation https://serverfault.com/questions/837480/nginx-double-reverse-proxy#:~:text=I%20think%20you,proxy_set_header%20Host%20%24proxy_host%3B

**Comment by katosabi** [comment]
I encountered this issue as well, but followed this [Reddit comment](https://www.reddit.com/r/nginxproxymanager/comments/135trgt/ssl_handshake_error/) to add these two lines to the custom config:

```
proxy_ssl_name $host;
proxy_ssl_server_name on; 
```

I did see the [other Reddit thread](https://www.reddit.com/r/nginxproxymanager/comments/14k29ry/help_nginx_reverse_proxies_chaining/) where the same thing was suggested to you @Fufs; I'm not nginx savvy enough to explain why it works for me and not you😄. I'm only doing this for Emby and Joplin.

**Comment by Fufs** [comment]
If I remember correctly `proxy_ssl_name` is being set correctly by default. The problem was that NPM2 was closing the connection prematurely. That's because NPM1 was setting the `Host` header to the address of NPM1 and NPM2 would close the connection because it's not the header it was expecting. If both NPMs were "listening" for the same domain but an external DNS (say 1.1.1.1) was pointing at NPM1 and internal DNS (like PiHole) was pointing at NPM2, then it would work perfectly. But because I like to have separate domains for each machine (to make sure I'm targeting the correct one).

**Comment by turingking** [comment]
Now there is a better way:
Edit Proxy Host ->  Advanced -> Custom Nginx Configuration ->
```shell
proxy_ssl_server_name on;

location / {
    # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

    # Set headers for proxy
    add_header X-Served-By $host;
    proxy_set_header Host $server;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;

    # Upgrade connection to WebSocket if necessary
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;

    # Proxy configuration
    proxy_pass $forward_scheme://$server:$port$request_uri;
}

 ```
The above code will be inserted directly into server{...}

If you want to add `Custom locations`, do not use the GUI option
The above configuration code can be modified
```shell
proxy_ssl_server_name on;

location / {
    # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

    # Set headers for proxy
    add_header X-Served-By $host;
    proxy_set_header Host $server;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;

    # Upgrade connection to WebSocket if necessary
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;

    # Proxy configuration
    proxy_pass $forward_scheme://$server:$port$request_uri;
}

# Custom locations
location /home {
    # Modify to your own configuration
    set $home_forward_scheme  https;
    set $home_server         "com.example.com";
    set $home_port            443;

    # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

    # Set headers for proxy
    add_header X-Served-By $host;
    proxy_set_header Host $home_server;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP    $remote_addr;
  
    # Upgrade connection to WebSocket if necessary
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;

    # Proxy configuration
    proxy_pass $home_forward_scheme://$home_server:$home_port/;
    # proxy_pass $home_forward_scheme://$home_server:$home_port$request_uri;
}

```
Use `$home_forward_scheme://$home_server:$home_port$request_uri;` if you want to append the request's URI directly to the proxy target.

Use `$home_forward_scheme://$home_server:$home_port$/;` if you want to add an additional trailing slash at the end of the proxy target's URI.

Then you can access `https://xxx.com/home`

**Comment by turingking** [comment]
> 我也遇到了这个问题，但按照[Reddit 评论](https://www.reddit.com/r/nginxproxymanager/comments/135trgt/ssl_handshake_error/)将这两行添加到自定义配置中：
> 
> ```
> proxy_ssl_name $host;
> proxy_ssl_server_name on; 
> ```
> 
> 我确实看到了[其他 Reddit 帖子](https://www.reddit.com/r/nginxproxymanager/comments/14k29ry/help_nginx_reverse_proxies_chaining/)，其中向您建议了同样的事情@Fufs; 我对 nginx 的了解不够，无法解释为什么它对我有用，但对你不起作用。我这么做只是为了 Emby 和 Joplin。

please see above
