### ISSUE TITLE
TransIP DNS Challenge unrecognized arguments

### ISSUE THREAD

**Issue by jedikaal** [NginxProxyManager/nginx-proxy-manager#3139]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes, sort of. I used the latest version
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
When trying to Add an SSL Certificate trough DNS Challenge with my provider TransIP. `I get an error  unrecognized arguments:`. 

```
Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-8" --agree-tos --email "<my_emailaddress>" --domains "<subdomain.domain.tld>l" --authenticator dns-transip --dns-transip-credentials "/etc/letsencrypt/credentials/credentials-8"
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --dns-transip-credentials /etc/letsencrypt/credentials/credentials-8

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

**Nginx Proxy Manager Version**
v2.10.4 © 2023 jc21.com. Theme by Tabler

**To Reproduce**
I used these values:

Domain Names: <subdomain.domain.tld> _(There is an existing A-records to the IP where the server does the request)_
Email Address for Let's Encrypt: <my_emailaddress>
Use a DNS Challenge: True
DNS Provider: TransIP
Credentials File Content: 
```
dns_transip_username = <TransIP_username>
dns_transip_key_file = /etc/letsencrypt/transip-rsa.key
``` 
_(key pair generated and placed on the folder)_
I Agree to the Let's Encrypt Terms of Service: True

After pressing the button save I get the error stated above. 

**Expected behavior**
That the SSL cert has been made. 

**Screenshots**
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/69734830/e82c3a55-85ea-4cf1-84c6-f460c8b0276e)

**Operating System**
I have an LXC contain on Proxmox 7.4-15 with Debian 12.

**Comment by lukeart** [comment]
Did you resolve this issue, @jedikaal?
I ran into the same issue, but realized that a plugin was missing:

```
$ pip list | grep certbot
certbot                2.1.0
certbot-dns-cloudflare 2.0.0
certbot-dns-duckdns    1.3
certbot-dns-porkbun    0.8
```

After installing the plugin, everything worked like a charm.

```
$ pip install certbot-dns-transip
```

**Comment by jedikaal** [comment]
You've seem to have found the cause of my problem. 
Thank you for sharing. 
How did you came up to look for this?

**Comment by lukeart** [comment]
It was probably at [this threat over at letsencrypt](https://community.letsencrypt.org/t/the-requested-plugin-does-not-appear-to-be-installed/190632), where I learned each provider has its own plugin. Turned out TransIP was missing in the container and the rest was trivial.
