### ISSUE TITLE
about CORS setting

### ISSUE THREAD

**Issue by wleelw** [NginxProxyManager/nginx-proxy-manager#3141]
hello guys, I have encountered a tricky problem. I am building a cross domain request using nginxproxymanager, but it still cannot take effect. Below is a screenshot of me.

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/74389842/32502005-585b-4ef9-b90c-83d05ea1b5b9)
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/74389842/469e68e3-e8f0-488f-9996-6b735531d789)
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/74389842/bb0280f6-8249-43a7-962c-f13fca95d805)
Browser did not return request header, error CORS reported
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/74389842/804d7516-3057-4353-9ae6-74cdcd87b3ab)
Is there a good way to solve it?

**Comment by mebonline** [comment]
Use this 

add_header 'Access-Control-Allow-Origin' '*';
add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
add_header 'Access-Control-Allow-Headers' 'User-Agent,Keep-Alive,Content-Type';
add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';

**Comment by wleelw** [comment]
thanks

> Use this
> 
> add_header 'Access-Control-Allow-Origin' '*'; add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS'; add_header 'Access-Control-Allow-Headers' 'User-Agent,Keep-Alive,Content-Type'; add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
