### ISSUE TITLE
Ways to move letsencrypt storage to /data volume

### ISSUE THREAD

**Issue by iBobik** [NginxProxyManager/nginx-proxy-manager#3170]
Hello, I create addon for Home Assistant OS which are just Docker image with some integration around.

For it I need to have all persistent data stored only in /data, other volumes will not survive recreate.

But there is an issue with /etc/letsencrypt - it is volume, so I cannot create symlink for it in my image (using your image as base).

**Describe the solution you'd like**
I would like to remove /etc/letsencrypt from VOLUME in the Dockerfile.
https://github.com/NginxProxyManager/nginx-proxy-manager/blob/fa851b61da3fe3726d1a04c25e69d36e79edea2d/docker/Dockerfile#L54

Or have the directory configurable, but this seems more work.

**Describe alternatives you've considered**
There is option to not use this image as a base, but copy&paste its content to my Dockerfile, but this will be maintenance hell.

Thank you for help. I can do PR if you confirm the solution.

**Comment by iBobik** [comment]
@jc21 are you ok with it? Can I prepare PR?

**Comment by jc21** [comment]
It should be ok, since all the documentation says that users should mount this folder. The only time it might cause issues is if someone doesn't mount it and then upgrades to a new image where the volume will not be used and their certs will be gone. Might need to be a minor release required for this change.

**Comment by iBobik** [comment]
> It should be ok, since all the documentation says that users should mount this folder. The only time it might cause issues is if someone doesn't mount it and then upgrades to a new image where the volume will not be used and their certs will be gone. Might need to be a minor release required for this change.

Thank you for reply. Would you mind checking my PR https://github.com/NginxProxyManager/nginx-proxy-manager/pull/3258?
