### ISSUE TITLE
Docker compose build is stuck on setting ownership

### ISSUE THREAD

**Issue by xfy777** [NginxProxyManager/nginx-proxy-manager#3177]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**
The docker image is stuck on setting ownership when starting.

**Nginx Proxy Manager Version**

Login does not start.

**To Reproduce**
1. Run docker-compose file.
2. Watch build
3. Start containers
4. Stuck on 
```
app_1  | ❯ Configuring npm user ...
app_1  | ❯ Configuring npm group ...
app_1  | ❯ Checking paths ...
app_1  | ❯ Setting ownership ...
```

**Expected behavior**
I would expect it to start normally.

**Operating System**
Ubuntu 22.04

**Comment by arsa-dev** [comment]
what was the problem last time @xfy777 ? I'm facing the same issue on kubernetes

**Comment by xfy777** [comment]
@arsa-dev  Chmod777 everything in the directory and essentially just gotta wait it out!

**Comment by electronick86** [comment]
same problem for me

**Comment by TheSlowGrowth** [comment]
Here's a solution for people running slow HDD pools on TrueNAS Scale:
https://github.com/truenas/charts/issues/1212
It worked for me. I'm leaving it here because this issue is a top hit on google.

**Comment by blind-coder** [comment]
> Here's a solution for people running slow HDD pools on TrueNAS Scale: https://github.com/truenas/charts/issues/1212 It worked for me. I'm leaving it here because this issue is a top hit on google.

That issue no longer exists, unfortunately. Do you remember what the solution is? Stuck on the same issue.

**Comment by TheSlowGrowth** [comment]
I have since moved on to an SSD pool on my truenas box and I removed the fix from my config.
But I remember that the solution was to add an environment varible that modified the startup sequence.
[This sounds vaguely familiar](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3154#issuecomment-2336556125), but I can't remember if it was the actual solution:
> Workaround add an Additional Environment Variable on Truenas 24.10-Beta.1:
S6_STAGE2_HOOK=sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh

Give it a try, and please report back for the next person that runs into this. @KSEGIT and @KoesterD liked my comment, so maybe they still have that bit of config in their deployment and can help out?

**Comment by KoesterD** [comment]
> Workaround add an Additional Environment Variable on Truenas 24.10-Beta.1:
> S6_STAGE2_HOOK=sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh

Yes, this fixed the issue for me. My config looks like this in TrueNAS:

![Image](https://github.com/user-attachments/assets/b404e56e-8a49-4b4b-8055-c36ec68dfbe9)

@blind-coder

**Comment by blind-coder** [comment]
> > Workaround add an Additional Environment Variable on Truenas 24.10-Beta.1:
> > S6_STAGE2_HOOK=sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh
> 
> Give it a try, and please report back for the next person that runs into this.

Yes, that worked for me, thank you very much!

**Comment by Sawtaytoes** [comment]
> > > Workaround add an Additional Environment Variable on Truenas 24.10-Beta.1:
> > > S6_STAGE2_HOOK=sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh
> > 
> > 
> > Give it a try, and please report back for the next person that runs into this.
> 
> Yes, that worked for me, thank you very much!

I was about to use your fix, and my container started up on its own. I use TrueNAS SCALE on a 2 SSD mirror with Electric Eel. I was seeing the container stuck here, but after a bit, it finally started on its own.

**Comment by Potterfanz** [comment]
I used the solution mentioned by someone else in [this](https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3154) issue thread, to set User ID and Group ID to 0 when installing, and that fixed it for me.

**Comment by dedebenui** [comment]
I tried the env variable fix but it doesn't work. It no longer gets stuck on the `Setting ownership`, but it errors out afterwards and doesn't start at all:
```
/etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh: line 60: syntax error: unexpected end of file
```

This is still a bug unfortunately, and I'm stuck waiting ages for the container to start after each update.

**Comment by blind-coder** [comment]
> I tried the env variable fix but it doesn't work. It no longer gets stuck on the `Setting ownership`, but it errors out afterwards and doesn't start at all:
> 
> ```
> /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh: line 60: syntax error: unexpected end of file
> ```
> 
> This is still a bug unfortunately, and I'm stuck waiting ages for the container to start after each update.

I've since moved to a plain dockerfile setup. This has the advantage that IPv6 also works correctly. Move TrueNAS https from 443 to 444 and http from 80 to 82 first.

```yaml
services:
  app:
    environment:
      DB_SQLITE_FILE: /data/database.sqlite
    image: jc21/nginx-proxy-manager:latest
    network_mode: host
    ports:
      - '80:80'
      - '82:81'
      - '443:443'
    restart: unless-stopped
    volumes:
      - /mnt/data/npm/data:/data
      - /mnt/data/npm/letsencrypt:/etc/letsencrypt
x-portals:
  - host: 192.168.2.10
    name: Web UI
    path: /
    port: 82
    scheme: http
```
