### ISSUE TITLE
proxy_pass in custom nginx config

### ISSUE THREAD

**Issue by DCRalph** [NginxProxyManager/nginx-proxy-manager#3197]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**

I have a pihole server which is accessed on http://<ip>/admin and in the past with plain nginx I have used proxy_pass to make it froward to /admin. When put proxy pass in to the custom nginx config field the status goes offline. 

**Nginx Proxy Manager Version**

v2.10.4

**To Reproduce**
1. Go to Proxy hosts
2. Edit or create a proxy
3. go to advanced
4. add "proxy_pass http://127.0.0.1:8888;" or somthing similar to custom nginx configuration

**Expected behavior**

"domain.com" to froward to http://<ip>/admin

**Screenshots**

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/43304937/80fd2816-9bf4-411b-9413-45e02f480eb5)
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/43304937/d8bd5fc3-41ca-4a5f-bffc-4e17f1e2f84c)

**Operating System**

ubuntu-23.04-standard_23.04-1 lcx container on proxmox

**Additional context**

**Comment by edsonsbj** [comment]
I already had a similar error and my solution was to add a custom location
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/60072822/037cade4-58e7-4e65-9c93-616498225c6e)

**Comment by DCRalph** [comment]
I have figured it out for anyone wanting to know.
Simply add the path after the ip in the custom locations tab.
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/43304937/f0008d21-691e-49cb-8fcf-dd75e410acaa)
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/43304937/e07dcc7e-db64-44e8-bc4e-f1ed1c1ecca4)
