### ISSUE TITLE
X509_V_FLAG_CB_ISSUER_CHECK

### ISSUE THREAD

**Issue by kaasszje** [NginxProxyManager/nginx-proxy-manager#3206]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes (was running 2.9.19 before)
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

**Nginx Proxy Manager Version**
When I start the docker image, or when I try to create a new certificate or renew an existing certificate.
I see the following error: 
npm  | [9/20/2023] [8:56:26 AM] [SSL      ] › ✖  error     Error: Command failed: certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --preferred-challenges "dns,http" --disable-hook-validation
npm  | Traceback (most recent call last):
npm  |   File "/usr/bin/certbot", line 5, in <module>
npm  |     from certbot.main import main
npm  |   File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 6, in <module>
npm  |     from certbot._internal import main as internal_main
npm  |   File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 21, in <module>
npm  |     import josepy as jose
npm  |   File "/opt/certbot/lib/python3.7/site-packages/josepy/__init__.py", line 40, in <module>
npm  |     from josepy.json_util import (
npm  |   File "/opt/certbot/lib/python3.7/site-packages/josepy/json_util.py", line 14, in <module>
npm  |     from OpenSSL import crypto
npm  |   File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
npm  |     from OpenSSL import crypto, SSL
npm  |   File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1517, in <module>
npm  |     class X509StoreFlags(object):
npm  |   File "/opt/certbot/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1537, in X509StoreFlags
npm  |     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
npm  | AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
npm  |
npm  |     at ChildProcess.exithandler (node:child_process:402:12)
npm  |     at ChildProcess.emit (node:events:513:28)
npm  |     at maybeClose (node:internal/child_process:1100:16)
npm  |     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)

I use transip as hosting provider which is supported.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Operating System**

**Additional context**

My npm is working, but I'm unable to create or renew certificates.

**Comment by kaasszje** [comment]
Tried the PR but regretfully still gives the same error
I'll try to debug it a bit further

**Comment by kaasszje** [comment]
To add I use a dns challenge and not the local challenge for this request.
(Using wildcard certs)

**Comment by ErikNoort** [comment]
I am also using the Transip API to add a CNAME to validate the request.
I am using host certificates, not wildcard certs.

**Comment by ErikNoort** [comment]
don't know why exactly, but this seems to have fixed the issue:
rm -rf /opt/certbot/lib/python3.7/site-packages/OpenSSL/
pip3 install pyOpenSSL --ignore-installed

apparently there are some conflicts in the installed openssl package.

**Comment by kaasszje** [comment]
Yep that seems to fix it :)

**Comment by KRGT-NL** [comment]
Same, suggestion is working.

**Comment by BlessedDisco** [comment]
It seems to me this problem is fixed in v2.11.1. After updating, I have no problems renewing my certificate

**Comment by KRGT-NL** [comment]
> It seems to me this problem is fixed in v2.11.1. After updating, I have no problems renewing my certificate

I do feel the same and have the same outcome, so looks solved now.

**Comment by kaasszje** [comment]
Same hetr
