### ISSUE TITLE
data.domain_names should NOT have more than 15 items << Multi Domain SAN Certs Limit

### ISSUE THREAD

**Issue by abdulfahad661** [NginxProxyManager/nginx-proxy-manager#3218]
**Is your feature request related to a problem? Please describe.**
Its not a problem looks like but a limit that should be increased i suggest, we use Route 53 and Cloud Flare and we have normal request of SAN for 30 to 40 sites at a time and looks there is limit set by developers in this NPM which can be great if increased.

<img width="194" alt="15 Items limits in domian names" src="https://github.com/NginxProxyManager/nginx-proxy-manager/assets/136641221/7407edfd-1d31-4dbb-b4ee-f898a3cdbfbd">

**Describe the solution you'd like**
Increase limit to like upto 50 for SAN sites (multiple domains at once)
Looks its been controlled at NginxProxyManager/nginx-proxy-manager/blob/develop/frontend/js/app/nginx/certificates/form.js
Line 268 >>             maxOptions:   15,
If that can be increased so that can be increased as i guess (i have no dev experience)

<img width="438" alt="max options" src="https://github.com/NginxProxyManager/nginx-proxy-manager/assets/136641221/74a69fd8-a756-4d0e-92fb-56acdae45fc7">

**Describe alternatives you've considered**
We do this by right now on linux using command below and it works for more that 15 domains(we have to enter DNS challenge for each item) :
certbot-2 certonly --email email@email.com  -d agent.ha.domain.com -d auth.ha.domain.com -d billing.ha.domain.com -d bots.ha.domain.com -d cm.ha.domain.com -d docs.ha.domain.com -d eps.ha.domain.com -d onboarding.ha.domain.com -d recordings.ha.domain.com -d reports.ha.domain.com -d security.ha.domain.com -d smgr.ha.domain.com -d wfm.ha.domain.com -d wizard.ha.domain.com -d www.ha.domain.com --agree-tos --manual --preferred-challenges dns
 

**Additional context**
This NPM is great and this limit increase can make life more easy :)

**Comment by Shocktrooper** [comment]
I just ran into this.  Unless there is a limitation on nginx or lets encrypt this field should reflect how many you can actually fit in a cert or nginx

**Comment by abdulfahad661** [comment]
Yes I hope that NPM devs can assist on enhancing this limits

**Comment by Shocktrooper** [comment]
If someone can point me to the code that needs to be changed I could handle this myself, or someone else if they get to it first

**Comment by abdulfahad661** [comment]
> If someone can point me to the code that needs to be changed I could handle this myself, or someone else if they get to it first

(https://github.com/NginxProxyManager/nginx-proxy-manager/tree/develop/frontend/js/app/nginx/certificates)
/form.js
Line 268 @Shocktrooper

**Comment by r3na** [comment]
NGINX and Letsencrypt both support quite a large number of domain names, so 15 as a limit is definitely not ideal?

**Nginx**:
- https://nginx.org/en/docs/http/server_names.html
- https://nginx.org/en/docs/http/ngx_http_core_module.html#server_names_hash_max_size

**Letsencrypt**:
> `A single Let’s Encrypt certificate can include up to 100 SAN names. Names can be single-name, wildcard names, or both.`
- https://support.dnsimple.com/articles/letsencrypt/#lets-encrypt-highlights

**Comment by r3na** [comment]
@abdulfahad661 @Shocktrooper  + others:

I wrote a step-by-step quick hotfix for anyone who needs to fix this problem (tested with [2.10.4](https://github.com/NginxProxyManager/nginx-proxy-manager/releases/tag/v2.10.4)):

1. you should get into the Docker Container
```console
docker ps
docker exec -it <my container id> bash
````

2. you should replace the 4 occurrences of `maxOptions: 15` with  `maxOptions: 30` and also replace the schema `maxItems: 15`  with `maxItems: 30`.

```console
grep -Ril "\"maxItems\": 15" /app/
grep -Ril "maxOptions:15" /app/
sed -i 's/maxOptions:15/maxOptions:30/g' /app/frontend/js/*.js
sed -i 's/\"maxItems\": 15/\"maxItems\": 30/g' /app/schema/definitions.json
grep -Ril "maxOptions:30" /app/
grep -Ril "\"maxItems\": 30" /app/
```

3.  you should commit the changes (to the app) and keep changes as in the docker image:
` docker commit <my container id> jc21/nginx-proxy-manager:latest`

4. bring the app down and up.

**Comment by abdulfahad661** [comment]
@r3na  thanks bro it works modified files in the docker container.. committed.. and then restarted container the limit is removed .. thanks again for assist

**Comment by abdulfahad661** [comment]
issue fixed as fix suggested by @r3na
