### ISSUE TITLE
Vultr - APIv2

### ISSUE THREAD

**Issue by arturswi** [NginxProxyManager/nginx-proxy-manager#3234]
**What provider would you like to see added to NPM?**
VULTR

**Have you checked if a certbot plugin exists?**
Failed to add TXT record for "my-domain": Error fetching DNS domains list: 503 - Sorry, all newly created accounts are forbidden from using API v1, all other accounts are able to use this deprecated API until September 30, 2023 at which point Vultr API v1 will be sunset. Please use API v2.
More info: https://www.vultr.com/docs/vultr-api-v1-to-v2-transition-strategies/

**Comment by JBM1866** [comment]
This is also occurring on several instances that I run.
Needs to support the new V2 API for Vultr or a LOT of certifications are going to expire.

**Comment by Everglase** [comment]
This is also a issue for me as well as I have quite a number of certificates that are expiring and I can not renew them because of the API v2 not being implemented.

**Comment by clord** [comment]
All of my lab systems are down because of this.

**Comment by arturswi** [comment]
my workaround

**Comment by clord** [comment]
https://github.com/lezgomatt/certbot-dns-vultr is updated to work with the v2 api and that work is released, so I believe the only thing required is to bump the version in https://github.com/NginxProxyManager/nginx-proxy-manager

**Comment by Everglase** [comment]
> my workaround
> 
> #download certbot for vultr with api v2 support `curl https://raw.githubusercontent.com/lezgomatt/certbot-dns-vultr/master/certbot_dns_vultr.py > /root/certbot_dns_vultr.py` #move old file as a backup `mv /opt/certbot/lib/python3.7/site-packages/certbot_dns_vultr.py /opt/certbot/lib/python3.7/site-packages/certbot_dns_vultr.py.bak` #replace old file new file `mv /root/certbot_dns_vultr.py /opt/certbot/lib/python3.7/site-packages/certbot_dns_vultr.py `

@arturswi I can't seem to find that "certbot_dns_vultr.py" file in that directory on in my docker container.

Any hints as to where it hides in the docker?

**Comment by phauxcamus** [comment]
Another workaround until the container is updated is to use pip to upgrade, then restart the container:

```bash
docker exec -it nginx-proxy-manager "pip install --upgrade certbot certbot-dns-vultr"
docker restart nginx-proxy-manager
```

**Comment by mstummer** [comment]
Thanks so much for posting the workaround, that got my domains going again:

- first did the pip install as suggested above
- then ran into the issue "Can't create table 'npm'.'migrations" described here and followed workaround there: https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1499
- then couldn't renew the certificates, but deleting them and issuing new ones worked. ("The requested certbot-dns-vultr:dns-vultr plugin does not appear to be installed")
