### ISSUE TITLE
Add an option to reject or drop a request with an unknown host

### ISSUE THREAD

**Issue by ondrejnedoma** [NginxProxyManager/nginx-proxy-manager#3246]
**Is your feature request related to a problem? Please describe.**

This is a security concern of mine, where if someone opens ANY domain pointing to my IP address with an A record, or the IP address itself, it would at best throw a 404 page if I set that up in the settings, and at worst show the congrats page.

**Describe the solution you'd like**

It would be a great feature if besides choosing congrats page, 404 page, redirection, or custom page, I could also choose to reject or drop the request entirely, giving the attacker a lot less hope.

**Describe alternatives you've considered**

**Additional context**

**Comment by FibreTTP** [comment]
This is was already implemented in https://github.com/NginxProxyManager/nginx-proxy-manager/pull/2942:
![firefox_2tUvsQ0ozu](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/120446961/cec391dd-a185-421d-8753-96b5459543e7)

https://nginx.org/en/docs/http/request_processing.html#how_to_prevent_undefined_server_names
