### ISSUE TITLE
Sign in Button Fails After Upgrade to v2.10.4

### ISSUE THREAD

**Issue by jwebbstevens** [NginxProxyManager/nginx-proxy-manager#3313]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
Upgraded to[ v2.10.4](https://github.com/NginxProxyManager/nginx-proxy-manager/releases/tag/v2.10.4) went to sign in and the Sign in button just clicks and no action follows. 

**Nginx Proxy Manager Version**
[v2.10.4](https://github.com/NginxProxyManager/nginx-proxy-manager/releases/tag/v2.10.4)
via docker [jc21/nginx-proxy-manager](https://registry.hub.docker.com/r/jc21/nginx-proxy-manager/)

**To Reproduce**
1. Go to local ip address of Nginx Proxy Manager Web UI
2. Click on email and password and enter information
3. Scroll down to Sign in and click
4. Nothing happens
5. Proxy is still running can navigate to any of my established routes using the common name.
6. Checked Env variable requirements many times to make sure MariaDB is working too.

**Expected behavior**
Expectation is that I clear the signin page and get taken to the Web UI Homepage of my instance of Nginx Proxy Manager

**Screenshots**
![Nginx-Proxy-Manager Login Screen](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/7277574/22fdfb1c-e23e-4757-b68a-1c293a37a28a)

**Operating System**
Synology NAS Running[ DSM 7.2-64570](https://archive.synology.com/download/Os/DSM/7.2-64570-1)
[Container Manager](https://www.synology.com/en-global/dsm/feature/container-manager)/Docker

**Additional context**
Tried Chrome (latest), Safari (Latest), Firefox (Latest). Turned off all firewalls local and otherwise.

**Comment by ethayer** [comment]
I also had this issue.  Moving the DB folder up one level out of "data" fixed it for me.

Solution: 
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3237

**Comment by jwebbstevens** [comment]
Ah thanks.  I ended up to just rebuilding the entire thing from scratch though with the latest version and then moved the DB folder as reference in #3237 . Probably for the best because my sites needed to be reconfigured anyhow.
