### ISSUE TITLE
Proxy streams not working

### ISSUE THREAD

**Issue by agi-dude** [NginxProxyManager/nginx-proxy-manager#3315]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
I have created a proxy stream to forward all traffic from port 3000 to another host, but so far I am unable to access the host.

**Nginx Proxy Manager Version**
v2.10.4

**To Reproduce**
1. Not really sure?

**Expected behavior**
I would have wanted it to forward traffic

**Screenshots**
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/102142660/d055fe14-ffbf-4c6d-bdc5-c9245e6acab0)

**Operating System**
I am using a Ubuntu machine running Portainer

**Additional context**
I have another proxy stream on port 5223, and that is working.
I also have checked that:

- I am able to connect to the server directly
- The port 3000 is open in the docker compose file
- Port 3000 is forwarded in my router\
- I am able to nmap onto port 3000 on the NGINX proxy manager and it shows that the port is open.

**Comment by rookiecloud2023** [comment]
I have similar problem. I have already updated the compose yml file to include the stream port. The TCP port is working fine but the UDP port seems not Listening.

**Comment by nickvin** [comment]
@rookiecloud2023 for UDP, you apparently need to append "/udp" in the ports section of the compose file.
(i.e. 5867:5867/udp)

Saw this [here](https://www.reddit.com/r/nginxproxymanager/comments/13h4sx3/comment/jl8gddw/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button), but haven't tested myself.
