### ISSUE TITLE
I have a problem when creating an access list.

### ISSUE THREAD

**Issue by donrichys** [NginxProxyManager/nginx-proxy-manager#3370]
Hi, I've been reading and researching about this error for a couple of days, I've tried different ways and the error continues, in other projects I've run this and it has worked without problems.

I have followed the documentation as usual, and it gives me error, I have tried with mariabd and sqlite and nothing.

Manual URL:
https://nginxproxymanager.com/setup/#running-the-app

It has been tested in different browsers: Firefox, Chromiun

When I try to create an access rule, it remains blank and if I save it, it gives me an error, as shown in the screenshots.

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/153031878/b599f521-5b9c-406b-9417-cadb36414c40)

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/153031878/2ca3f6f2-adf7-49be-b336-2a0dfdc1882e)

My docker configuration is as follows:

```sh
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```
I hope you can help me.
Best regards

**Comment by the1ts** [comment]
I have seen this myself when I had a browser extension blocking the update. Perhaps try an incognito login then turn off the offending extension for that url.

**Comment by donrichys** [comment]
Hi, I just tried it and nothing, I have tried incognito and still the same, I even restarted the browser and nothing :(
