### ISSUE TITLE
When I create ssl, I get an error message

### ISSUE THREAD

**Issue by HKTY569** [NginxProxyManager/nginx-proxy-manager#3393]
`Error: Command failed: . /opt/certbot/bin/activate && pip install --no-cache-dir certbot-dns-aliyun~=0.38.1  && deactivate
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-aliyun/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-aliyun/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-aliyun/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-aliyun/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/certbot-dns-aliyun/
ERROR: Could not find a version that satisfies the requirement certbot-dns-aliyun~=0.38.1 (from versions: none)
ERROR: No matching distribution found for certbot-dns-aliyun~=0.38.1

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)`

I installed it through docker, with the default configuration file and no other options set. What is the reason?
![微信图片_20231217212836](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/35788811/48c7c9e1-e819-487e-aecf-c8bab462db83)

**Comment by itollei** [comment]
the same error!!

**Comment by jc21** [comment]
This is a network connectivity issue between your docker container and the outside world. v0.38.1 definitely does exist:
https://pypi.org/project/certbot-dns-aliyun/#history
and I can install it just fine.

**Comment by HKTY569** [comment]
> 同样的错误！！

Just isolate nginx-proxy-manager from other containers by creating new Networks.

**Comment by HKTY569** [comment]
> 这是您的 docker 容器与外界之间的网络连接问题。v0.38.1 确实存在： https: [//pypi.org/project/certbot-dns-aliyun/#history](https://pypi.org/project/certbot-dns-aliyun/#history) 我可以很好地安装它。

Ok thanks I solved the problem by creating new Networks

**Comment by hds1992012011** [comment]
> > > 这是您的 docker 容器与外界之间的网络连接问题。v0.38.1 确实存在： https: [//pypi.org/project/certbot-dns-aliyun/#history](https://pypi.org/project/certbot-dns-aliyun/#history) 我可以很好地安装它。
> > 
> > 
> > 好的，谢谢，我通过创建新的网络解决了这个问题。
> > @HKTY569 我也遇到了，你能解释一下怎么解决吗？

mark

**Comment by M-Nemo** [comment]
> > 这是您的 docker 容器与外界之间的网络连接问题。v0.38.1 确实存在： https: [//pypi.org/project/certbot-dns-aliyun/#history](https://pypi.org/project/certbot-dns-aliyun/#history) 我可以很好地安装它。
> 
> Ok thanks I solved the problem by creating new Networks

same problem when i use cloudflare token, it might be a dns problem ,i tried to creat a new bridge network, but it didn't work.
用cloudflare token去做SSL认证的时候也遇到了差不多的问题，然后检查了半天发现是docker内无法解析域名，IP直接访问是正常的，创建新网络也没有解决问题。
