### ISSUE TITLE
"Cannot Load Certificate Error" From Deleting Certificate (HELP)

### ISSUE THREAD

**Issue by jHat0421** [NginxProxyManager/nginx-proxy-manager#3420]
So I've been running Nginx on a Unraid server, and I had deleted a certificate in the webUI in hopes of fixing an issue before that I had, but ran into newer issues with the webUI now being unresponsive. Checking the log will state: 
```
"Starting nginx ...
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/npm-18/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/npm-18/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)"
<REPEAT>
```
and typing in nginx -t will produce a similar error: 
```
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/npm-18/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/npm-18/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed
```
I've read about copying an existing cert in either live or archive folders contained in the "letsencrypt" folder. Unfortunately, both are empty and I have no idea how to continue. Any help would be much appreciated.

**Comment by jonfriesen** [comment]
I'm also experiencing this issue. I had a DNS challenge cert that I deleted and now NPM won't come back up after the latest restart:

```
[1;34m❯ [1;36mStarting nginx ...[0m
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/npm-2/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:
```

I'm running as a container on truenas scale

**Comment by tutunciyan** [comment]
Same issue here. Fixed by reverting back to an backup, but this is not always option.

**Comment by flygav1** [comment]
I have had this issue as well... it requires making a whole new proxmox lvm everytime :( very sad.

**Comment by jHat0421** [comment]
I FIGURED IT OUT! This is what I did for Unraid. First thing that I did was remove the Nginx docker container, but without removing the image. Then I moved the two files that was contained in my volume mapping mnt/user/appdata/Nginx-Proxy-Manager (I think regularly is just in /data/nginx. The two files are named data and letsencrypt. I had moved them outside of my mnt (I think just in a backup folder in root), and reinstalled the docker container. The docker container created those two files again, and you'll have to go through the process of setting up as if it were first time.

**Comment by flygav1** [comment]
ahh so you didnt create or have a separate valuem for nginx reverse proxy?

**Comment by rcdailey** [comment]
I resolved the issue by deleting the `1.conf` file under `nginx/proxy_host`

**Comment by ma-lalonde** [comment]
I had the same issue: `nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/npm-11/fullchain.pem"`

I used the following command to find the hosts referrigng to this certificate: `sudo grep -Rnw . -e 'npm-11'` (replace `.` by the path to your `data` folder)

Then deleted the culprit identified by the previous command: `sudo rm data/nginx/proxy_host/7.conf`

I could then log into the Nginx Proxy Manager interface and re-configure the missing certificates.

**Comment by mhos** [comment]
We have a client using NPM for hundreds of domains and one issue we just found out was that using the API call to just delete the SSL certs that are expired or domains that are expired keep the SSL config details in the configs thus causing nginx errors during startup. I feel like if the API DELETE is used for the SSL certs that some checks need to be in place to remove the cruft within the proxy config to prevent these errors.
I am no expert with NPM but one way we were able to recover from complete catastrophe for hundreds of domains was by doing the following:
Log into the NPM docker.
Create a generic SelfSigned SSL cert:
``openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout privkey.pem -out fullchain.pem``
Then use this script to copy that new ssl into the missing paths:

```
#!/bin/bash

# Created by: Casey O'Connor
# Date: 08/27/2024
# Description: Scans the /var/log/nginx/error.log for missing ssl certs. Creates the missing cert directory and copies in SelfSigned Cert to get Nginx loading again.
# This script will run until it finds no more.
# Usage: You need to change this part /CHANGE/ME/TO/PATH/TO/ to the actual path of the new SelfSigned Cert you created with this command:
#        openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout privkey.pem -out fullchain.pem

fix_certs() {
    # Run nginx -t and capture the output
    nginx_output=$(nginx -t 2>&1)

    # Function to extract directory names from nginx output
    extract_dirs() {
        echo "$nginx_output" | grep -oP '(?<=/etc/letsencrypt/live/)[^/]+(?=/fullchain\.pem)'
    }

    # Extract missing directory names
    missing_dirs=$(extract_dirs)

    # Check if any missing directories were found
    if [ -z "$missing_dirs" ]; then
        echo "No missing directories found."
        return 1
    fi

    # Process each missing directory
    echo "$missing_dirs" | while read -r dir; do
        echo "Processing directory: $dir"

        # Create the missing directory
        mkdir -p "/etc/letsencrypt/live/$dir"

        # Copy the certificate files
        cp "/CHANGE/ME/TO/PATH/TO/privkey.pem" "/etc/letsencrypt/live/$dir/"
        cp "/CHANGE/ME/TO/PATH/TO/fullchain.pem" "/etc/letsencrypt/live/$dir/"

        echo "Created directory and copied files for $dir"
    done

    return 0
}

# Main loop
iterations=0
while true; do
    iterations=$((iterations + 1))
    echo "Iteration $iterations"

    if ! fix_certs; then
        echo "No more missing folders found. Exiting."
        break
    fi

    echo "Completed iteration $iterations. Checking again..."
    echo
done

echo "Script completed after $iterations iteration(s). Please run nginx -t to verify."

```
This is not the most elegant way to do it but what worked for us in a pinch.
Please share and or improve as you see fit.

**Comment by a-crazy-pencil** [comment]
do ```sudo rm data/nginx/proxy_host/*.conf``` that should work
