### ISSUE TITLE
[Question] When adding a proxy host - where does it create the config file?

### ISSUE THREAD

**Issue by paulb39** [NginxProxyManager/nginx-proxy-manager#3452]
Apologies, googling like crazy but can't find the answer. When you make a proxy host record via the UI - where does it create that config file? I did a grep find on all files in /etc/nginx but no file contains my domain

**Comment by paulb39** [comment]
I can't be the only one with this question. I am trying to diagnose items I added to advanced configuration, but I really need to see how the config file looks

**Comment by paulb39** [comment]
Finally found it : /data/nginx/proxy_host 
can we please add this to the docs somewhere?

**Comment by paulb39** [comment]
Well now I have a new problem- the UI will overwrite my changes. I want the advanced config to go under location /, no server, not sure how to do that

**Comment by jc21** [comment]
If you enter the `/` location inside the advanced config, the auto generation will detect that and won't generate it for you. Keep in mind that if you do specify your own `/` location, you'll have to include some/all of the following in order to get the proxy. Here's an example you can paste it directly into the advanced config:

```
location / {
  add_header       X-Served-By $host;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-Scheme $scheme;
  proxy_set_header X-Forwarded-Proto  $scheme;
  proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
  proxy_set_header X-Real-IP          $remote_addr;
  proxy_pass       $forward_scheme://$server:$port$request_uri;
}
```

**Comment by paulb39** [comment]
Much appreciated - worked as expected
