### ISSUE TITLE
Whenever a kubernetes pod reboots npm can't seem to resolve the host to the new cluster IP

### ISSUE THREAD

**Issue by cyberpower678** [NginxProxyManager/nginx-proxy-manager#3492]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
For some strange reason, if I were to reboot a pod that is a proxy target for npm, the host to that pod will no longer resolve, or remain stuck on the old pod IP, resulting in the browser eventually returning a 502.  If I ran a curl request from within the npm pod to the proxy target pod, it will resolve the host just fine and retrieve page just fine, yet the reverse proxy will persistently log errors regarding not being able to resolve the host.

Once I reboot npm, it will begin to forward just fine again.

**Nginx Proxy Manager Version**
2.10.4

**To Reproduce**
1. Install an application on TrueNAS
2. Install npm on TrueNAS
3. Set up a proxy host to the application
4. Restart the application
5. NPM will no longer forward to the application until it's restarted

**Expected behavior**

The DNS should not be getting stuck after initially resolving the host

**Screenshots**

**Operating System**

TrueNAS SCALE/Debian

**Additional context**

**Comment by dasunsrule32** [comment]
I can't reproduce this myself. Are you using the community train or the docker image itself deployed as a custom app?

**Comment by cyberpower678** [comment]
Oh sorry, I forgot to close this when I figured out what was actually going wrong.  No problems to report.
