### ISSUE TITLE
 如何http自动重定向到https How to automatically redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by javazwz123** [NginxProxyManager/nginx-proxy-manager#3509]
When entering my own webpage, always add an HTTPS prefix before the network address. If it is the default HTTP, the error "400 Bad Request, The plain HTTP request was sent to HTTPS port" will appear

server {
    listen 80;
    server_name jiyik.com www.jiyik.com;
    return 301 https://jiyik.com$request_uri;
}
There is nginx code online that can redirect HTTPS via HTTP. How can I use it on npm? Thank you

**Comment by endless1651** [comment]
user redirection with 307 temporary redirect

**Comment by endless1651** [comment]
use force ssl

**Comment by javazwz123** [comment]
> use force ssl
Solved, thank you. Home network, port 80 443 is closed and has no effect. In the advanced settings, add this string of code and it will work
error_page 497 https://$http_host$request_uri;
