### ISSUE TITLE
I Hope to add a function to reload the nginx configuration file on the page

### ISSUE THREAD

**Issue by jinlin-teck** [NginxProxyManager/nginx-proxy-manager#3528]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jinlin-teck** [comment]
Sometimes the container IP changes and I have to reload nginx. Then I have to log in to the container shell to execute "nginx -s reload", which is troublesome. I hope to add this button to the web page.
Thanks！

**Comment by daedric7** [comment]
> Sometimes the container IP changes and I have to reload nginx. Then I have to log in to the container shell to execute "nginx -s reload", which is troublesome. I hope to add this button to the web page. Thanks！

If you go into NPM WebUI, open any entry to edit, and just save, this causes a nginx reload
