### ISSUE TITLE
Cannot access admin interface on v2.11.1 (502 Gateway Error)

### ISSUE THREAD

**Issue by krosseyed** [NginxProxyManager/nginx-proxy-manager#3585]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
I cannot log into the admin interface after deploying a fresh v2.11.1 container on a Mikrotik CHR on AWS using a t3.micro.

**To Reproduce**
1. [Setup container support](https://help.mikrotik.com/docs/display/ROS/Container) and [enable device-mode on AWS](https://forum.mikrotik.com/viewtopic.php?p=1058637#p1058637) for Mikrotik CHR
2. [Create config.json](https://old.reddit.com/r/nginx/comments/pt352s/bad_gateway_on_login/hdvucab/) and move it to /npm on CHR
3. Install container using the following config

```
/interface/veth
add name=veth1 address=172.17.0.2/24 gateway=172.17.0.1

/interface/bridge
add name=docker

/ip/address
add address=172.17.0.1/24 interface=docker

/interface/bridge/port 
add bridge=docker interface=veth1
/ip/firewall/nat/add chain=srcnat action=masquerade src-address=172.17.0.0/24 

/container envs
add key=DB_SQLITE_FILE name=npm_envs value=/data/database.sqlite
add key=DEBUG name=npm_envs value=true

/container mounts
add dst=/data name=/npm/data src=/npm/data
add dst=/etc/letsencrypt name=/npm/letsencrypt src=/npm/letsencrypt
add dst=/app/config/production.json name=/npm/config.json src=/npm/config.json

/container
add envlist=npm_envs interface=veth1 logging=yes mounts=/npm/data,/npm/letsencrypt,/npm/config.json root-dir=/npm/root start-on-boot=yes workdir=/app
```
4. Remove /etc/nginx/conf.d/dev.conf by going into the container and deleting it
```
/container shell 0
rm /etc/nginx/conf.d/dev.conf
```
5. Shutdown and Startup the container and wait about 10 minutes to start up. Then access via http://<IP_OF_AWS_INSTANCE>:81 using the default admin credentials

**Expected behavior**
To be able to log into the admin console. Not get a 502/Bad Gateway error

**Screenshots**
<img width="750" alt="Screenshot 2024-02-25 at 11 25 16 PM" src="https://github.com/NginxProxyManager/nginx-proxy-manager/assets/6548354/7ac65663-3ffd-49ee-96cd-affad049e1b7">

**Operating System**
Mikrotik CHR v7.12.1 using the container application provided by Mikrotik

**Additional context**

I am getting in my logs the following output:
`Using Sqlite: /data/database.sqlite
`

I know Mikrotik's RouterOS is not a popular platform, but it would be nice to have this configuration to run NPM documented somewhere so people who want to run this on RouterOS can do so. The newer hardware is definitely equivalent or faster than a RaspberryPi and has more networking capabilities than most computing platforms.

**Comment by SaschMie** [comment]
Same here, the new update broke npm. Login is broken and dns challenge errors all time.

**Comment by krosseyed** [comment]
There was another issue I discovered and it was related to how much RAM I allowed the VM to use. I am going to close this ticket for now as I am no longer trying to use NginxProxyManager for my homelab needs.

**Comment by krosseyed** [comment]
Just an update, ran this same setup on a brand new CRS2116 and it works fine. It was the RAM limit that got me on this bug.
