### ISSUE TITLE
The 'certbot_dns_dnspod.dns_dnspod' plugin errored while loading: No module named 'zope'. You may need to remove or update this plugin. The Certbot log will contain the full error details and this should be reported to the plugin developer.

### ISSUE THREAD

**Issue by 3222368840** [NginxProxyManager/nginx-proxy-manager#3593]
添加ssl证书时，遇到这个错误：

**Comment by 3222368840** [comment]
The 'certbot_dns_dnspod.dns_dnspod' plugin errored while loading: No module named 'zope'. You may need to remove or update this plugin. The Certbot log will contain the full error details and this should be reported to the plugin developer.

**Comment by BigDaBoluo** [comment]
python3 -m pip install --upgrade pip
pip install certbot-dns-dnspod
pip install zope
进入容器，试试这个吧
