### ISSUE TITLE
docker应该使用host网络，并且提供更改端口号

### ISSUE THREAD

**Issue by GuoYuefei** [NginxProxyManager/nginx-proxy-manager#3605]
使用上面没有啥问题，并且Let's Encrypt也挺好用。但是！docker中为什么使用网桥模式，nginx可是要代理主机网络的，其他那是不是意味着，每代理一个，都需要一个端口映射！
程序本身应该还要提供一个更改端口的配置文件，我查看了源码，没有配置的地方，仿佛就是使用了初始的80、443

**Comment by jetamie** [comment]
说明你对compose不熟悉，用什么网络是你自己决定的，yml自己配置，而且就算用网桥模式也没啥关系，网桥模式是可以通过内网IP访问的

**Comment by jetamie** [comment]
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/46777058/d0586cf4-1c17-481e-8e59-11f82b76d737)

**Comment by jetamie** [comment]
compose网络模式设置：network_mode : host

**Comment by jetamie** [comment]
端口问题：也是可以通过compose配置的，百度下 compose使用把

**Comment by GuoYuefei** [comment]
主要一旦使用了host模式，就要占用宿主机的80端口，我查看了源码，没有看到有修改服务端口的地方。然后如果用网桥模式，多服务的情况下，要添加十几个端口映射，然后大部份端口都用了各服务初始端口，也就是不连贯性。
其实提供一个环境变量或者配置文件，配置运行端口+我自己改成host模式就能解决

**Comment by GuoYuefei** [comment]
> If the services were in docker, you could use something like [registrator](https://github.com/gliderlabs/registrator) and consul to automate the port setup.如果服务在 docker 中，您可以使用 registrator 和 consul 之类的东西来自动设置端口。

Thank you for your help~
