### ISSUE TITLE
Thoughts on Freenginx

### ISSUE THREAD

**Issue by Pyroseza** [NginxProxyManager/nginx-proxy-manager#3629]
I noticed this link today and the content is quite eye opening: https://www.infoq.com/news/2024/03/freenginx-ngnix-web-server/

It talks about security concerns with F5 and I was wondering if you’d consider adopting the new fork to embrace a more safer and secure path forward which sticks with the original intentions of Nginx

As of now the source code is not available in GitHub but in Hg (Mercurial), I’m keeping an eye on it to see if there will be a container image or not to simplify things.

Code: http://freenginx.org/hg/nginx

**Comment by Pyroseza** [comment]
I found this unofficial mirror: https://github.com/freenginx-mirror/nginx

**Comment by JBlond** [comment]
Be aware that this project uses OpenResty, not nginx.

**Comment by Pyroseza** [comment]
> Be aware that this project uses OpenResty, not nginx.

The name threw me off 😅
