### ISSUE TITLE
Can't login anymore.

### ISSUE THREAD

**Issue by tkbstudios** [NginxProxyManager/nginx-proxy-manager#3681]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
When pressing the login button, I am welcomed with this very satisfying error message:  
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

**Nginx Proxy Manager Version**

**To Reproduce**
1. Input your credentials
2. press log in

**Expected behavior**
It should log me in like it did before

**Screenshots**
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/69647028/2793b296-8be6-48e1-8450-6add8e17065f)

**Operating System**
Ubuntu 22.04 LTS Pro

**Additional context**
Docker version: `Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1`
Browser: `Firefox 124.0.2 (64-bit) - Up To Date`
Last time I logged in was 4 days ago I think.

**Comment by tkbstudios** [comment]
This issue is somehow fixed and I didn't do nothing??

**Comment by thebino** [comment]
Have you checked the docker logs? There might be any hint as to why the backend service can't start properly. That's why this error appears most likely.

**Comment by tkbstudios** [comment]
I noticed that nginx proxy manager requires port 3000, which was in use by another service, I changed the port of the other service and now it works.
