### ISSUE TITLE
NPM passes through some requests even though 444 option is set

### ISSUE THREAD

**Issue by ericswpark** [NginxProxyManager/nginx-proxy-manager#3704]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

When running NPM with the default page option set to 444 (No Response), some requests still make it to proxied hosts, causing errors because the wrong `HTTP_HOST` is set (the server IP instead of the proxy hostname).

**Nginx Proxy Manager Version**

v2.11.1

**To Reproduce**
1. Set up a proxy host
2. Set default server behavior to 444
3. Send requests to the server IP

**Expected behavior**

None of the requests should make it through to the proxied host

**Additional context**

This issue appears to be sporadic as I'm unable to reproduce it on-demand. However, I get errors from the proxied app behind NPM, telling me that requests are coming through with the `HTTP_HOST` header set to the server's IP address instead of the correct hostname I set while setting up the proxy host in NPM.

**Comment by h4de5** [comment]
are those requests maybe related to static assets like .jpg, .css, .js or .woff files?

if so, there is a location rule in a include/assets.conf that takes precedence here.

**Comment by ericswpark** [comment]
@h4de5 nope, root (`/`) with no files.

**Comment by ericswpark** [comment]
This occurred due to a Docker Compose misconfiguration; not an NPM issue. Sorry!
