### ISSUE TITLE
NPM Broken? Bad underlying tool sets?

### ISSUE THREAD

**Issue by sdh91** [NginxProxyManager/nginx-proxy-manager#3763]
It appears that NPM is broken as a whole. I was on 2.10.3 and have been running it for a while with nearly no issues. My certificates stopped renewing. I have tried everything from upgrading to doing a full new instance and still cannot get certificates to be issued. Even with DNS challenge with Cloudflare. I'm not sure what is going on but as a whole this project appears to be broken and no one seems to be getting any real information. Work arounds are not working in my case.

Can we please get some sort of update on this? What has happened that has caused this to break? I feel this is more of a certbot issue but not sure if I'm being honest.

**Comment by jc21** [comment]
No NPM is not broken, however as you've probably determined, the certbot for cloudflare was.

As you were using a NPM version over a year old, there have been significant upgrades to certbot since then. The CI tests that it can install the plugins but it doesn't test each one, it's just not feasible.

Please try using the `github-develop` docker image tag to get the fix from the PR, at least until `2.11.3` is released. Then feel free to close this issue if it works for you.

**Comment by sdh91** [comment]
I wasn't using DNS API validation. I have used HTTP validation for as long as I've used NPM. I did try it as a testing function, but that was it. 

I stayed on a version that was working. Didn't see any reason to move as there wasn't a compelling reason to upgrade. I had been burned before by upgrading and then losing all my configuration.

I'm not the only one that has suddenly had thier certificates stop renewing. Attempt to manually renew and the only message is "Internal Error". That is vague and not helpful to anyone.

**Comment by sdh91** [comment]
I believe my issue was compounded by a semi-recent LE change with Multi-Perceptual validation. I urge anyone that may be implementing a geo-block on their firewall to confirm if this is making it worse for them. While I did upgrade to the latest version my success with renewing was sporadic. I could renew a single cert, then not renew others. After finding this post, https://community.letsencrypt.org/t/unexpected-renewal-failures-since-april-2024-please-read-this/216830, I realized that my geo-block that I use to protect myself, may be interfering. This was indeed a cause of the rest of the sporadic issues it seems. I am closing my issue at this time.
