### ISSUE TITLE
DNS challenge with Dreamhost

### ISSUE THREAD

**Issue by lfdmn** [NginxProxyManager/nginx-proxy-manager#3801]
**Is your feature request related to a problem? Please describe.**
DreamHost DNS challenge required for wildcard certificates.

**Describe the solution you'd like**
DreamHost provides a [DNS API](https://help.dreamhost.com/hc/en-us/articles/217555707-DNS-API-commands)

There is a Python module here https://github.com/goncalo-leal/certbot-dns-dreamhost/.

I would appreciate some help or guidance how to add this and prepare a PR.

**Comment by lfdmn** [comment]
I found a built-in way to do it:
- DNS Provider: DnsMulti
- Credentials File Content
  ```
  dns_multi_provider = dreamhost
  DREAMHOST_API_KEY = ABCDEFG1234
  ```
- Propagation Seconds `120`

**Comment by richardwonka** [comment]
I cannot find DnsMulti in the list in a current install of the homeassistant NPM Add-On - what am I missing?

**Comment by nyshocka** [comment]
I am getting the error: ERROR: Could not find a version that satisfies the requirement certbot-dns-multi~=4.9 (from versions: none)

Anyone come across this when using DnsMulti and Dreamhost.

**Comment by nyshocka** [comment]
> I cannot find DnsMulti in the list in a current install of the homeassistant NPM Add-On - what am I missing?

I had to update my NPM for DnsMulti to show up. Still not working as noted above.
