### ISSUE TITLE
SSL Handshake Error

### ISSUE THREAD

**Issue by Nu11ified** [NginxProxyManager/nginx-proxy-manager#3826]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes 
- Are you sure you're not using someone else's docker image?
  - Yes 
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**

I have setup a SSL Certificate for my domain with my API Key from cloudflare for the DNS Challenge. 

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/86795298/e05f0e0c-cd34-4f41-8151-da3ca176469b)

I have also setup a proxy for the NPM itself to run on a proxy. This is set with the same SSL Certificate I have setup above.

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/86795298/3ec1c447-7947-48ab-8cf3-329d34b83c79)

But when I try to access the proxy link I get this error: 

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/86795298/d2bdc943-823a-4924-91ab-c9904113a071)

For noting sake I have completely reset my docker engine instance multiple times, tried every single option in the SSL Encryption Mode, made sure the subdomain was spelt correctly, and checked IP the DNS points too in cloudflare. I also had to go into the bash to reinstall the pip cloudflare as something in the latest version caused it to break. After fixing that I am still getting these issues. 

**Nginx Proxy Manager Version**

v2.11.2 

**To Reproduce**
1. Create SSL Certificate with Cloudflare DNS Challenge
2. Create a proxy for the NPM itself 
3. Set DNS of Subdomain towards Server IP
4. Get the stupid error 525

**Expected behavior**

The NPM should be accessible through the subdomain. 

**Screenshots**

Given above.

**Operating System**

Ubuntu 24.04

**Additional context**

**Comment by ransbachm** [comment]
You may wanna disable the cloudflare proxy and then access the website directly. This will likely also throw an error (if cloudflare says the handshake failed, your browser will probably too). You can then check for ssl errors yourself from this window.

That will at least give you more information to work from.

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/122271989/07d3cc8c-e5d4-4ba6-aef7-9829d4326da7)


![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/122271989/608a4fa5-01a6-4b5d-87c7-22ed6dc083e8)
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/122271989/d8dea567-7f86-4203-86f9-586e6e1ef92a)

**Comment by volodymyrmorozz** [comment]
i have the same issue from yesterday and i cand find a solution, 100+ domains affected, help me plz

**Comment by SiskoUrso** [comment]
@Nu11ified  Did you ever find a solution to this one? Noticed having this same issue with newly created proxy hosts.

**Comment by Nu11ified** [comment]
> @Nu11ified Did you ever find a solution to this one? Noticed having this same issue with newly created proxy hosts.
> 
> **Update: after posting this I noticed that there was an updated that addressed this and updated to v2.11.3 and its working again.

Honestly this unreliability was a huge red flag I just switched to using Traefik and that has worked great so far.

**Comment by Nu11ified** [comment]
Issue seems to be fixed in v2.11.3 as stated by another person above...
