### ISSUE TITLE
nginx: [emerg] bind() to 0.0.0.0:3478 failed (98: Address already in use)

### ISSUE THREAD

**Issue by leon1995** [NginxProxyManager/nginx-proxy-manager#3859]
**Describe the bug**
I added a stream from port 3478 to 3478, then I restarted the docker container and now I cannot start it, because I am getting errors
```
app         | nginx: [emerg] bind() to 0.0.0.0:3478 failed (98: Address already in use)
app         | nginx: [emerg] bind() to 0.0.0.0:3478 failed (98: Address already in use)
app         | nginx: [emerg] bind() to 0.0.0.0:3478 failed (98: Address already in use)
app         | nginx: [emerg] bind() to 0.0.0.0:3478 failed (98: Address already in use)
app         | nginx: [emerg] bind() to 0.0.0.0:3478 failed (98: Address already in use)
app         | nginx: [emerg] still could not bind()
```
Is there a way to remove the stream mapping manually?

**Comment by leon1995** [comment]
I was able to fix this, by first removing the stream config `rm data/nginx/stream/<problematic_config>`. Then I was able to start the docker and deleted the stream from the webinterface

**Comment by Benzeel** [comment]
thank you so much, this helped fix my issue
