### ISSUE TITLE
Not change version in frontend

### ISSUE THREAD

**Issue by sias32** [NginxProxyManager/nginx-proxy-manager#3869]
In the new version 2.11.3, going into the panel will show the old version

![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/109104432/f99e03cb-e9b0-4c2e-af09-f0a135579b17)

**Comment by mykorea0330** [comment]
could u check one more update
my server apply correct version

**Comment by sias32** [comment]
The data must have been cached, opening via incognito displays correctly
