### ISSUE TITLE
NPM giving me a headache

### ISSUE THREAD

**Issue by kosymodo** [NginxProxyManager/nginx-proxy-manager#3901]
I have Nginx Proxy Manager running on a Pi via Portainer. I'm having issues whereby I can access all my proxy hosts using their internal IP addresses (e.g. 192.168.1.200:81 for NPM itself), but can't access them via their FQDNs (e.g. nginx.DOMAIN.co.uk for NPM)

NPM has been running fine for months now, this has happened out of the blue. If I ping nginx.DOMAIN.co.uk I get no errors. I have a static IP.

Any ideas what I could try in order to troubleshoot what's happening?

**Comment by kosymodo** [comment]
> maybe allow the web socket option for the domain

That doesn't change anything unfortunately

**Comment by kosymodo** [comment]
> that's weird so any errors in NPM itself via the GUI if you press the link? any docker errors? can you share the logs please

Sorry, just checking - which link are you referring to?

The logs from Portainer for the NPM container?

**Comment by kosymodo** [comment]
I've now figured out what was causing the issue - somehow, when last updating the container, the ports seem to have defaulted.  I have custom port forwarding on my router, and therefore this is where everything was failing.  Now that I have set the ports to the correct values, everything is back working :)

**Comment by jackdeep89** [comment]
> I've now figured out what was causing the issue - somehow, when last updating the container, the ports seem to have defaulted. I have custom port forwarding on my router, and therefore this is where everything was failing. Now that I have set the ports to the correct values, everything is back working :)

I've the exact same issue, how do you fix it btw?
which port defaulted?

**Comment by beardcodes** [comment]
If it is using an automation for the container to be updated, then it needs to be looked at. 
Like for example the watch tower updates containers automatically, make sure you go through the compose your self.

**Comment by kosymodo** [comment]
> > I've now figured out what was causing the issue - somehow, when last updating the container, the ports seem to have defaulted. I have custom port forwarding on my router, and therefore this is where everything was failing. Now that I have set the ports to the correct values, everything is back working :)
> 
> I've the exact same issue, how do you fix it btw? which port defaulted?

For me, all ports had defaulted...I had to therefore ensure that the ports specified in my port forwarding on my router were replicated in the ports configured in Portainer

Router
![image](https://github.com/user-attachments/assets/c63ad731-526e-42c0-832f-6bc6fc1273df)

Portainer
![NPM ports Portainer](https://github.com/user-attachments/assets/ba1afb64-544e-47d8-818c-4de67c21f10a)

**Comment by alangrainger** [comment]
@kosymodo could you close this issue since it isn't an issue?
