### ISSUE TITLE
How to redirect FROM a subfolder to a backend service

### ISSUE THREAD

**Issue by Chaxiraxi** [NginxProxyManager/nginx-proxy-manager#3950]
I don't understand how custom locations work. I want to redirect as follows:
admin.example.com/phpmyadmin/ -> http://phpmyadmin:80/
admin.example.com/pihole/ -> http://pihole:80/admin/

The custom locations seems to be able to redirect only from subdomains to subfolders, but not the opposite...

**Comment by jannismilz** [comment]
Hey @Chaxiraxi 

So what do you mean with "redirect"?
I assume it's not a redirect host but you rather want to "redirect the traffic" to these addresses, right?

If yes, the first one is pretty easy.
For the second you most likely need some custom nginx config code to redirect to a specific path on the destination as well.

**Comment by Chaxiraxi** [comment]
I meant forward the request actually yup, sorry for the confusion. But I can't really understand the interface. I expect the configuration to work in the screenshot, but I get a ERR_SSL_UNRECOGNIZED_NAME_ALERT error in HTTPS, or a 404 openresty error via HTTP...
![image](https://github.com/user-attachments/assets/46123834-bac1-402b-ae25-82b66c737dd8)

**Comment by jannismilz** [comment]
Okay I understand.

That doesn't work like that. Have you already defined something for `admin.example.com` itself?
Because what you need to do is go to "Custom locations" and add it there like the following:
![Screenshot 2024-08-23 at 17 54 36](https://github.com/user-attachments/assets/c3d9efe5-5311-4b57-ab55-cf9af54bbc3f)

**Comment by Chaxiraxi** [comment]
Understood, but filling the "Details" tab is mandatory, and I don't want that the base domain itself forwards to anything.
I tried the following:
![image](https://github.com/user-attachments/assets/7d4a8a49-26d7-4c8b-a0ab-b3c174109f43)
![image](https://github.com/user-attachments/assets/3c49f7d2-e9cc-48c9-8385-107a6333090c)

But when I try to access my admin panel I get an ERR_SSL_UNRECOGNIZED_NAME_ALERT via https
![image](https://github.com/user-attachments/assets/db7c1b85-ed44-4b96-a968-09018c793677)

And via HTTP I get this on the base domain: 
![image](https://github.com/user-attachments/assets/11a0d253-352d-41c9-99d6-f62303ec1884)

and a 404 on the /phpmyadmin location:
![image](https://github.com/user-attachments/assets/5ac5e74c-20a5-45cf-811c-301b0e885401)

**Comment by Chaxiraxi** [comment]
Oh well... This [Reddit post](https://www.reddit.com/r/nginxproxymanager/comments/pnec6x/comment/henl8vx/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) answered my question I guess... Nginx Proxy Manger doesn't have the feature by default for this very specific, yet common and useful case. I'll come back to the good old manual Nginx configuration then I guess.
