### ISSUE TITLE
Not sure if this is NPM issue or not....

### ISSUE THREAD

**Issue by ccheath** [NginxProxyManager/nginx-proxy-manager#3992]
I setup NPM following [this video](https://www.youtube.com/watch?v=qlcVx-k-02E) "Quick and Easy Local SSL Certificates for Your Homelab!" 
Only difference is that I have my own domain (not duckdns) and have it's DNS controlled by Cloudflare.
(which he shows very briefly as an alternative to duckdns)

Everything went smooth, but at the end all my services loaded in http not https.
I double-checked everything that I could think of and everything was set correctly.
Then I began to get "site can't be reached" ERR_CONNECTION_REFUSED browser messages.

I've removed all the proxies and tried to create them again but no matter what I do they all give that same ERR_CONNECTION_REFUSED message.

I can't see any errors in the docker container logs for NPM, and I'm a bit lost here... can anyone suggest some things to troubleshoot? 

TYIA

**Comment by ccheath** [comment]
update: after sleeping on this and checking again today my services are again reachable, but again are also not secured http (not https)...

how can i troubleshoot this?

**Comment by ccheath** [comment]
well.... and again it's gone back to "site can't be reached" ERR_CONNECTION_REFUSED
this time I've done nothing to the NPM config (haven't touched it since yesterday)
just browsed to three a few login pages then went to eat dinner and after coming back to check nothing's loading

**Comment by cjboyle** [comment]
@ccheath We may need more info on the applications you have set up, browser messages aren't terribly helpful...

On that video around 3:18, he set **scheme=https** and **port=80**, which is incorrect and may cause issues as :80 is reserved for HTTP, not HTTPS.

It obviously depends on which ports your apps are exposing (and which protocol each is using), but make sure the scheme field is correct. For example, for Jellyfin's default ports, you might use **one** of (but not both):
* scheme=http, port=8096  (this is what I proxy in NPM)
* scheme=https, port=8920  (I don't proxy this as it requires a separate app-local certificate)

**Comment by ccheath** [comment]
@cjboyle thanks for the reply... I was able to get it to work yesterday by putting the IP (local/internal) address in NPM instead of the container name like he did in the video.

I also left NPM only accessible on the lan and only exposed my other services via NPM.

again, thanks
