### ISSUE TITLE
Porkbun API Change

### ISSUE THREAD

**Issue by armin771** [NginxProxyManager/nginx-proxy-manager#4061]
I just received an email from porkbun saying that they are changing their hostname for the API.
It may be important for the dns challenge provider function in the SSL Certificates menu.

```
CRITICAL UPDATE DETAILS

Type: API Hostname Change

Old Value: porkbun.com

New Value: api.porkbun.com

Deadline: 2024-12-01 00:00:00 UTC
```

**Comment by swipesomething** [comment]
I also received this email and it seems my certificate won't update anymore as a result of this change
