### ISSUE TITLE
Strange errors in UI on 2.12..0 

### ISSUE THREAD

**Issue by itsbhanusharma** [NginxProxyManager/nginx-proxy-manager#4074]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
I'm receiving strange message "data/value must match exactly one schema in oneOf" across the UI on many pages. 

**Nginx Proxy Manager Version**
v2.12.0

**To Reproduce**
1. Go to 'Hosts > Redirection Hosts'
2. Click on 'Add redirection Host' and leave the scheme to 'Auto'
3. Fill in the values for 'domain names' and 'forward domain'
4. Click Save
5. See error
![image](https://github.com/user-attachments/assets/db8ac06f-39d9-4803-a093-5bca6491e7b3)

Another area where this error Persists is 'settings > default site'
1. Edit 'default site'
2. Try selecting '404 Page' or 'No Response (444)' 
3. Click Save
![image](https://github.com/user-attachments/assets/7620d068-8466-46a3-8293-06fae8148c61)

**Expected behavior**
Options should behave as expected.

**Screenshots**
Screenshots attached below repro steps. 

**Operating System**

**Additional context**
N/A

**Comment by spearox** [comment]
Same for me with default site.
![image](https://github.com/user-attachments/assets/c1aa67bf-f121-4924-bee8-9a0fe4b8c617)

**Comment by CRASH-Tech** [comment]
+1
