### ISSUE TITLE
Cannot specify a port when configuring a new proxy host in the domain name with 2.12.1

### ISSUE THREAD

**Issue by codethought** [NginxProxyManager/nginx-proxy-manager#4090]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes 

**Describe the bug**

With version 2.12.1 the ability to specify a port in the domain name when adding a new proxy host now generates an error where it did not in 2.11.3. See attached screen shots.. If this is not a bug I would like to know how to accomplish this same thing now with newer versions. Thanks.

**Nginx Proxy Manager Version**

2.12.1

**To Reproduce**
1. Go to Hosts | Proxy Host
2. Click on 'Add Proxy Host'
3. Try to add a host with a port in the domain name

**Expected behavior**

I would expect to be able to enter a port with the domain name

**Screenshots**

**Operating System**

Docker within Unraid (Linux)

**Additional context**

<img width="1180" alt="version-2-11 3" src="https://github.com/user-attachments/assets/7603472e-e425-45bc-96fb-dd920939e140">

<img width="497" alt="version-2-12-1" src="https://github.com/user-attachments/assets/0192774d-2302-4418-86db-74082e8fc15d">

**Comment by yiqian987** [comment]
The same problem happened to me

**Comment by codethought** [comment]
I figured out why.. this isn't a bug.. we're leveraging the proxy manager wrong... so we are in the wrong.. not NPM


In NGINX itself, If you need to set up a proxy configuration in NGINX where requests to the same `server_name` are forwarded to different destination ports based on the incoming port, you can do this by setting up multiple server blocks, each with a different `listen` port, and then using the `proxy_pass` directive to specify the backend (destination) port. For example:



```
# Incoming on port 80, proxy to port 8080
server {
    listen 80;
    server_name derp.domain;
    
    location / {
        proxy_pass http://127.0.0.1:8080;
        # Additional proxy configurations (e.g., headers, buffering)
    }
}

# Incoming on port 1234, proxy to port 9090
server {
    listen 1234;
    server_name derp.domain;
    
    location / {
        proxy_pass http://127.0.0.1:9090;
        # Additional proxy configurations
    }
}
```

Eventually NGINX will disable the ability to do it 'wrong' aka `derp.domain:1337`

And we will have to use the advanced configuration section to set up multiple `proxy_pass` configurations.
