### ISSUE TITLE
http2 deprecated,

### ISSUE THREAD

**Issue by play113** [NginxProxyManager/nginx-proxy-manager#4132]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /data/nginx/proxy_host/14.conf:19

**Nginx Proxy Manager Version**

2.12.1

**Operating System**

Debian 12 / Docker 27.2.0

**Additional context**

switch from

    listen      X.X.X.X:443 ssl http2;

to

    listen      X.X.X:X:443 ssl;
    http2  on;

**Comment by snordmann** [comment]
The fix is already implemented and merged into the develop branch (and will thus be part of the next release). Related PR: #4106

**Comment by play113** [comment]
THX
