### ISSUE TITLE
IONOS certificate doesn't work

### ISSUE THREAD

**Issue by jclsn** [NginxProxyManager/nginx-proxy-manager#4183]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes
  
**Describe the bug**
The IONOS certificate is obtained using the DNS challenge, but the domain does still not use this certificate. 

I am a bit frustrated by now, because I don't know what I am doing wrong. From what I understand a TXT record needs to be created for this to work, but I haven't seen one. Maybe I am mistaken and the TXT record is only present during the creation of the certifcate. In any case, the certificate is not used, although the domain name certainly points to my server wheere NPM is running.

**Nginx Proxy Manager Version**
v2.12.1

**To Reproduce**
1. Go to SSL Certificates and click on "Add SSL Certificates"
2. Select IONOS DNS challenge and enter your API credentials
3. Create the certificate and add it to your proxy host
4. The domain uses another certificate

**Expected behavior**
The domain should use the certificate created with certbot.

**Comment by rezzorix** [comment]
IONOS works. You also do not need to create a txt record.
I assume you use the German IONOS - in any case US, Spanish or German.. all same process.

In the IONOS Api-Portal you get a Prefix and an API key.. this is all you need to create a DNS record in NPM.

When setting up the SSL Certs, choose DNS-Challenge choose IONOS and enter this:
dns_ionos_prefix = myapikeyprefix
dns_ionos_secret = verysecureapikeysecret
dns_ionos_endpoint = https://api.hosting.ionos.com

**Comment by jclsn** [comment]
Yeah, that part also works for me. I am now thinking that something does not work with the proxy. The certificates from Letsencrypt are not the ones I am getting when I am trying to access the domain. There are also no access logs on the proxies.

**Comment by rezzorix** [comment]
Nothing suspicious in the logs. Certs are created.

**Comment by jclsn** [comment]
Did I maybe misconfigure something on IONOS then? I deleted everything but the A and AAAA records

![grafik](https://github.com/user-attachments/assets/b00a398f-7a8b-4da7-b7ce-7c4c6f2c466f)

**Comment by rezzorix** [comment]
Seems right... maybe IP not up-to-date?
Port forwarding in Router not correctly set to the server where NPM is on?

**Comment by jclsn** [comment]
IP is up-to-date and the ports forwarding is also working. I have everything as I had it with my Strato domain before. I just changed the domain provider now. One difference is that with Strato I used ``ddclient``  and now I am using the router's DynDNS function.

I can even use the domain for SSH connections. It is just that the proxy is somehow showing me the wrong certificate. One that is valid for 10 years or so and self-signed.

**Comment by rezzorix** [comment]
DNS propagation already correct? 
https://www.whatsmydns.net/

**Comment by jclsn** [comment]
Yes, all check marks are there. I don't think the DNS is the issue here. Maybe NPM is not serving port 80, but then it would complain wouldn't it?

I am updating my IP with the IONOS API. This is what NPM is doing.

**Comment by rezzorix** [comment]
NPM is updating your Certs via DNS-Challenge. 
NPM is not updating your IP.

**Comment by jclsn** [comment]
I know. The IP is fine like I said. 

The problem is that the wrong certificate is used when I am accessing the server.

**Comment by rezzorix** [comment]
Would you mind sharing domain / ip with me? You could do via email rezzorix [at] gmail dot com

**Comment by jclsn** [comment]
Thanks, sent you a mail

**Comment by rezzorix** [comment]
Answered.

**Comment by Stephan-4711** [comment]
Can I add my question here?
I have a IONOS problem too.
I used the tteck script to install nginx it worked until one of the last updates of nginx. then I needed to install the ionos api part. When I now try to renew or even create a new certificate I always get an 401 error and it seems the api wants dns_ionos_token instead of dns_ionos_prefix (manually created this entry)

**Comment by rezzorix** [comment]
Not sure what you mean with “manually created”…
You get both the token and the prefix from ionos. 

Please refer to the api help and api documentation where you can test out and get direct feedback.
