### ISSUE TITLE
Tested V3 

### ISSUE THREAD

**Issue by raulfg3** [NginxProxyManager/nginx-proxy-manager#4194]
I Tested latest V3 on docker and see this error on log and login page do not load

`docker compose logs ...
proxymanager_v3  | ❯ Configuring npm user ...
proxymanager_v3  | ❯ Configuring npm group ...
proxymanager_v3  | ❯ Checking paths ...
proxymanager_v3  | ❯ Setting ownership ...
proxymanager_v3  | ❯ Dynamic resolvers ...
proxymanager_v3  | s6-rc: warning: unable to start service prepare: command exited 127
proxymanager_v3  | /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
proxymanager_v3  | ❯ Configuring npm user ...
proxymanager_v3  | 1001
proxymanager_v3  | usermod: no changes
proxymanager_v3  | ❯ Configuring npm group ...
proxymanager_v3  | ❯ Checking paths ...
proxymanager_v3  | ❯ Setting ownership ...
proxymanager_v3  | ❯ Dynamic resolvers ...
proxymanager_v3  | s6-rc: warning: unable to start service prepare: command exited 127
proxymanager_v3  | /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.

END OF LINE`

V3 tested is:  
![image](https://github.com/user-attachments/assets/f42f0bea-ac2a-434a-9cd3-2130556f9943)

PD: You see 2 errors, because I reset docker to see if something changes.  latest version works fine.

**Comment by dscham** [comment]
I don't know what you are doing with v3, but I'd say it looks like it's very fresh still. Nothing does anything really. At least the image I pulled today.

**Comment by raulfg3** [comment]
I only test it on a test machine. thanks to publish.

I'll wait next images to see evolution.

**Comment by artenais** [comment]
To add for debug this happens only when using a HostPath/Local persistent volume. If I do not add anything it starts up correctly.

**Comment by raulfg3** [comment]
yes, as you says, using volume: start well.

![V3-1 2024-12-02 165722](https://github.com/user-attachments/assets/4467ab97-a551-4335-9505-4af0476a5b9e)

**Comment by artenais** [comment]
You mean docker volume? I am trying it on Kubernetes with no luck. Can you share your config?

**Comment by raulfg3** [comment]
yes, shared.

`services:
  proxymanager_v3:
    image: 'jc21/nginx-proxy-manager:v3'
    container_name: proxymanager_v3
    networks:
      my-net:
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DISABLE_IPV6='true'
    ports:
      - '90:80'
      - '81:81'
      - '450:443'
    volumes:
      # - CHANGE_TO_COMPOSE_DATA_PATH/Dockers/proxymanager_v3:/data
      # - CHANGE_TO_COMPOSE_DATA_PATH/Dockers/proxymanager_v3/letsencrypt:/etc/letsencrypt
      - NPMVolume:/data
      - NPMCert:/etc/letsencrypt
    restart: unless-stopped
networks:
  my-net:
    external: true
volumes:
  NPMVolume:
  NPMCert:
[NPMV3.txt](https://github.com/user-attachments/files/17984209/NPMV3.txt)
`

**Comment by raulfg3** [comment]
[NPMV3.txt](https://github.com/user-attachments/files/17984227/NPMV3.txt)
