### ISSUE TITLE
Reverse proxy works erraticatly

### ISSUE THREAD

**Issue by ranademiradafija** [NginxProxyManager/nginx-proxy-manager#4233]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes

**Describe the bug**

I have been using HomeAssistant container version without problems with reverse proxy (NGINX) until HA version 2024.10.4.
My surprise is that from version 2024.11.0B1 the reverse proxy does not work well with HA. The connection with HA has random cuts both in the web interface and with the Android app "connection lost. Reconnecting....".

**Nginx Proxy Manager Version**
v2.12.1

**Comment by Starstrike** [comment]
Hmm you made this 3 days ago yet the latest version for Home Assistant Core is 2024.12.3.

I also use Home Assistant in a Docker container with nginx proxy manager and have no issues with the website or the app.

**Comment by ranademiradafija** [comment]
> Hmm you made this 3 days ago yet the latest version for Home Assistant Core is 2024.12.3.
> 
> I also use Home Assistant in a Docker container with nginx proxy manager and have no issues with the website or the app.

Thank you for your answer.
I try to use 2024.12.3 with the same result.
It's a frustration, because i find nothing, It's very strange.
Now I'm migrating to Proxmox in order to replicate de problem and to be more flexible,

**Comment by ranademiradafija** [comment]
> Since you are using the container version, can you check and make sure that the container does not share a MAC address with any other containers in the same docker network?

I've try to do this and i didn`t found problems wirh MAC adresses, but I have managed to isolate the problem, I think that is related with some rule of my WAN router server (when traffic of reverse proxy passes through it) becouse If I use reverse proxy in local I don`t have any problems. (sorry for my English) ;)
The strange thing is that it only happens from version 2024.11.0, I'm amazed.

**Comment by ranademiradafija** [comment]
Well, I finally found the problem. Newer versions of Homa Assistant use a higher number of websocket connections. I had the connection limit set low in my firewall to avoid DDoS attacks. I have increased the number of allowed connections and now everything works fine.
