### ISSUE TITLE
Changing Listening Ports

### ISSUE THREAD

**Issue by jonny190** [NginxProxyManager/nginx-proxy-manager#55]
Is there a way to change the listening ports from 8080 and 4443 to 80 and 443?

**Comment by jc21** [comment]
If you're referring to [this config file](https://github.com/jc21/nginx-proxy-manager/blob/master/docker-compose.yml), that's only a development file and not to be used for production. The [installation instructions](https://github.com/jc21/nginx-proxy-manager/blob/master/doc/INSTALL.md) specify the ports 80/443 in all examples. But still, you should still be in control of your docker execution. I don't understand that you can't change the ports, I don't use macvlan but if the docker image exposes 80/81/443 and if your docker runs without specifying any ports, they are the ports that will be used.

I feel that this problem you're having relates to any docker container and is not specific to this project.

**Comment by jonny190** [comment]
sorry for the delay in getting back to you. the docker composer file on hub.docker.com shows:
    # Change the HTTPs port 443 to the unprivileged port 4443.
    sed-patch 's|listen 443 |listen 4443 |' /etc/nginx/conf.d/default.conf && \
    sed-patch 's|listen 443 |listen 4443 |' /opt/nginx-proxy-manager/src/backend/templates/_listen.conf && \

and:
# Expose ports.
#   - 8080: HTTP traffic
#   - 4443: HTTPs traffic
#   - 8181: Management web interface
EXPOSE 8080 4443 8181

can these not be configured to listen on the native 80 and 443?

**Comment by matt-cylanda** [comment]
I have the same question

**Comment by pwrsoft** [comment]
Try to use this docker-compose.yml config file:

version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8080:80'
      - '8181:81'
      - '4443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
