### ISSUE TITLE
Unable to set Wildcard Subdomain

### ISSUE THREAD

**Issue by socheatsok78** [NginxProxyManager/nginx-proxy-manager#596]
**Describe the bug**
- A clear and concise description of what the bug is.
- What version of Nginx Proxy Manager is reported on the login page?

**To Reproduce**
1. Go to 'Proxy Host'
2. Click on 'New Proxy Host'
3. Scroll down to 'Domain Names'
4. Add `*.example.com`

**Expected behavior**
Unable to add `*.example.com`

**Screenshots**
This is the example screenshot on your website: 

![image](https://user-images.githubusercontent.com/4363857/92303233-15087080-ef9d-11ea-93a7-7d617a89840b.png)

**Comment by leimantas** [comment]
It works when I create cert from SSL CERTIFICATES menu. I can create wildcard domain. 

Is it because of this filter?
 
https://github.com/jc21/nginx-proxy-manager/blob/master/frontend/js/app/nginx/certificates/form.js#L200
![image](https://user-images.githubusercontent.com/46538777/92575855-1aa9d300-f289-11ea-8ee1-c1afcc708db0.png)

https://github.com/jc21/nginx-proxy-manager/blob/master/frontend/js/app/nginx/proxy/form.js#L227
![image](https://user-images.githubusercontent.com/46538777/92575774-08c83000-f289-11ea-8fbc-8c44c51ed008.png)

**Comment by socheatsok78** [comment]
I think that might be the issue, have been looking at that too.

**Comment by leimantas** [comment]
Any news? Now I manually edit generated nginx file.

**Comment by launtony** [comment]
@leimantas How do you do that manually? What is the modified file?

**Comment by leimantas** [comment]
Make folder for data files, mount it and then after creating PROXY sub.domain.com - go to this folder/nginx/proxy_host ; And there you will find generated conf file. Just edit this line: **server_name sub.domain.com**; int to this: **server_name *.domain.com**;

**Comment by socheatsok78** [comment]
The latest update seem to fixed the issues with wildcard domain proxy.
But I haven't had time to try it yet.

![image](https://user-images.githubusercontent.com/4363857/97069114-fd8e5100-15f7-11eb-8669-1f4f1bcabb3c.png)

**Comment by launtony** [comment]
@socheatsok78 I'm running the latest version and the wildcard is not supported :/ You don't have the "Add" button :/

**Comment by leimantas** [comment]
Ye, not working.

**Comment by felixgeissler** [comment]
I ran into that same bug. Will have to live with a custom config for now...

**Comment by benricok** [comment]
Update? Otherwise manually editing the file will have to do.

**Comment by chaptergy** [comment]
It is possible to add a wildcard certificate through the dedicated _SSL Certificates_ tab. You'll need to do the dns challenge then, so your dns provider needs to be supported. It is not possible to add a wildcard certificate from within the create host popup, so you will have to create the certificate beforehand.

**Comment by dawnerd** [comment]
Latest version still has this problem. Was able to add on an older instance but adding a wildcard subdomain (not a cert) still fails.

**Comment by chaptergy** [comment]
Ah, sorry, Ivwas ging through these issues quickly, I Seen to have misubderstood. Sorry.
