### ISSUE TITLE
OpenVPN Configuration

### ISSUE THREAD

**Issue by bwees** [NginxProxyManager/nginx-proxy-manager#866]
**What is troubling you?**

I am trying to put an OpenVPN server with only port 1194 exposed behind NPM. I would like to be able to set my ovpn client to vpm.domain.com instead of my public IP address. This is so I am not exposing port 1194 on my router and instead am only exposing 80 and 443 which NPM is listening on. What configuration do I have to do inside of NPM to allow the client to point to vpn.domain.com and it goes through Nginx and onto the VPN server. I know that this is similar to #274 but, I could not discern a clear configuration. I have tried to do a simple proxy where vpn.domain.com forwards to 10.0.1.51:1194 (the ovpn server) but the connection fails and from what I can tell, the server is not seeing any traffic trying to connect to it

**Comment by dixi83** [comment]
I found this topic on the Nginx forums:
https://forum.nginx.org/read.php?11,260587
It seems to be possible. But I don't see how to configure this in NPM...

**Comment by chaptergy** [comment]
Proxying both http and non-http protocols on the same port is non-trivial and relies on SNI, which apparently is NOT provided by most OpenVPN clients. So it seems you need specific clients for this to work anyways.
If it were possible you would have to use the image from PR https://github.com/jc21/nginx-proxy-manager/pull/1479 (`jc21/nginx-proxy-manager:github-pr-1479`) and add it as an ssl passthough host as described [here](https://github.com/jc21/nginx-proxy-manager/blob/70163a66fbe524856df64b83252e3b26244ac0d0/docs/advanced-config/README.md#ssl-passthrough).
